# -*- coding: utf-8 -*-\n# build_app_data.py\nimport json\n\nproducts = [
  {
    "segment": "Sector Público",
    "tipo": "Software",
    "linea": "Línea PitchLab",
    "tags": [
      "PitchLab",
      "Discurso Político",
      "IA Generativa",
      "Claude",
      "Listo para la venta"
    ],
    "readyForSale": true,
    "name": "PitchLab360",
    "slogan": "Analiza el discurso, mejora el mensaje",
    "description": "Análisis de discurso político con Claude (Anthropic). Perfil comunicativo, análisis emocional, stakeholders, encuadres narrativos y potencial digital. Probado con candidatos presidenciales.",
    "status": "En línea",
    "demoMode": "mostrar",
    "appUrl": "https://pitchlab360-production.up.railway.app/",
    "githubUrl": "https://github.com/Juansotag/PitchLab360",
    "logo": "assets/projects/pitchlab360.jpg",
    "videoUrl": "https://drive.google.com/file/d/1bYLxn5TCm_Hwq6DG7-u7UYui5N5szYUm/view?usp=drive_link",
    "pptUrl": ""
  },
  {
    "segment": "Sector Público",
    "tipo": "Software",
    "linea": "Línea PitchLab",
    "tags": [
      "PitchLab",
      "Fact-checking",
      "Chrome Extension",
      "GPT-4o",
      "Listo para la venta"
    ],
    "readyForSale": true,
    "name": "Polycheck",
    "slogan": "Verifica en tiempo real, no después",
    "description": "Extensión de Chrome para fact-checking en tiempo real sobre videos de YouTube y directos. Integración GPT-4o + Gemini + Google Search para análisis forense del discurso.",
    "status": "En línea",
    "demoMode": "mostrar",
    "appUrl": "",
    "githubUrl": "https://github.com/Juansotag/Polycheck",
    "logo": "assets/projects/polycheck.jpg",
    "videoUrl": "https://drive.google.com/file/d/111GwtqEWziIQFwi8BxMgQhiR6ZT-o2YW/view?usp=drive_link",
    "pptUrl": ""
  },
  {
    "segment": "Sector Privado",
    "tipo": "Software",
    "linea": "Línea PitchLab",
    "tags": [
      "PitchLab",
      "Pitch Médico",
      "INVIMA",
      "Entrenamiento",
      "Listo para la venta"
    ],
    "readyForSale": true,
    "name": "PitchLab Med",
    "slogan": "Practica tu pitch médico con estándares INVIMA",
    "description": "Plataforma para la práctica y evaluación de pitch médicos con medidas de rigurosidad INVIMA. Entrenamiento conversacional para profesionales e industria farmacéutica.",
    "status": "En línea",
    "demoMode": "mostrar",
    "appUrl": "https://pitchlab-med.up.railway.app/",
    "githubUrl": "https://github.com/Juansotag/PitchLab360-comercial",
    "logo": "assets/projects/pitchlab360.jpg",
    "videoUrl": "",
    "pptUrl": ""
  },
  {
    "segment": "Sector Público",
    "tipo": "Software",
    "linea": "Línea PitchLab",
    "tags": [
      "PitchLab",
      "Avatar en Vivo",
      "Voz en Tiempo Real",
      "Negociación",
      "Listo para la venta"
    ],
    "readyForSale": true,
    "name": "PitchLab Entrenamiento",
    "slogan": "Avatar conversacional para entrenamiento",
    "description": "Herramienta de la Línea PitchLab para el entrenamiento de conversaciones en voz en vivo, adaptado para negociaciones políticas, comerciales o académicas.",
    "status": "En línea",
    "demoMode": "mostrar",
    "appUrl": "https://avatarentrenamiento.up.railway.app/",
    "githubUrl": "https://github.com/Juansotag/Avatar_entrenamiento",
    "logo": "assets/projects/pitchlab360.jpg",
    "videoUrl": "",
    "pptUrl": ""
  },
  {
    "segment": "Sector Público",
    "tipo": "Software",
    "linea": "Línea GovTest & Opinión",
    "tags": [
      "GovTest",
      "Afinidad Política",
      "Elecciones 2026",
      "Viral",
      "Listo para la venta"
    ],
    "readyForSale": true,
    "name": "GovTest",
    "slogan": "Descubre tu candidato con datos",
    "description": "Test de afinidad política por dilemas de política pública. 16 preguntas, 14 candidatos presidenciales 2026, 7 arquetipos de votante y tarjeta viral descargable.",
    "status": "En línea",
    "demoMode": "mostrar",
    "appUrl": "https://convergencia-electoral.up.railway.app/",
    "githubUrl": "https://github.com/GovLabSabana/test-dilema",
    "logo": "assets/projects/govtest.jpg",
    "videoUrl": "https://drive.google.com/file/d/1B1RWm_HmN4HlHjiIzlDzh58FqfGpITkX/view?usp=drive_link",
    "pptUrl": ""
  },
  {
    "segment": "Sector Público",
    "tipo": "Software",
    "linea": "Línea GovTest & Opinión",
    "tags": [
      "GovTest",
      "9 Ejes Ideológicos",
      "Supabase",
      "Ranking",
      "Listo para la venta"
    ],
    "readyForSale": true,
    "name": "Test 9 Ejes",
    "slogan": "Tu posición en 9 ejes, tu candidato en un clic",
    "description": "Test de afinidad política por 9 ejes ideológicos. Algoritmo euclidiano, ranking de candidatos, perfil personalizado y persistencia de datos en Supabase.",
    "status": "En línea",
    "demoMode": "mostrar",
    "appUrl": "https://test9ejes.up.railway.app/",
    "githubUrl": "https://github.com/GovLabSabana/Test_9ejes",
    "logo": "assets/projects/test9ejes.jpg",
    "videoUrl": "https://drive.google.com/file/d/1IpEH495QROwq8k3VdkaD52tjbJKX68Iv/view?usp=drive_link",
    "pptUrl": ""
  },
  {
    "segment": "Sector Público",
    "tipo": "Software",
    "linea": "Línea GovTest & Opinión",
    "tags": [
      "GovTest",
      "50 Preguntas",
      "Coyuntura Colombia",
      "Glassmorphism",
      "Listo para la venta"
    ],
    "readyForSale": true,
    "name": "Test 9 Ejes Colombia",
    "slogan": "50 preguntas, un perfil ideológico",
    "description": "Versión extendida del test con 50 preguntas coyunturales sobre Colombia. Modo oscuro glassmorphism, compartir en alta resolución y datos anónimos en Supabase.",
    "status": "En línea",
    "demoMode": "mostrar",
    "appUrl": "https://test9col.up.railway.app/",
    "githubUrl": "https://github.com/GovLabSabana/Test_9ejesColombia",
    "logo": "assets/projects/test9ejes.jpg",
    "videoUrl": "https://drive.google.com/file/d/1gXzEi2ZNE4daXYBnidmccgcgkWj2Db84/view?usp=drive_link",
    "pptUrl": ""
  },
  {
    "segment": "Sector Público",
    "tipo": "Software",
    "linea": "Asistentes de Voz",
    "tags": [
      "Asistentes de Voz",
      "LiveKit",
      "OpenAI Realtime",
      "Cajicá",
      "WebRTC"
    ],
    "readyForSale": false,
    "name": "AlcaldesaIA",
    "slogan": "Pregúntale al municipio, él te responde",
    "description": "Asistente de voz en tiempo real sobre el Plan de Desarrollo de Cajicá 2024-2027. OpenAI Realtime API + LiveKit + WebRTC.",
    "status": "En mantenimiento",
    "demoMode": "mostrar",
    "appUrl": "https://asistente-virtual-cajica.up.railway.app/",
    "githubUrl": "https://github.com/GovLabSabana/cajica",
    "logo": "assets/projects/alcaldesa.png",
    "videoUrl": "",
    "pptUrl": ""
  },
  {
    "segment": "Sector Privado",
    "tipo": "Software",
    "linea": "Asistentes de Voz",
    "tags": [
      "Asistentes de Voz",
      "PQRS",
      "LiveKit",
      "OpenAI Realtime",
      "Santander",
      "Listo para la venta"
    ],
    "readyForSale": true,
    "name": "Gober Santander",
    "slogan": "Un asistente público para cada ciudadano",
    "description": "Asistente de voz conversacional para el sector público. Procesamiento de PQRS, visualización de datos e interfaz para funcionarios con OpenAI Realtime + LiveKit.",
    "status": "En línea",
    "demoMode": "mostrar",
    "appUrl": "https://santander-production.up.railway.app/",
    "githubUrl": "https://github.com/GovLabSabana/Santander",
    "logo": "assets/projects/gober.png",
    "videoUrl": "https://drive.google.com/file/d/1JZj-tysFp6FlbX3NeH5Y4pINnr_1dNzg/view?usp=drive_link",
    "pptUrl": ""
  },
  {
    "segment": "Sector Público",
    "tipo": "Software",
    "linea": "Asistentes de Voz",
    "tags": [
      "Asistentes de Voz",
      "GovLab",
      "Atención al Ciudadano"
    ],
    "readyForSale": false,
    "name": "Govi",
    "slogan": "El GovLab te habla, tú lo escuchas",
    "description": "Asistente basado en voz para la consulta y acercamiento al cliente del Laboratorio de Gobierno de la Universidad de La Sabana.",
    "status": "En mantenimiento",
    "demoMode": "mostrar",
    "appUrl": "",
    "githubUrl": "https://github.com/GovLabSabana/Govi2",
    "logo": "assets/Govlab.png",
    "videoUrl": "",
    "pptUrl": ""
  },
  {
    "segment": "Sector Privado",
    "tipo": "Software",
    "linea": "Asistentes de Voz",
    "tags": [
      "Asistentes de Voz",
      "Next.js",
      "LiveKit",
      "Silero VAD",
      "ConvergenceLab",
      "Listo para la venta"
    ],
    "readyForSale": true,
    "name": "ConvergenceLab",
    "slogan": "Habla con la universidad, ella te escucha",
    "description": "Asistente de voz en tiempo real para el Convergence Lab de la Unisabana (Sabius). Permite consultar aliados e investigaciones relevantes. LiveKit Agents + OpenAI Realtime API + Silero VAD.",
    "status": "En línea",
    "demoMode": "mostrar",
    "appUrl": "https://convergencelab.up.railway.app/",
    "githubUrl": "https://github.com/GovLabSabana/ConvergenceLAb",
    "logo": "assets/projects/convergence.png",
    "videoUrl": "https://drive.google.com/file/d/1r-HPmA_JXTUB45rQpJKJ7RzEZwTaReno/view?usp=drive_link",
    "pptUrl": ""
  },
  {
    "segment": "Sector Privado",
    "tipo": "Software",
    "linea": "Asistentes de Voz",
    "tags": [
      "Asistentes de Voz",
      "Llamadas Automatizadas",
      "Dapta",
      "Outbound Calls",
      "Listo para la venta"
    ],
    "readyForSale": true,
    "name": "Alocandidato",
    "slogan": "La campaña que llama, nunca la que cansa",
    "description": "Sistema de llamadas de voz automatizadas a ciudadanos con preguntas interactivas sobre candidatos y propuestas con tecnología Dapta.",
    "status": "En línea",
    "demoMode": "mostrar",
    "appUrl": "",
    "githubUrl": "",
    "logo": "assets/projects/alocandidato.jpg",
    "videoUrl": "https://drive.google.com/file/d/1bOY7U-cqev5172oxBTSLvazsdPdM2hTT/view?usp=drive_link",
    "pptUrl": ""
  },
  {
    "segment": "Sector Privado",
    "tipo": "Software",
    "linea": "Agroindustria & Exportación",
    "tags": [
      "Corpohass",
      "Aguacate Hass",
      "Trazabilidad",
      "FastAPI",
      "React",
      "Listo para la venta"
    ],
    "readyForSale": true,
    "name": "HassApp",
    "slogan": "Del campo al mundo, con datos",
    "description": "Plataforma integral para gestión de producción, cosecha, insumos, exportación y sondeo de opinión del sector aguacate Hass. FastAPI + React + MySQL + AWS S3.",
    "status": "En línea",
    "demoMode": "mostrar",
    "appUrl": "https://heartfelt-success-production-8486.up.railway.app/",
    "githubUrl": "https://github.com/GovLabSabana/HassApp",
    "logo": "assets/projects/hassapp.png",
    "videoUrl": "https://drive.google.com/file/d/1WMHMOz0j_DHamcykskRayQAUyCyPpryw/view?usp=drive_link",
    "pptUrl": ""
  },
  {
    "segment": "Sector Privado",
    "tipo": "Software",
    "linea": "Agroindustria & Exportación",
    "tags": [
      "Corpohass",
      "Diagnóstico Exportador",
      "Termómetro IA",
      "FastAPI",
      "Listo para la venta"
    ],
    "readyForSale": true,
    "name": "ExportaCheck",
    "slogan": "¿Listo para exportar? Descúbrelo hoy",
    "description": "Plataforma con termómetro interactivo que evalúa el nivel de preparación exportadora de empresas agrícolas y productoras. Diagnóstico por dimensiones con IA. Next.js + FastAPI + Supabase.",
    "status": "En línea",
    "demoMode": "mostrar",
    "appUrl": "https://exporta-facil-bot-production-e49c.up.railway.app/",
    "githubUrl": "https://github.com/GovLabSabana/TermoExportador",
    "logo": "assets/projects/exportacheck.jpg",
    "videoUrl": "https://drive.google.com/file/d/1X7QuSOTr0gCKC7rLTdSzvLsoyWHbyw_i/view?usp=drive_link",
    "pptUrl": ""
  },
  {
    "segment": "Sector Privado",
    "tipo": "Software",
    "linea": "Notarías & Documental",
    "tags": [
      "Notarías",
      "Borradores de Escrituras",
      "Chat IA",
      "Cumplimiento",
      "Listo para la venta"
    ],
    "readyForSale": true,
    "name": "NotariaDoc",
    "slogan": "El borrador perfecto, sin esperas",
    "description": "MVP para construir borradores de escrituras notariales, verificación de requisitos de cumplimiento y asistente conversacional con RAG legal.",
    "status": "En línea",
    "demoMode": "mostrar",
    "appUrl": "https://notariadoc-production.up.railway.app/",
    "githubUrl": "https://github.com/GovLabSabana/NotariaDoc",
    "logo": "assets/Govlab.png",
    "videoUrl": "https://drive.google.com/file/d/1BNngISeVJ6rFuEdgpbrmGFCxAjOLwgFE/view?usp=drive_link",
    "pptUrl": ""
  },
  {
    "segment": "Sector Privado",
    "tipo": "Software",
    "linea": "Notarías & Documental",
    "tags": [
      "Notarías",
      "Panel de Control",
      "Pronóstico",
      "Tiempos de Espera",
      "Listo para la venta"
    ],
    "readyForSale": true,
    "name": "NotariaIQ",
    "slogan": "Control total de la notaría en un panel",
    "description": "Panel de control para notarías: seguimiento de usuarios, tiempos de espera, ingresos, egresos, análisis descriptivo y pronóstico de afluencia con IA.",
    "status": "En línea",
    "demoMode": "mostrar",
    "appUrl": "https://notariaiq-production.up.railway.app/",
    "githubUrl": "https://github.com/GovLabSabana/NotariaIQ",
    "logo": "assets/Govlab.png",
    "videoUrl": "https://drive.google.com/file/d/19wx_KXzy9Byorjwu40xK5E3ymxglD_aO/view?usp=drive_link",
    "pptUrl": ""
  },
  {
    "segment": "Sector Privado",
    "tipo": "Software",
    "linea": "Notarías & Documental",
    "tags": [
      "Notarías",
      "Constructoras",
      "Flujo de Aprobación",
      "Cero Papel",
      "Listo para la venta"
    ],
    "readyForSale": true,
    "name": "Radica Notaría",
    "slogan": "Radica, revisa y aprueba sin papel",
    "description": "Suite de automatización documental para la Notaría Segunda de Zipaquirá. Formulario para constructoras + panel de digitadora con flujo de aprobación de escrituras.",
    "status": "En línea",
    "demoMode": "mostrar",
    "appUrl": "https://radicanotaria-production.up.railway.app/",
    "githubUrl": "https://github.com/GovLabSabana/Radica_notaria",
    "logo": "assets/Govlab.png",
    "videoUrl": "https://drive.google.com/file/d/1cmOw8OCh4UhW1YzWrMBpbsMvaZZjnrSV/view?usp=drive_link",
    "pptUrl": ""
  },
  {
    "segment": "Sector Público",
    "tipo": "Software",
    "linea": "Proyección Social & Directiva",
    "tags": [
      "Gestión Documental",
      "Alto Gobierno",
      "Síntesis Ejecutiva",
      "Decisiones",
      "Listo para la venta"
    ],
    "readyForSale": true,
    "name": "Resume Expedientes",
    "slogan": "Decisiones de alto gobierno en segundos",
    "description": "Herramienta con IA para resumir expedientes directivos complejos y apoyar la toma de decisiones estratégicas de alto gobierno.",
    "status": "En línea",
    "demoMode": "mostrar",
    "appUrl": "https://expedientes.up.railway.app/",
    "githubUrl": "https://github.com/Juansotag/resumidor-expedientes",
    "logo": "assets/Govlab.png",
    "videoUrl": "",
    "pptUrl": ""
  },
  {
    "segment": "Sector Público",
    "tipo": "Software",
    "linea": "Proyección Social & Directiva",
    "tags": [
      "Proyección Social",
      "CRON",
      "WhatsApp",
      "Email",
      "Newsletter",
      "Listo para la venta"
    ],
    "readyForSale": true,
    "name": "NewsletterMaker",
    "slogan": "Generador y envío de newsletter",
    "description": "Plataforma para la construcción de Newsletters y la asignación de procesos asíncronos CRON por correo y WhatsApp para la Dirección de Proyección Social.",
    "status": "En línea",
    "demoMode": "mostrar",
    "appUrl": "https://newsletter-pse.up.railway.app/",
    "githubUrl": "https://github.com/Juansotag/Newsletter---Proyecci-n-social",
    "logo": "assets/Govlab.png",
    "videoUrl": "",
    "pptUrl": ""
  },
  {
    "segment": "Sector Público",
    "tipo": "Software",
    "linea": "Gestión Pública & Ambiental",
    "tags": [
      "CAR Cundinamarca",
      "PQRS Automático",
      "IA",
      "Clasificación",
      "Listo para la venta"
    ],
    "readyForSale": true,
    "name": "CAResponde",
    "slogan": "De la PQRS al ciudadano en segundos",
    "description": "Asistente en texto para la CAR Cundinamarca: recibe, categoriza, visualiza y genera respuestas automáticas a PQRS con inteligencia artificial.",
    "status": "En línea",
    "demoMode": "mostrar",
    "appUrl": "https://car-pqrs-production.up.railway.app/",
    "githubUrl": "https://github.com/GovLabSabana/CAR-pqrs",
    "logo": "assets/projects/caresponde.png",
    "videoUrl": "https://drive.google.com/file/d/1Z9kNrQxgHan2YKVw9oRovIzGJfLPp86j/view?usp=drive_link",
    "pptUrl": ""
  },
  {
    "segment": "Sector Público",
    "tipo": "Software",
    "linea": "Gestión Pública & Ambiental",
    "tags": [
      "Bogotá",
      "Plan de Desarrollo",
      "RAG FAISS",
      "GPT-4o",
      "Listo para la venta"
    ],
    "readyForSale": true,
    "name": "AlcaldIA",
    "slogan": "El Plan de Desarrollo en tus manos",
    "description": "Asistente RAG sobre el Plan de Desarrollo Distrital de Bogotá. Búsqueda semántica con FAISS + GPT-4o para consultas por meta, programa y presupuesto.",
    "status": "En línea",
    "demoMode": "mostrar",
    "appUrl": "https://alcadia.up.railway.app/",
    "githubUrl": "https://github.com/GovLabSabana/AlcaldIA",
    "logo": "assets/Govlab.png",
    "videoUrl": "https://drive.google.com/file/d/1rfDiEcx6BD2r3HDHG5GSUVze8Bd8O9ww/view?usp=drive_link",
    "pptUrl": ""
  },
  {
    "segment": "Sector Público",
    "tipo": "Software",
    "linea": "Gestión Pública & Ambiental",
    "tags": [
      "Policía Ambiental",
      "Legislación Ambiental",
      "Jurisprudencia",
      "Carabineros"
    ],
    "readyForSale": false,
    "name": "PoliciApp-Eco",
    "slogan": "La ley ambiental en campo",
    "description": "Asistente IA de legislación ambiental colombiana para la Policía Ambiental y Carabineros. Cubre pesca, flora, fauna, minería y recursos hídricos.",
    "status": "En mantenimiento",
    "demoMode": "mostrar",
    "appUrl": "",
    "githubUrl": "https://github.com/GovLabSabana/PoliciApp-Eco2",
    "logo": "assets/Govlab.png",
    "videoUrl": "",
    "pptUrl": ""
  },
  {
    "segment": "Sector Público",
    "tipo": "Software",
    "linea": "Gestión Pública & Ambiental",
    "tags": [
      "Policía Ambiental",
      "Normativa Ambiental",
      "Jurisprudencia",
      "Chatbot"
    ],
    "readyForSale": false,
    "name": "PoliciaAmbiental",
    "slogan": "Jurisprudencia ambiental en campo",
    "description": "Chatbot para facilitar conocimientos de jurisprudencia y competencias operativas para la policía ambiental de Colombia.",
    "status": "En mantenimiento",
    "demoMode": "mostrar",
    "appUrl": "",
    "githubUrl": "https://github.com/GovLabSabana/Policia_ambiental",
    "logo": "assets/Govlab.png",
    "videoUrl": "",
    "pptUrl": ""
  },
  {
    "segment": "Sector Público",
    "tipo": "Software",
    "linea": "Gestión Pública & Ambiental",
    "tags": [
      "Comparación Normativa",
      "Diff Semántico",
      "GPT-4",
      "Leyes"
    ],
    "readyForSale": false,
    "name": "LegisCheck",
    "slogan": "Dos versiones, un solo vistazo",
    "description": "Comparación inteligente de documentos legislativos. Diff semántico con GPT-4, línea de tiempo de cambios normativos y reportes PDF.",
    "status": "En mantenimiento",
    "demoMode": "mostrar",
    "appUrl": "",
    "githubUrl": "https://github.com/GovLabSabana/Paralelo",
    "logo": "assets/projects/Legischeck.png",
    "videoUrl": "",
    "pptUrl": ""
  },
  {
    "segment": "Sector Público",
    "tipo": "Software",
    "linea": "Seguridad & Analítica",
    "tags": [
      "Observatorio de Seguridad",
      "Predicción Delitos",
      "Barranquilla",
      "Listo para la venta"
    ],
    "readyForSale": true,
    "name": "Barranquilla",
    "slogan": "Predice la criminalidad, protege la ciudad",
    "description": "App web para subir, analizar y predecir eventos de criminalidad y convivencia ciudadana para el Observatorio de Seguridad de Barranquilla.",
    "status": "En línea",
    "demoMode": "mostrar",
    "appUrl": "https://barranquilla-production.up.railway.app/",
    "githubUrl": "https://github.com/GovLabSabana/Barranquilla",
    "logo": "assets/Govlab.png",
    "videoUrl": "https://drive.google.com/file/d/1X7_dn5FwxNv9XvoflFxJrNYQPzxmr8DJ/view?usp=drive_link",
    "pptUrl": ""
  },
  {
    "segment": "Sector Privado",
    "tipo": "Software",
    "linea": "Sostenibilidad & ESG",
    "tags": [
      "Universia",
      "ESG",
      "Benchmarking",
      "Supabase",
      "React",
      "Listo para la venta"
    ],
    "readyForSale": true,
    "name": "Test de sostenibilidad universitaria",
    "slogan": "Mide tu sostenibilidad, mejora tu ranking",
    "description": "Sistema de evaluación universitaria en dimensiones Gobernanza, Social y Ambiental (ESG). Dashboard comparativo entre instituciones. React + Node + Supabase.",
    "status": "En línea",
    "demoMode": "mostrar",
    "appUrl": "https://bot-sostenibilidad-esg.up.railway.app/",
    "githubUrl": "https://github.com/GovLabSabana/Universia",
    "logo": "assets/projects/sostenibilidad.jpg",
    "videoUrl": "https://drive.google.com/file/d/1GDyYWyFkWJktyAc-a9Alec8xrri4dNEU/view?usp=drive_link",
    "pptUrl": ""
  },
  {
    "segment": "Sector Privado",
    "tipo": "Software",
    "linea": "Sostenibilidad & ESG",
    "tags": [
      "MetaRed",
      "Universia",
      "Agente IA",
      "Regresión",
      "Data Science",
      "Listo para la venta"
    ],
    "readyForSale": true,
    "name": "Asistente de agente para MetaRed",
    "slogan": "Resultados de encuestas sobre sostenibilidad y agente de análisis",
    "description": "Herramienta para visualizar resultados de la encuesta de sostenibilidad de MetaRed / Universia, con un agente IA capaz de correr modelos de regresión y analítica descriptiva.",
    "status": "En línea",
    "demoMode": "mostrar",
    "appUrl": "https://metaredesg.up.railway.app/",
    "githubUrl": "https://github.com/Juansotag/Metared-by-Universia",
    "logo": "assets/projects/sostenibilidad.jpg",
    "videoUrl": "",
    "pptUrl": ""
  },
  {
    "segment": "Sector Público",
    "tipo": "Software",
    "linea": "Comunidad & Admisiones",
    "tags": [
      "Escuela de Gobierno",
      "MPA",
      "CV Matching",
      "Recomendación",
      "Listo para la venta"
    ],
    "readyForSale": true,
    "name": "MPAChat",
    "slogan": "Tu perfil profesional para el MPA, en minutos",
    "description": "Asistente IA que analiza la hoja de vida de candidatos a la Maestría en Administración Pública (MPA) de la Escuela de Gobierno, recomendando líneas y perfilando aspirantes.",
    "status": "En línea",
    "demoMode": "mostrar",
    "appUrl": "https://mpachat-unisabana.up.railway.app/",
    "githubUrl": "https://github.com/Juansotag/MPAchat",
    "logo": "assets/photos/Aliados/escuela.png",
    "videoUrl": "",
    "pptUrl": ""
  },
  {
    "segment": "Sector Público",
    "tipo": "Software",
    "linea": "Comunidad & Admisiones",
    "tags": [
      "Suite Alumni",
      "Hojas de Vida",
      "Egresados",
      "Unisabana",
      "Listo para la venta"
    ],
    "readyForSale": true,
    "name": "AlumniCV",
    "slogan": "Suite Alumni - Hojas de vida",
    "description": "Herramienta para egresados de la Universidad de La Sabana enfocada en optimización, formato y gestión de hojas de vida profesionales.",
    "status": "En línea",
    "demoMode": "mostrar",
    "appUrl": "https://alumnicv.up.railway.app/",
    "githubUrl": "https://github.com/Juansotag/AlumniCV",
    "logo": "assets/Govlab.png",
    "videoUrl": "",
    "pptUrl": ""
  },
  {
    "segment": "Sector Público",
    "tipo": "Software",
    "linea": "Comunidad & Admisiones",
    "tags": [
      "Suite Alumni",
      "Acompañamiento",
      "Posgrados",
      "Chatbot",
      "Listo para la venta"
    ],
    "readyForSale": true,
    "name": "AlumniChat",
    "slogan": "Chatbot de acompañamiento para egresados",
    "description": "Chatbot de acompañamiento y orientación académica/profesional para la comunidad de egresados de la Universidad de La Sabana.",
    "status": "En línea",
    "demoMode": "mostrar",
    "appUrl": "https://alumnichat.up.railway.app/",
    "githubUrl": "https://github.com/Juansotag/AlumniChat",
    "logo": "assets/Govlab.png",
    "videoUrl": "",
    "pptUrl": ""
  },
  {
    "segment": "Sector Público",
    "tipo": "Software",
    "linea": "Innovación & Procesos",
    "tags": [
      "Innovación Unisabana",
      "Business Model Canvas",
      "Propiedad Intelectual",
      "Listo para la venta"
    ],
    "readyForSale": true,
    "name": "Germina",
    "slogan": "Asistente de innovación con IA",
    "description": "Plataforma para el seguimiento de procesos de innovación, emprendimiento y autoría intelectual de la Universidad de La Sabana. Genera documentos y apoya en Business Model Canvas.",
    "status": "En línea",
    "demoMode": "mostrar",
    "appUrl": "https://germina.up.railway.app/",
    "githubUrl": "https://github.com/Juansotag/germina",
    "logo": "assets/projects/germina.png",
    "videoUrl": "",
    "pptUrl": ""
  },
  {
    "segment": "Sector Privado",
    "tipo": "Software",
    "linea": "Inteligencia Geoespacial",
    "tags": [
      "Geoespacial",
      "Vivienda",
      "Leaflet",
      "FincaRaíz",
      "Estratos",
      "Listo para la venta"
    ],
    "readyForSale": true,
    "name": "Geovivienda",
    "slogan": "Ubica, analiza y decide dónde vivir",
    "description": "Plataforma inmobiliaria con analítica geoespacial: scraping de mercado, distancias a Transmilenio/SITP/ciclorutas, estrato promedio a 200m y mapas interactivos con Leaflet.",
    "status": "En línea",
    "demoMode": "mostrar",
    "appUrl": "https://geovivienda.up.railway.app/",
    "githubUrl": "https://github.com/Juansotag/Geovivienda-main",
    "logo": "assets/projects/geovivienda-main.png",
    "videoUrl": "https://drive.google.com/file/d/1awsOrJvFAQg4JV4zUP4_4vhpDaucnehM/view?usp=drive_link",
    "pptUrl": ""
  },
  {
    "segment": "Sector Privado",
    "tipo": "Software",
    "linea": "Analítica con IA",
    "tags": [
      "LangChain",
      "Plotly",
      "Whisper",
      "TTS",
      "Auto-Gráficos",
      "Listo para la venta"
    ],
    "readyForSale": true,
    "name": "Data Copilot",
    "slogan": "Pregúntale a tus datos con tu propia voz",
    "description": "Asistente de análisis de datos con LangChain + GPT-4 + Whisper. Carga CSV/Excel, genera gráficos interactivos con Plotly y responde por voz y texto.",
    "status": "En línea",
    "demoMode": "mostrar",
    "appUrl": "https://datacopilot.up.railway.app/",
    "githubUrl": "https://github.com/GovLabSabana/Data_copilot",
    "logo": "assets/Govlab.png",
    "videoUrl": "",
    "pptUrl": ""
  },
  {
    "segment": "Sector Público",
    "tipo": "Software",
    "linea": "Dashboards & Analítica",
    "tags": [
      "INVAMER",
      "Percepción Democrática",
      "Tiempo Real",
      "Filtros Demográficos",
      "Listo para la venta"
    ],
    "readyForSale": true,
    "name": "Cuidar la Democracia",
    "slogan": "Visualiza lo que piensa el ciudadano",
    "description": "Dashboard interactivo con datos de encuesta sobre percepciones democráticas en Colombia (INVAMER/GovLab). Filtros sociodemográficos, mapas y gráficos en tiempo real.",
    "status": "En línea",
    "demoMode": "mostrar",
    "appUrl": "https://cuidar-la-democracia-production.up.railway.app/",
    "githubUrl": "https://github.com/Juansotag/Cuidar-la-Democracia",
    "logo": "assets/projects/democracia.png",
    "videoUrl": "https://drive.google.com/file/d/1cGZzC2g1HsFeL4M3TziwMUL9o692WI-x/view?usp=drive_link",
    "pptUrl": ""
  },
  {
    "segment": "Sector Público",
    "tipo": "Software",
    "linea": "Dashboards & Analítica",
    "tags": [
      "FONDECUN",
      "Cundinamarca",
      "Sankey",
      "Mapa de Calor",
      "Reportes PDF",
      "Listo para la venta"
    ],
    "readyForSale": true,
    "name": "Data Promce",
    "slogan": "Sigue cada institución, mide cada etapa",
    "description": "Plataforma de seguimiento del programa FONDECUN en IEDs de Cundinamarca. Mapa de calor, Sankey, análisis cualitativo con IA y exportación a PDF/Excel.",
    "status": "En línea",
    "demoMode": "mostrar",
    "appUrl": "https://fondecun-production.up.railway.app/",
    "githubUrl": "https://github.com/GovLabSabana/FONDECUN",
    "logo": "assets/projects/datapromce.png",
    "videoUrl": "https://drive.google.com/file/d/1TJcmWLiAGKcxoCspHzYNniXq0ip3uiFw/view?usp=drive_link",
    "pptUrl": ""
  },
  {
    "segment": "Sector Público",
    "tipo": "Software",
    "linea": "Dashboards & Analítica",
    "tags": [
      "Sabana Centro Cómo Vamos",
      "Matching Planes",
      "Scoring IA",
      "Desarrollo Regional",
      "Listo para la venta"
    ],
    "readyForSale": true,
    "name": "Sabana Centro Sostenible",
    "slogan": "Conecta proyectos con planes de desarrollo",
    "description": "Matching entre proyectos estratégicos de Sabana Centro y planes de desarrollo municipales. Scoring semántico con IA de visión regional e impacto.",
    "status": "En línea",
    "demoMode": "mostrar",
    "appUrl": "https://sabanacentrosostenible.up.railway.app/",
    "githubUrl": "https://github.com/GovLabSabana/SCS_V2",
    "logo": "assets/projects/scsv2.png",
    "videoUrl": "https://drive.google.com/file/d/1WARAZMkb6xri4bO8MIxiPEIVHqOUqbfo/view?usp=drive_link",
    "pptUrl": ""
  },
  {
    "segment": "Sector Público",
    "tipo": "Dashboards",
    "linea": "Dashboards & Analítica",
    "tags": [
      "Tableau",
      "Metas Institucionales",
      "App Móvil",
      "Dashboard"
    ],
    "readyForSale": true,
    "name": "SIAG",
    "slogan": "Sigue en tiempo real a tu organización",
    "description": "Suite de seguimiento de metas institucionales en tiempo real con integración en aplicación web, Android e iOS.",
    "status": "En línea",
    "demoMode": "mostrar",
    "appUrl": "https://public.tableau.com/app/profile/juan.sotelo.aguilar/viz/Cardesk-Gestin/Dashboard1",
    "githubUrl": "",
    "logo": "assets/Govlab.png",
    "videoUrl": "https://drive.google.com/file/d/1iZEkSOuXZ5h4kMB0xZBnUOpvovll0vQx/view?usp=drive_link",
    "pptUrl": ""
  },
  {
    "segment": "Sector Público",
    "tipo": "Dashboards",
    "linea": "Dashboards & Analítica",
    "tags": [
      "Tableau",
      "Seguridad Ciudadana",
      "Policía Nacional",
      "Datos Abiertos"
    ],
    "readyForSale": true,
    "name": "Violencia Intrafamiliar en Colombia",
    "slogan": "Monitoreo y tendencias a nivel nacional",
    "description": "Dashboard interactivo con análisis territorial y temporal de denuncias de violencia intrafamiliar en Colombia.",
    "status": "En línea",
    "demoMode": "mostrar",
    "appUrl": "https://public.tableau.com/app/profile/juan.sotelo.aguilar/viz/Datos-Polica/Violenciaintrafamiliar",
    "githubUrl": "",
    "logo": "assets/Govlab.png",
    "videoUrl": "",
    "pptUrl": ""
  },
  {
    "segment": "Sector Público",
    "tipo": "Dashboards",
    "linea": "Dashboards & Analítica",
    "tags": [
      "Tableau",
      "Salud Pública",
      "Capacidad Hospitalaria",
      "Indicadores"
    ],
    "readyForSale": true,
    "name": "Recursos hospitalarios por cada 100.000 habitantes",
    "slogan": "Capacidad del sistema de salud en Colombia",
    "description": "Visualización comparativa de camas, médicos y recursos de atención hospitalaria en los municipios y departamentos del país.",
    "status": "En línea",
    "demoMode": "mostrar",
    "appUrl": "https://public.tableau.com/app/profile/juan.sotelo.aguilar/viz/Recursoshospitalariosporcada100_00habitantes-2022/Dashboard1",
    "githubUrl": "",
    "logo": "assets/Govlab.png",
    "videoUrl": "",
    "pptUrl": ""
  },
  {
    "segment": "Sector Público",
    "tipo": "Dashboards",
    "linea": "Dashboards & Analítica",
    "tags": [
      "Tableau",
      "ADRES",
      "Afiliaciones Salud",
      "Demografía"
    ],
    "readyForSale": true,
    "name": "Registros de la Base Única de afiliados - Adres - Mayo 2025",
    "slogan": "Radiografía del aseguramiento en salud",
    "description": "Tablero analítico de la Base de Datos Única de Afiliados (BDUA) con perfiles sociodemográficos y régimen de aseguramiento.",
    "status": "En línea",
    "demoMode": "mostrar",
    "appUrl": "https://public.tableau.com/app/profile/juan.sotelo.aguilar/viz/RegistrosdelaBasedeDatosnicadeAfiliados-ADRES-Mayo2025/Perfilesdelosafiliados",
    "githubUrl": "",
    "logo": "assets/Govlab.png",
    "videoUrl": "",
    "pptUrl": ""
  },
  {
    "segment": "Sector Público",
    "tipo": "Dashboards",
    "linea": "Dashboards & Analítica",
    "tags": [
      "Tableau",
      "Demografía",
      "Envejecimiento",
      "Políticas Poblacionales"
    ],
    "readyForSale": true,
    "name": "Envejecimiento poblacional en Colombia por Sexo y Área",
    "slogan": "Transición demográfica y territorio",
    "description": "Historia interactiva sobre las curvas de envejecimiento y pirámides poblacionales urbanas y rurales en Colombia.",
    "status": "En línea",
    "demoMode": "mostrar",
    "appUrl": "https://public.tableau.com/app/profile/juan.sotelo.aguilar/viz/EnvejecimientopoblacionalenColombiaporSexoyArea/Historia1",
    "githubUrl": "",
    "logo": "assets/Govlab.png",
    "videoUrl": "",
    "pptUrl": ""
  },
  {
    "segment": "Sector Público",
    "tipo": "Dashboards",
    "linea": "Dashboards & Analítica",
    "tags": [
      "Tableau",
      "Seguridad",
      "Extorsión",
      "Series Temporales"
    ],
    "readyForSale": true,
    "name": "Panorama de la Extorsión en Colombia (2010-2024)",
    "slogan": "Evolución de un delito de alto impacto",
    "description": "Análisis longitudinal de denuncias, modalidades y focos territoriales del delito de extorsión a lo largo de 14 años.",
    "status": "En línea",
    "demoMode": "mostrar",
    "appUrl": "https://public.tableau.com/app/profile/juan.sotelo.aguilar/viz/PanoramadelaextorsinenColombia2010-2024/Dashboard1",
    "githubUrl": "",
    "logo": "assets/Govlab.png",
    "videoUrl": "",
    "pptUrl": ""
  },
  {
    "segment": "Sector Público",
    "tipo": "Dashboards",
    "linea": "Dashboards & Analítica",
    "tags": [
      "Tableau",
      "Justicia",
      "Protección",
      "Datos Policiales"
    ],
    "readyForSale": true,
    "name": "Delitos Sexuales en Colombia",
    "slogan": "Evidencia para la protección ciudadana",
    "description": "Mapeo y caracterización de reportes de delitos sexuales para el diseño de políticas de prevención y justicia focalizada.",
    "status": "En línea",
    "demoMode": "mostrar",
    "appUrl": "https://public.tableau.com/app/profile/juan.sotelo.aguilar/viz/DelitossexualesenColombia_17300861605130/Dashboard1",
    "githubUrl": "",
    "logo": "assets/Govlab.png",
    "videoUrl": "",
    "pptUrl": ""
  },
  {
    "segment": "Sector Público",
    "tipo": "Dashboards",
    "linea": "Dashboards & Analítica",
    "tags": [
      "Tableau",
      "Demografía",
      "Cuidado",
      "Adulto Mayor"
    ],
    "readyForSale": true,
    "name": "El Panorama del envejecimiento poblacional en Colombia",
    "slogan": "Retos de la longevidad y servicios sociales",
    "description": "Dashboard integral con indicadores de dependencia, índice de envejecimiento y distribución departamental.",
    "status": "En línea",
    "demoMode": "mostrar",
    "appUrl": "https://public.tableau.com/app/profile/juan.sotelo.aguilar/viz/ElpanoramadelenvejecimientopoblacionalenColombia/Dashboard1",
    "githubUrl": "",
    "logo": "assets/Govlab.png",
    "videoUrl": "",
    "pptUrl": ""
  },
  {
    "segment": "Sector Público",
    "tipo": "Dashboards",
    "linea": "Dashboards & Analítica",
    "tags": [
      "Tableau",
      "Salud Mental",
      "Epidemiología",
      "Prevención"
    ],
    "readyForSale": true,
    "name": "Suicidios en Colombia 2023-2024",
    "slogan": "Datos para la salud mental pública",
    "description": "Monitoreo descriptivo y espacial de eventos de salud mental y suicidio reportados en el territorio nacional.",
    "status": "En línea",
    "demoMode": "mostrar",
    "appUrl": "https://public.tableau.com/app/profile/juan.sotelo.aguilar/viz/Suicidios-2023-2024/Dashboard12",
    "githubUrl": "",
    "logo": "assets/Govlab.png",
    "videoUrl": "",
    "pptUrl": ""
  },
  {
    "segment": "Sector Público",
    "tipo": "Dashboards",
    "linea": "Dashboards & Analítica",
    "tags": [
      "Tableau",
      "NUSE 123",
      "Bogotá",
      "UPZ",
      "Emergencias"
    ],
    "readyForSale": true,
    "name": "Llamadas totales al NUSE/123 por UPZ en Bogotá",
    "slogan": "Llamadas de emergencia a escala barrial",
    "description": "Distribución geográfica por Unidades de Planeamiento Zonal (UPZ) de llamadas atendidas por la línea única de emergencias de Bogotá.",
    "status": "En línea",
    "demoMode": "mostrar",
    "appUrl": "https://public.tableau.com/app/profile/juan.sotelo.aguilar/viz/LlamadastotalesalNUSEporUPZ/Vistadistrital",
    "githubUrl": "",
    "logo": "assets/Govlab.png",
    "videoUrl": "",
    "pptUrl": ""
  },
  {
    "segment": "Sector Público",
    "tipo": "Dashboards",
    "linea": "Dashboards & Analítica",
    "tags": [
      "Tableau",
      "Agro",
      "Precios Arroz",
      "Forecasting",
      "Modelos Predictivos"
    ],
    "readyForSale": true,
    "name": "Precios y productividad del arroz - Forecasting",
    "slogan": "Pronóstico de precios y cosechas agrícolas",
    "description": "Modelo predictivo de series temporales de precios mayoristas y rendimiento por hectárea en el sector arrocero.",
    "status": "En línea",
    "demoMode": "mostrar",
    "appUrl": "https://public.tableau.com/app/profile/juan.sotelo.aguilar/viz/Dashboardarroz/Dashboard1",
    "githubUrl": "",
    "logo": "assets/Govlab.png",
    "videoUrl": "",
    "pptUrl": ""
  },
  {
    "segment": "Sector Público",
    "tipo": "Dashboards",
    "linea": "Dashboards & Analítica",
    "tags": [
      "Tableau",
      "Movilidad",
      "Siniestralidad Vial",
      "Forecasting",
      "Bogotá"
    ],
    "readyForSale": true,
    "name": "Siniestralidad vial en Bogotá - Forecasting",
    "slogan": "Modelos predictivos de accidentalidad vial",
    "description": "Predicción de eventos de siniestros viales en corredores viales clave de Bogotá mediante técnicas de forecasting.",
    "status": "En línea",
    "demoMode": "mostrar",
    "appUrl": "https://public.tableau.com/app/profile/juan.sotelo.aguilar/viz/Siniestralidadvial-2019-2023V2-forecasting/SiniestralidadvialenBogotD_C_-Modelopredictivo-2019-2023",
    "githubUrl": "",
    "logo": "assets/Govlab.png",
    "videoUrl": "",
    "pptUrl": ""
  },
  {
    "segment": "Sector Público",
    "tipo": "Dashboards",
    "linea": "Dashboards & Analítica",
    "tags": [
      "Tableau",
      "Movilidad",
      "Accidentes",
      "Bogotá"
    ],
    "readyForSale": true,
    "name": "Siniestralidad vial en Bogotá - Siniestros",
    "slogan": "Registro y causas de accidentes de tránsito",
    "description": "Visualización histórica 2019-2023 de siniestros viales clasificados por tipo de vehículo, horario y localidad.",
    "status": "En línea",
    "demoMode": "mostrar",
    "appUrl": "https://public.tableau.com/app/profile/juan.sotelo.aguilar/viz/Siniestralidadvial-2019-2023V2-Siniestros/SiniestralidadvialenBogotD_C_-2019-2023",
    "githubUrl": "",
    "logo": "assets/Govlab.png",
    "videoUrl": "",
    "pptUrl": ""
  },
  {
    "segment": "Sector Público",
    "tipo": "Dashboards",
    "linea": "Dashboards & Analítica",
    "tags": [
      "Tableau",
      "Movilidad",
      "Víctimas",
      "Seguridad Vial"
    ],
    "readyForSale": true,
    "name": "Siniestralidad vial en Bogotá - Víctimas",
    "slogan": "Perfil de actores viales y lesionados",
    "description": "Tablero enfocado en peatones, ciclistas y motociclistas afectados en eventos viales en la capital.",
    "status": "En línea",
    "demoMode": "mostrar",
    "appUrl": "https://public.tableau.com/app/profile/juan.sotelo.aguilar/viz/Siniestralidadvial-2019-2023V2-Vctimas/VctimasdelasiniestralidadvialenBogotD_C_-2019-2023",
    "githubUrl": "",
    "logo": "assets/Govlab.png",
    "videoUrl": "",
    "pptUrl": ""
  },
  {
    "segment": "Sector Público",
    "tipo": "Dashboards",
    "linea": "Dashboards & Analítica",
    "tags": [
      "Tableau",
      "Geoanalítica",
      "Mapas de Calor",
      "Puntos Críticos"
    ],
    "readyForSale": true,
    "name": "Siniestralidad vial en Bogotá - Análisis espacial",
    "slogan": "Puntos críticos e intersecciones de alto riesgo",
    "description": "Análisis de concentración geoespacial de accidentes e identificación de tramos viales prioritarios para intervención.",
    "status": "En línea",
    "demoMode": "mostrar",
    "appUrl": "https://public.tableau.com/app/profile/juan.sotelo.aguilar/viz/Siniestralidadvial-2019-2023V2-Anlisisespacial/SiniestralidadvialenBogotD_C_-2019-2023-Anlisisespacial",
    "githubUrl": "",
    "logo": "assets/Govlab.png",
    "videoUrl": "",
    "pptUrl": ""
  },
  {
    "segment": "Sector Público",
    "tipo": "Dashboards",
    "linea": "Dashboards & Analítica",
    "tags": [
      "Tableau",
      "Forecasting",
      "Línea 123",
      "UPZ",
      "Capacidad Operativa"
    ],
    "readyForSale": true,
    "name": "Llamadas totales al NUSE/123 por UPZ en Bogotá - Forecasting",
    "slogan": "Pronóstico de demanda de atención de emergencias",
    "description": "Modelos predictivos de volumen de llamadas al NUSE por UPZ para optimizar el despliegue de patrullas y ambulancias.",
    "status": "En línea",
    "demoMode": "mostrar",
    "appUrl": "https://public.tableau.com/app/profile/juan.sotelo.aguilar/viz/LlamadasalNUSEporUPZ/VistaporUPZ",
    "githubUrl": "",
    "logo": "assets/Govlab.png",
    "videoUrl": "",
    "pptUrl": ""
  },
  {
    "segment": "Sector Público",
    "tipo": "Estudios & Análisis de datos",
    "linea": "Salud & Geoanalítica",
    "tags": [
      "Machine Learning",
      "Clínica Unisabana",
      "ARIMA",
      "Prophet",
      "Pacientes NO-EPS"
    ],
    "readyForSale": false,
    "name": "Análisis Clínica Universidad de la Sabana",
    "slogan": "Anticipa la demanda, optimiza los recursos",
    "description": "Sistema ML de series de tiempo (ARIMA y Prophet) con MAE inferior a 10% para pronosticar el número de pacientes NO-EPS y la facturación semanal de la Clínica.",
    "status": "Activo",
    "demoMode": "ppt",
    "appUrl": "",
    "githubUrl": "https://github.com/GovLabSabana/ModeloClinica",
    "logo": "assets/photos/Aliados/clinica.png",
    "videoUrl": "",
    "pptUrl": "assets/decks/modelo_clínica.pdf"
  },
  {
    "segment": "Sector Público",
    "tipo": "Estudios & Análisis de datos",
    "linea": "Salud & Geoanalítica",
    "tags": [
      "Geoanalítica",
      "Clínica Unisabana",
      "Pacientes Potenciales",
      "Inteligencia Territorial"
    ],
    "readyForSale": false,
    "name": "Geoanálisis Clínica Universidad de la Sabana",
    "slogan": "Encuentra al paciente antes de que llegue",
    "description": "Análisis predictivo geoespacial de la ubicación y patrones de desplazamiento de potenciales usuarios de servicios de salud privados en Sabana Centro.",
    "status": "Activo",
    "demoMode": "ppt",
    "appUrl": "",
    "githubUrl": "",
    "logo": "assets/photos/Aliados/clinica.png",
    "videoUrl": "https://drive.google.com/file/d/1KdjNdT396zr8c9nPjeeX_xjB-99c_8Ka/view?usp=drive_link",
    "pptUrl": "assets/decks/modelo_geo_clínica.pdf"
  },
  {
    "segment": "Sector Público",
    "tipo": "Estudios & Análisis de datos",
    "linea": "Políticas Públicas & Territorio",
    "tags": [
      "OSZ",
      "Zipaquirá",
      "Indicadores Sociales",
      "Observatorio Social"
    ],
    "readyForSale": false,
    "name": "Observatorio Social de Zipaquirá - OSZ",
    "slogan": "Alcaldía de Zipaquirá",
    "description": "Desarrollo y diseño del primer observatorio social de la Región Sabana Centro para el seguimiento riguroso de indicadores sociales y bienestar.",
    "status": "Activo",
    "demoMode": "ppt",
    "appUrl": "",
    "githubUrl": "",
    "logo": "assets/projects/osz.png",
    "videoUrl": "",
    "pptUrl": "assets/decks/Observatorio Social de Zipaquirá.pdf"
  },
  {
    "segment": "Sector Público",
    "tipo": "Estudios & Análisis de datos",
    "linea": "Electoral & Pronóstico",
    "tags": [
      "Pronóstico Electoral",
      "Redes Sociales",
      "Metodología ELA-NOM",
      "Error < 9%"
    ],
    "readyForSale": false,
    "name": "ELA-NOM",
    "slogan": "Pronostica elecciones con redes sociales",
    "description": "Aplicación de una novedosa metodología de pronóstico electoral (ELA-NOM) basada en minería de redes sociales con error predictivo inferior al 9%.",
    "status": "Activo",
    "demoMode": "mostrar",
    "appUrl": "",
    "githubUrl": "https://github.com/Juansotag/ELA_NOM",
    "logo": "assets/Govlab.png",
    "videoUrl": "",
    "pptUrl": ""
  },
  {
    "segment": "Transversal",
    "tipo": "Educación",
    "linea": "Educación & Formación",
    "tags": [
      "Doctorado",
      "Posgrado",
      "Investigación IA",
      "Sector Público"
    ],
    "readyForSale": true,
    "name": "Doctorado en IA",
    "slogan": "Investiga el futuro, lidera el cambio",
    "description": "Programa doctoral de investigación de vanguardia en inteligencia artificial, enfocado en soluciones para el sector público y formulación de políticas basadas en evidencia.",
    "status": "Activo",
    "demoMode": "mostrar",
    "appUrl": "https://www.unisabana.edu.co/programas/posgrados/doctorado-en-inteligencia-artificial",
    "githubUrl": "",
    "logo": "assets/Govlab.png",
    "videoUrl": "",
    "pptUrl": ""
  },
  {
    "segment": "Transversal",
    "tipo": "Educación",
    "linea": "Educación & Formación",
    "tags": [
      "Maestría",
      "Posgrado",
      "Analítica Aplicada",
      "Toma de Decisiones"
    ],
    "readyForSale": true,
    "name": "Maestría en IA",
    "slogan": "Domina la IA, transforma tu sector",
    "description": "Programa de posgrado en inteligencia artificial y analítica aplicada con énfasis en gobierno digital, política pública y gestión estratégica organizacional.",
    "status": "Activo",
    "demoMode": "mostrar",
    "appUrl": "https://www.unisabana.edu.co/programas/posgrados/maestria-en-analitica-aplicada",
    "githubUrl": "",
    "logo": "assets/Govlab.png",
    "videoUrl": "",
    "pptUrl": ""
  },
  {
    "segment": "Transversal",
    "tipo": "Educación",
    "linea": "Educación & Formación",
    "tags": [
      "Pregrado",
      "Ciencia de Datos",
      "Modelado Matemático",
      "Unisabana"
    ],
    "readyForSale": true,
    "name": "Pregrado en IA",
    "slogan": "Aprende IA desde la raíz",
    "description": "Programa de pregrado en Ciencia de Datos e Inteligencia Artificial de la Universidad de La Sabana. Formación integral en modelos, algoritmos y aplicaciones reales.",
    "status": "Activo",
    "demoMode": "mostrar",
    "appUrl": "https://www.unisabana.edu.co/programas/pregrados/ciencia-de-datos",
    "githubUrl": "",
    "logo": "assets/Govlab.png",
    "videoUrl": "",
    "pptUrl": ""
  },
  {
    "segment": "Transversal",
    "tipo": "Educación",
    "linea": "Educación & Formación",
    "tags": [
      "Bootcamps",
      "Educación Continua",
      "Formación Ejecutiva",
      "Práctica"
    ],
    "readyForSale": true,
    "name": "Bootcamps en IA",
    "slogan": "Habilidades reales, en tiempo récord",
    "description": "Programas técnicos intensivos de capacitación en IA para profesionales y directivos del sector público y privado, orientados a casos de uso inmediatos.",
    "status": "Activo",
    "demoMode": "mostrar",
    "appUrl": "https://www.unisabana.edu.co/programas/educacion-continua/curso/curso-experto-en-inteligencia-artificial-para-profesionales-innovadores",
    "githubUrl": "",
    "logo": "assets/Govlab.png",
    "videoUrl": "",
    "pptUrl": ""
  }
]\n\nwith open('products_data.json', 'w', encoding='utf-8') as f:\n    json.dump(products, f, ensure_ascii=False, indent=2)\n