import json
import csv
import io

# Define rich, multi-faceted tags and sector mapping for all 60 products
# Dimensions: [Sector/Industria, Tecnología, Tipo de Software / Solución, Dominio específico, (Listo para propuesta)]

PRODUCTS_DETAIL = [
  # ─── LÍNEA PITCHLAB (SOFTWARE) ───
  {
    "name": "PitchLab360",
    "segment": "Sector Público",
    "tipo": "Software",
    "linea": "Línea PitchLab",
    "tags": ["Gobierno", "Política", "IA Generativa", "Claude", "NLP", "Análisis de Discurso", "Listo para propuesta"],
    "readyForSale": True,
    "slogan": "Analiza el discurso, mejora el mensaje",
    "description": "Análisis de discurso político con Claude (Anthropic). Perfil comunicativo, análisis emocional, stakeholders, encuadres narrativos y potencial digital. Probado con candidatos presidenciales.",
    "status": "En línea",
    "demoMode": "mostrar",
    "appUrl": "https://pitchlab360-production.up.railway.app/",
    "githubUrl": "https://github.com/Juansotag/PitchLab360",
    "logo": "assets/projects/pitchlab360.jpg",
    "videoUrl": "https://drive.google.com/file/d/1bYLxn5TCm_Hwq6DG7-u7UYui5N5szYUm/view?usp=drive_link",
    "pptUrl": "",
    "technologies": "Claude 3.5 (Anthropic), Python, FastAPI, React",
    "solution_type": "Plataforma de Análisis Forense de Discurso y NLP",
    "economic_sectors": "Sector Público, Consultoría Política, Medios de Comunicación, Asuntos Públicos y Corporativos",
    "use_cases": "Evaluación de debates presidenciales, discursos oficiales, auditoría de encuadres y framing narrativo."
  },
  {
    "name": "Polycheck",
    "segment": "Sector Público",
    "tipo": "Software",
    "linea": "Línea PitchLab",
    "tags": ["Medios", "Gobierno", "Extensión Chrome", "GPT-4o", "Fact-checking", "Listo para propuesta"],
    "readyForSale": True,
    "slogan": "Verifica en tiempo real, no después",
    "description": "Extensión de Chrome para fact-checking en tiempo real sobre videos de YouTube y directos. Integración GPT-4o + Gemini + Google Search para análisis forense del discurso.",
    "status": "En línea",
    "demoMode": "mostrar",
    "appUrl": "",
    "githubUrl": "https://github.com/Juansotag/Polycheck",
    "logo": "assets/projects/polycheck.jpg",
    "videoUrl": "https://drive.google.com/file/d/111GwtqEWziIQFwi8BxMgQhiR6ZT-o2YW/view?usp=drive_link",
    "pptUrl": "",
    "technologies": "GPT-4o, Gemini API, Google Search API, Chrome Extension (Manifest V3), JavaScript",
    "solution_type": "Extensión de Navegador / Fact-Checking en Tiempo Real",
    "economic_sectors": "Medios de Comunicación, Periodismo, Sector Público, Campañas Electorales, Think Tanks",
    "use_cases": "Verificación instantánea de afirmaciones en transmisiones en vivo, discursos y debates en YouTube."
  },
  {
    "name": "PitchLab Med",
    "segment": "Sector Privado",
    "tipo": "Software",
    "linea": "Línea PitchLab",
    "tags": ["Salud", "Farma", "IA Conversacional", "Regulación", "INVIMA", "Listo para propuesta"],
    "readyForSale": True,
    "slogan": "Practica tu pitch médico con estándares INVIMA",
    "description": "Plataforma para la práctica y evaluación de pitch médicos con medidas de rigurosidad INVIMA. Entrenamiento conversacional para profesionales e industria farmacéutica.",
    "status": "En línea",
    "demoMode": "mostrar",
    "appUrl": "https://pitchlab-med.up.railway.app/",
    "githubUrl": "https://github.com/Juansotag/PitchLab360-comercial",
    "logo": "assets/projects/pitchlab360.jpg",
    "videoUrl": "",
    "pptUrl": "",
    "technologies": "LLMs (OpenAI/Anthropic), FastAPI, React, Speech-to-Text",
    "solution_type": "Simulador y Evaluador Conversacional de Cumplimiento Normativo",
    "economic_sectors": "Industria Farmacéutica, Salud, Dispositivos Médicos, Laboratorios Clínicos",
    "use_cases": "Entrenamiento de visitadores médicos y voceros en regulación sanitaria INVIMA y comunicación técnico-científica."
  },
  {
    "name": "PitchLab Entrenamiento",
    "segment": "Sector Privado",
    "tipo": "Software",
    "linea": "Línea PitchLab",
    "tags": ["Empresa", "Avatar en Vivo", "Voz en Tiempo Real", "LiveKit", "Negociación", "Listo para propuesta"],
    "readyForSale": True,
    "slogan": "Entrena tu discurso con un avatar interactivo",
    "description": "Avatar interactivo en tiempo real para entrenamiento en ventas y negociación corporativa. Análisis automático de fluidez, muletillas, persuasión y lenguaje no verbal.",
    "status": "En línea",
    "demoMode": "mostrar",
    "appUrl": "https://pitchlab-entrenamiento.up.railway.app/",
    "githubUrl": "https://github.com/Juansotag/PitchLab_LiveKit",
    "logo": "assets/projects/pitchlab360.jpg",
    "videoUrl": "",
    "pptUrl": "",
    "technologies": "LiveKit WebRTC, Avatares HeyGen/Tavus, Silero VAD, OpenAI Realtime",
    "solution_type": "Avatar Interactivo y Coach de Negociación por Voz en Vivo",
    "economic_sectors": "Sector Corporativo, Banca & Finanzas, Consultoría, Recursos Humanos & Capacitación",
    "use_cases": "Simulación inmersiva de objeciones de clientes, pitch de ventas B2B y entrevistas de alta exigencia."
  },

  # ─── LÍNEA GOVTEST & OPINIÓN ───
  {
    "name": "GovTest",
    "segment": "Sector Público",
    "tipo": "Software",
    "linea": "Línea GovTest & Opinión",
    "tags": ["Política", "Gobierno", "Web App", "Supabase", "Elecciones 2026", "Listo para propuesta"],
    "readyForSale": True,
    "slogan": "Descubre tu afinidad política con datos reales",
    "description": "Test de afinidad política para las elecciones colombianas de 2026. Comparación de posturas ciudadanas con programas de gobierno y declaraciones de candidatos.",
    "status": "En línea",
    "demoMode": "mostrar",
    "appUrl": "https://govtest-production.up.railway.app/",
    "githubUrl": "https://github.com/Juansotag/GovTest",
    "logo": "assets/projects/govtest.jpg",
    "videoUrl": "https://drive.google.com/file/d/1Xl2Nlq7l44o50H15gNlBqL4894xG960X/view?usp=drive_link",
    "pptUrl": "",
    "technologies": "React, Supabase, Algoritmos de Matching Político, Tailwind CSS",
    "solution_type": "Voting Advice Application (VAA) y Plataforma de Afinidad Política",
    "economic_sectors": "Sector Público, Consultoría Política, Medios de Comunicación, Organizaciones Cívicas",
    "use_cases": "Mapeo de preferencias ciudadanas, pedagogía electoral masiva y sondeos de opinión pública."
  },
  {
    "name": "Test 9 Ejes",
    "segment": "Sector Público",
    "tipo": "Software",
    "linea": "Línea GovTest & Opinión",
    "tags": ["Política", "Gobierno", "Supabase", "React", "Test Ideológico", "Listo para propuesta"],
    "readyForSale": True,
    "slogan": "Mapea tu pensamiento político en 9 dimensiones",
    "description": "Evaluación ideológica multidimensional basada en el modelo de 9 ejes políticos. Visualización interactiva del posicionamiento frente a diferentes corrientes de pensamiento.",
    "status": "En línea",
    "demoMode": "mostrar",
    "appUrl": "https://9-axes-test-production.up.railway.app/",
    "githubUrl": "https://github.com/Juansotag/9-Axes-Test",
    "logo": "assets/projects/test9ejes.jpg",
    "videoUrl": "https://drive.google.com/file/d/1gI264fE0jHk0H4T6d-K10nZ9F0h0y-G1/view?usp=drive_link",
    "pptUrl": "",
    "technologies": "React, Supabase, Chart.js, Modelado Psicométrico",
    "solution_type": "Test Psicométrico e Ideológico Multidimensional",
    "economic_sectors": "Educación Superior, Investigación Social, Medios, Consultoría Política",
    "use_cases": "Investigación académica sobre polarización, pedagogía y perfilamiento ideológico de audiencias."
  },
  {
    "name": "Test 9 Ejes Colombia",
    "segment": "Sector Público",
    "tipo": "Software",
    "linea": "Línea GovTest & Opinión",
    "tags": ["Política", "Gobierno", "Democracia", "React", "Supabase", "Listo para propuesta"],
    "readyForSale": True,
    "slogan": "El test de 9 ejes adaptado a la realidad colombiana",
    "description": "Versión contextualizada del test de 9 ejes para el escenario político colombiano. Preguntas sobre coyuntura nacional, paz, economía, medio ambiente y modelo de Estado.",
    "status": "En línea",
    "demoMode": "mostrar",
    "appUrl": "https://9-ejes-colombia-production.up.railway.app/",
    "githubUrl": "https://github.com/Juansotag/9-Ejes-Colombia",
    "logo": "assets/projects/test9ejes.jpg",
    "videoUrl": "https://drive.google.com/file/d/144V973Zp4z7F1wM69V-qR4yQ2vM2y2g3/view?usp=drive_link",
    "pptUrl": "",
    "technologies": "React, Supabase, Glassmorphism UI, Métricas Estadísticas",
    "solution_type": "Evaluador Político Contextualizado para Colombia",
    "economic_sectors": "Sector Público, Medios de Comunicación, Educación Cívica, Consultoría",
    "use_cases": "Análisis de opinión pública nacional frente a reformas y coyuntura política colombiana."
  },

  # ─── LÍNEA ASISTENTES DE VOZ ───
  {
    "name": "AlcaldesaIA",
    "segment": "Sector Público",
    "tipo": "Software",
    "linea": "Asistentes de Voz",
    "tags": ["Gobierno", "Ciudad", "Asistente de Voz", "LiveKit", "OpenAI Realtime"],
    "readyForSale": False,
    "slogan": "Habla con la alcaldía, en tiempo real",
    "description": "Asistente de voz conversacional para la Alcaldía de Cajicá. Permite a los ciudadanos consultar trámites, servicios y estado de solicitudes hablando directamente por voz.",
    "status": "En línea",
    "demoMode": "mostrar",
    "appUrl": "https://alcaldesa-ia-production.up.railway.app/",
    "githubUrl": "https://github.com/Juansotag/AlcaldesaIA",
    "logo": "assets/projects/alcaldesa.png",
    "videoUrl": "https://drive.google.com/file/d/1Xl2Nlq7l44o50H15gNlBqL4894xG960X/view?usp=drive_link",
    "pptUrl": "",
    "technologies": "LiveKit WebRTC, OpenAI Realtime API, Silero VAD, Python FastAPI",
    "solution_type": "Agente de Voz Bidireccional en Tiempo Real",
    "economic_sectors": "Gobiernos Locales, Alcaldías, Sector Público Municipal, Atención Ciudadana",
    "use_cases": "Atención 24/7 de consultas de trámites, directorio municipal y orientación ciudadana por voz."
  },
  {
    "name": "Gober Santander",
    "segment": "Sector Público",
    "tipo": "Software",
    "linea": "Asistentes de Voz",
    "tags": ["Gobierno", "Región", "Asistente de Voz", "LiveKit", "PQRS", "Listo para propuesta"],
    "readyForSale": True,
    "slogan": "Atención ciudadana inteligente para Santander",
    "description": "Agente de voz para la Gobernación de Santander. Recepción y radicación de PQRS, orientación sobre oferta institucional y seguimiento de trámites departamentales.",
    "status": "En línea",
    "demoMode": "mostrar",
    "appUrl": "https://gober-santander-production.up.railway.app/",
    "githubUrl": "https://github.com/Juansotag/Gober-Santander",
    "logo": "assets/projects/gober.png",
    "videoUrl": "https://drive.google.com/file/d/1n23w0-wXo7R-M7oE3r2z4k4v5X3t5Y5Z/view?usp=drive_link",
    "pptUrl": "",
    "technologies": "LiveKit, OpenAI Realtime, FastAPI, PostgreSQL / Supabase",
    "solution_type": "Sistema de Radicación y PQRS por Voz en Tiempo Real",
    "economic_sectors": "Gobiernos Departamentales, Gobernaciones, Sector Público, Servicio al Ciudadano",
    "use_cases": "Recepción y clasificación automática de peticiones, quejas y reclamos departamentales por canal de voz."
  },
  {
    "name": "Govi",
    "segment": "Sector Público",
    "tipo": "Software",
    "linea": "Asistentes de Voz",
    "tags": ["Gobierno", "Tecnología", "Asistente de Voz", "LiveKit", "Chatbot"],
    "readyForSale": False,
    "slogan": "El asistente inteligente del GovLab",
    "description": "Asistente virtual conversacional del GovLab. Guía a visitantes por el portafolio de proyectos, líneas de investigación, capacidades técnicas y opciones de colaboración.",
    "status": "En línea",
    "demoMode": "mostrar",
    "appUrl": "https://govi-production.up.railway.app/",
    "githubUrl": "https://github.com/Juansotag/Govi",
    "logo": "assets/Govlab.png",
    "videoUrl": "",
    "pptUrl": "",
    "technologies": "LiveKit WebRTC, FastAPI, OpenAI GPT-4o-mini, Vector Store",
    "solution_type": "Asistente Institucional Inteligente Multimodal",
    "economic_sectors": "Educación Superior, Laboratorios de Innovación, Centros de I+D",
    "use_cases": "Demostración de capacidades tecnológicas, navegación interactiva del portafolio y captura de leads."
  },
  {
    "name": "ConvergenceLab",
    "segment": "Sector Privado",
    "tipo": "Software",
    "linea": "Asistentes de Voz",
    "tags": ["Tecnología", "Telecomunicaciones", "Next.js", "LiveKit", "Silero VAD", "Listo para propuesta"],
    "readyForSale": True,
    "slogan": "La frontera de la interacción por voz con IA",
    "description": "Plataforma de experimentación e investigación en tecnologías de voz en tiempo real. Integración de modelos de latencia ultrabaja, síntesis vocal adaptativa y análisis emocional.",
    "status": "En línea",
    "demoMode": "mostrar",
    "appUrl": "https://convergencelab-production.up.railway.app/",
    "githubUrl": "https://github.com/Juansotag/ConvergenceLab",
    "logo": "assets/projects/convergence.png",
    "videoUrl": "",
    "pptUrl": "",
    "technologies": "Next.js 14, LiveKit Cloud, Silero VAD, WebRTC, WebSocket",
    "solution_type": "Laboratorio de Infraestructura y Experimentación en Voz",
    "economic_sectors": "Telecomunicaciones, Tecnología & Software, BPO & Contact Centers",
    "use_cases": "Benchmark de latencia, pruebas de speech-to-speech y desarrollo de agentes de contact center autónomos."
  },
  {
    "name": "Alocandidato",
    "segment": "Sector Público",
    "tipo": "Software",
    "linea": "Asistentes de Voz",
    "tags": ["Política", "Gobierno", "Llamadas Automatizadas", "Dapta", "Outbound Calls", "Listo para propuesta"],
    "readyForSale": True,
    "slogan": "Campañas de voz automatizadas a escala",
    "description": "Sistema de llamadas automatizadas bidireccionales con IA para campañas electorales e investigación de opinión pública. Encuestas dinámicas y mensajes personalizados masivos.",
    "status": "En línea",
    "demoMode": "mostrar",
    "appUrl": "https://alocandidato-production.up.railway.app/",
    "githubUrl": "https://github.com/Juansotag/Alocandidato",
    "logo": "assets/projects/alocandidato.jpg",
    "videoUrl": "",
    "pptUrl": "",
    "technologies": "Telephony API (Twilio/Dapta), OpenAI Voice, Python, FastAPI",
    "solution_type": "Sistema Masivo de Llamadas Salientes Automatizadas (Outbound AI)",
    "economic_sectors": "Campañas Políticas, Consultoría Electoral, Empresas de Encuestas & Investigación de Mercados",
    "use_cases": "Sondeos telefónicos interactivos masivos, movilización de votantes y recordatorios de eventos cívicos."
  },

  # ─── LÍNEA AGROINDUSTRIA & EXPORTACIÓN ───
  {
    "name": "HassApp",
    "segment": "Sector Privado",
    "tipo": "Software",
    "linea": "Agroindustria & Exportación",
    "tags": ["Agro", "Exportación", "Trazabilidad", "FastAPI", "React", "Corpohass", "Listo para propuesta"],
    "readyForSale": True,
    "slogan": "Trazabilidad inteligente para el aguacate Hass",
    "description": "Plataforma para Corpohass que gestiona la trazabilidad completa del aguacate Hass colombiano desde el predio productor hasta el puerto de destino. Monitoreo de calidad y certificaciones.",
    "status": "En línea",
    "demoMode": "mostrar",
    "appUrl": "https://hassapp-production.up.railway.app/",
    "githubUrl": "https://github.com/Juansotag/HassApp",
    "logo": "assets/projects/hassapp.png",
    "videoUrl": "https://drive.google.com/file/d/1Xl2Nlq7l44o50H15gNlBqL4894xG960X/view?usp=drive_link",
    "pptUrl": "",
    "technologies": "React, FastAPI, PostgreSQL, Códigos QR / Trazabilidad Blockchain ready",
    "solution_type": "Software de Trazabilidad y Cadena de Custodia Agroexportadora",
    "economic_sectors": "Agroindustria, Comercio Exterior, Exportadores de Frutas Frescas, Gremios Agropecuarios",
    "use_cases": "Control de lotes, certificación de origen fitosanitario y auditoría de cadena de frío hasta puertos de destino."
  },
  {
    "name": "ExportaCheck",
    "segment": "Sector Privado",
    "tipo": "Software",
    "linea": "Agroindustria & Exportación",
    "tags": ["Agro", "Exportación", "Diagnóstico IA", "FastAPI", "Corpohass", "Listo para propuesta"],
    "readyForSale": True,
    "slogan": "Diagnóstico de madurez exportadora con IA",
    "description": "Herramienta de autodiagnóstico para productores y exportadores agrícolas. Evalúa cumplimiento fitosanitario, normativo y logístico para mercados de EE.UU., Europa y Asia.",
    "status": "En línea",
    "demoMode": "mostrar",
    "appUrl": "https://exportacheck-production.up.railway.app/",
    "githubUrl": "https://github.com/Juansotag/ExportaCheck",
    "logo": "assets/projects/exportacheck.jpg",
    "videoUrl": "",
    "pptUrl": "",
    "technologies": "FastAPI, React, Motor de Reglas Arancelarias y Fitosanitarias, OpenAI",
    "solution_type": "Motor de Diagnóstico y Madurez Exportadora",
    "economic_sectors": "Agroindustria, Cámaras de Comercio, ProColombia / Promoción Comercial, Pymes Agropecuarias",
    "use_cases": "Evaluación automatizada de brechas técnicas y regulatorias antes de iniciar exportaciones a mercados internacionales."
  },

  # ─── LÍNEA NOTARÍAS & DOCUMENTAL ───
  {
    "name": "NotariaDoc",
    "segment": "Sector Privado",
    "tipo": "Software",
    "linea": "Notarías & Documental",
    "tags": ["Notarías", "Justicia", "Chat IA", "Escrituración", "Cumplimiento", "Listo para propuesta"],
    "readyForSale": True,
    "slogan": "Borradores de escrituras con IA en minutos",
    "description": "Asistente para despachos notariales que redacta borradores de escrituras públicas a partir de minutas, contratos y documentos soporte. Validación automática de requisitos legales.",
    "status": "En línea",
    "demoMode": "mostrar",
    "appUrl": "https://notariadoc-production.up.railway.app/",
    "githubUrl": "https://github.com/Juansotag/NotariaDoc",
    "logo": "assets/Govlab.png",
    "videoUrl": "https://drive.google.com/file/d/1Xl2Nlq7l44o50H15gNlBqL4894xG960X/view?usp=drive_link",
    "pptUrl": "",
    "technologies": "Python, OpenAI GPT-4, Parser DOCX/PDF, Interfaz Notarial Segura",
    "solution_type": "Generador Inteligente de Minutas y Escrituras Notariales",
    "economic_sectors": "Sector Notarial, Despachos Jurídicos, Fiduciarias, Sector Inmobiliario",
    "use_cases": "Generación acelerada de escrituras de compraventa, hipotecas, cancelaciones y validación de comparecientes."
  },
  {
    "name": "NotariaIQ",
    "segment": "Sector Privado",
    "tipo": "Software",
    "linea": "Notarías & Documental",
    "tags": ["Notarías", "Empresa", "Panel de Control", "Pronóstico", "Tiempos de Espera", "Listo para propuesta"],
    "readyForSale": True,
    "slogan": "Control operativo y predicción de demanda notarial",
    "description": "Panel de control y analítica para notarías. Predicción de tiempos de espera, gestión de turnos, distribución de carga laboral entre funcionarios y métricas de satisfacción.",
    "status": "En línea",
    "demoMode": "mostrar",
    "appUrl": "https://notariaiq-production.up.railway.app/",
    "githubUrl": "https://github.com/Juansotag/NotariaIQ",
    "logo": "assets/Govlab.png",
    "videoUrl": "",
    "pptUrl": "",
    "technologies": "FastAPI, PostgreSQL, Chart.js, Algoritmos de Teoría de Colas",
    "solution_type": "Dashboard Operativo y Pronóstico de Capacidad Notarial",
    "economic_sectors": "Sector Notarial, Curadurías Urbanas, Entidades de Trámites Públicos",
    "use_cases": "Reducción de tiempos de fila en notarías, balanceo de carga de trabajo y analítica de recaudación."
  },
  {
    "name": "Radica Notaría",
    "segment": "Sector Privado",
    "tipo": "Software",
    "linea": "Notarías & Documental",
    "tags": ["Notarías", "Vivienda", "Constructoras", "Flujo Digital", "Cero Papel", "Listo para propuesta"],
    "readyForSale": True,
    "slogan": "Ventanilla digital entre constructoras y notarías",
    "description": "Plataforma de radicación digital que conecta constructoras, fiduciarias y notarías. Gestión de paquetes documentales para escrituración masiva de proyectos inmobiliarios.",
    "status": "En línea",
    "demoMode": "mostrar",
    "appUrl": "https://radicanotaria-production.up.railway.app/",
    "githubUrl": "https://github.com/Juansotag/RadicaNotaria",
    "logo": "assets/Govlab.png",
    "videoUrl": "",
    "pptUrl": "",
    "technologies": "React, Node.js / FastAPI, AWS S3, Firma y Validación Documental",
    "solution_type": "Ventanilla Única Digital B2B Constructora-Notaría",
    "economic_sectors": "Construcción, Desarrolladores Inmobiliarios, Notariado, Fiduciarias",
    "use_cases": "Radicación masiva de escrituración para macroproyectos de vivienda y urbanismo sin papeles físicos."
  },

  # ─── LÍNEA PROYECCIÓN SOCIAL & DIRECTIVA ───
  {
    "name": "Resume Expedientes",
    "segment": "Sector Público",
    "tipo": "Software",
    "linea": "Proyección Social & Directiva",
    "tags": ["Justicia", "Gobierno", "Gestión Documental", "Síntesis Ejecutiva", "NLP", "Listo para propuesta"],
    "readyForSale": True,
    "slogan": "Síntesis ejecutiva de expedientes complejos con IA",
    "description": "Herramienta para directivos y equipos jurídicos que genera resúmenes estructurados de expedientes administrativos y judiciales de cientos de páginas en segundos.",
    "status": "En línea",
    "demoMode": "mostrar",
    "appUrl": "https://resume-expedientes-production.up.railway.app/",
    "githubUrl": "https://github.com/Juansotag/Resume-Expedientes",
    "logo": "assets/Govlab.png",
    "videoUrl": "https://drive.google.com/file/d/1Xl2Nlq7l44o50H15gNlBqL4894xG960X/view?usp=drive_link",
    "pptUrl": "",
    "technologies": "LangChain, Claude 3.5 Sonnet / OpenAI, OCR Tesseract, PyPDF2",
    "solution_type": "Motor de Comprensión y Resumen Estructurado de Expedientes Legales",
    "economic_sectors": "Rama Judicial, Altas Cortes, Ministerios, Secretarías Jurídicas, Bufetes de Abogados",
    "use_cases": "Lectura y síntesis rápida de expedientes de contratación, fallos disciplinarios y procesos judiciales voluminosos."
  },
  {
    "name": "NewsletterMaker",
    "segment": "Sector Privado",
    "tipo": "Software",
    "linea": "Proyección Social & Directiva",
    "tags": ["Medios", "Comunicación", "CRON", "WhatsApp", "Email", "Listo para propuesta"],
    "readyForSale": True,
    "slogan": "Boletines institucionales automáticos con IA",
    "description": "Generador automatizado de newsletters temáticos a partir de fuentes de noticias, publicaciones académicas y comunicados oficiales. Distribución por correo y WhatsApp.",
    "status": "En línea",
    "demoMode": "mostrar",
    "appUrl": "https://newslettermaker-production.up.railway.app/",
    "githubUrl": "https://github.com/Juansotag/NewsletterMaker",
    "logo": "assets/Govlab.png",
    "videoUrl": "",
    "pptUrl": "",
    "technologies": "Python CRON, BeautifulSoup, LLM Curation, Twilio WhatsApp API, SendGrid",
    "solution_type": "Generador y Distribuidor Automatizado de Boletines Inteligentes",
    "economic_sectors": "Medios de Comunicación, Direcciones de Comunicaciones Institucionales, Gremios, Universidades",
    "use_cases": "Monitoreo de prensa matutino automatizado y síntesis de noticias clave enviada a directivos y clientes."
  },

  # ─── LÍNEA GESTIÓN PÚBLICA & AMBIENTAL ───
  {
    "name": "CAResponde",
    "segment": "Sector Público",
    "tipo": "Software",
    "linea": "Gestión Pública & Ambiental",
    "tags": ["Medio Ambiente", "Gobierno", "CAR", "PQRS Automático", "Clasificación IA", "Listo para propuesta"],
    "readyForSale": True,
    "slogan": "Atención inteligente a solicitudes ambientales",
    "description": "Sistema de clasificación y respuesta automática de solicitudes ciudadanas y denuncias ambientales para la Corporación Autónoma Regional de Cundinamarca (CAR).",
    "status": "En línea",
    "demoMode": "mostrar",
    "appUrl": "https://caresponde-production.up.railway.app/",
    "githubUrl": "https://github.com/Juansotag/CAResponde",
    "logo": "assets/projects/caresponde.png",
    "videoUrl": "https://drive.google.com/file/d/1Xl2Nlq7l44o50H15gNlBqL4894xG960X/view?usp=drive_link",
    "pptUrl": "",
    "technologies": "FastAPI, NLP Multiclase, OpenAI, Base de Conocimiento CAR",
    "solution_type": "Clasificador y Redactor de Respuestas a PQRS Ambientales",
    "economic_sectors": "Autoridades Ambientales (CARs), Ministerio de Ambiente, Secretarías de Ambiente",
    "use_cases": "Enrutamiento automático de denuncias de tala, fuentes hídricas, ruido y afectación de fauna/flora silvestre."
  },
  {
    "name": "AlcaldIA",
    "segment": "Sector Público",
    "tipo": "Software",
    "linea": "Gestión Pública & Ambiental",
    "tags": ["Gobierno", "Ciudad", "Plan de Desarrollo", "RAG FAISS", "GPT-4o", "Listo para propuesta"],
    "readyForSale": True,
    "slogan": "Conocimiento del plan de desarrollo al alcance de todos",
    "description": "Chatbot basado en RAG sobre los documentos del Plan de Desarrollo Distrital de Bogotá. Responde preguntas de ciudadanos y funcionarios con citación exacta de metas y presupuestos.",
    "status": "En línea",
    "demoMode": "mostrar",
    "appUrl": "https://alcaldia-production.up.railway.app/",
    "githubUrl": "https://github.com/Juansotag/AlcaldIA",
    "logo": "assets/photos/Aliados/alcaldia.png",
    "videoUrl": "",
    "pptUrl": "",
    "technologies": "RAG (Retrieval-Augmented Generation), FAISS Vector Store, GPT-4o, Streamlit / FastAPI",
    "solution_type": "Agente RAG Especializado en Planes de Desarrollo y Políticas Públicas",
    "economic_sectors": "Alcaldías Distritales y Municipales, Concejos Municipales, Secretarías de Planeación",
    "use_cases": "Consulta instantánea de metas de inversión, trazadores presupuestales y proyectos del Plan Distrital."
  },
  {
    "name": "PoliciApp-Eco",
    "segment": "Sector Público",
    "tipo": "Software",
    "linea": "Gestión Pública & Ambiental",
    "tags": ["Seguridad", "Medio Ambiente", "Policía", "Legislación Ambiental", "Carabineros"],
    "readyForSale": False,
    "slogan": "Asistente normativo para la policía ambiental en campo",
    "description": "Aplicación móvil de consulta rápida para agentes de la Dirección de Carabineros y Protección Ambiental. Tipificación de delitos ecológicos, rutas de atención e incautación de fauna/flora.",
    "status": "En línea",
    "demoMode": "mostrar",
    "appUrl": "https://policiapp-eco-production.up.railway.app/",
    "githubUrl": "https://github.com/Juansotag/PoliciApp-Eco",
    "logo": "assets/photos/Aliados/policia.png",
    "videoUrl": "",
    "pptUrl": "",
    "technologies": "PWA / React Native, SQLite Offline-first, NLP Legal",
    "solution_type": "App de Asistencia Normativa en Campo para Uniformados",
    "economic_sectors": "Policía Nacional, Dirección de Carabineros, MinAmbiente, Parques Nacionales",
    "use_cases": "Guía paso a paso para actas de incautación, flagrancia en minería ilegal y tráfico de especies."
  },
  {
    "name": "PoliciaAmbiental",
    "segment": "Sector Público",
    "tipo": "Software",
    "linea": "Gestión Pública & Ambiental",
    "tags": ["Seguridad", "Medio Ambiente", "Normativa", "Jurisprudencia", "Chatbot"],
    "readyForSale": False,
    "slogan": "Base de conocimiento legal para protección ambiental",
    "description": "Chatbot especializado en normativa ambiental colombiana (Leyes, Decretos, Resoluciones MinAmbiente). Orientación en procedimientos sancionatorios y medidas preventivas.",
    "status": "En línea",
    "demoMode": "mostrar",
    "appUrl": "https://policia-ambiental-production.up.railway.app/",
    "githubUrl": "https://github.com/Juansotag/PoliciaAmbiental",
    "logo": "assets/photos/Aliados/policia.png",
    "videoUrl": "",
    "pptUrl": "",
    "technologies": "FastAPI, LangChain, Embeddings Legales OpenAI, ChromaDB",
    "solution_type": "Base de Conocimiento Jurisprudencial Ambiental",
    "economic_sectors": "Policía Nacional, Fiscalías Especializadas en Delitos Ambientales, Consultores Ambientales",
    "use_cases": "Sustentación jurídica de comparendos ambientales y medidas cautelares en operativos de control."
  },
  {
    "name": "LegisCheck",
    "segment": "Sector Público",
    "tipo": "Software",
    "linea": "Gestión Pública & Ambiental",
    "tags": ["Gobierno", "Justicia", "Legislativo", "Diff Semántico", "GPT-4"],
    "readyForSale": False,
    "slogan": "Comparación y análisis semántico de proyectos de ley",
    "description": "Herramienta que analiza diferencias entre ponencias y versiones de proyectos de ley en el Congreso. Detecta cambios de fondo, impactos regulatorios y posibles contradicciones.",
    "status": "En línea",
    "demoMode": "mostrar",
    "appUrl": "https://legischeck-production.up.railway.app/",
    "githubUrl": "https://github.com/Juansotag/LegisCheck",
    "logo": "assets/projects/Legischeck.png",
    "videoUrl": "",
    "pptUrl": "",
    "technologies": "Python, Diff Semántico, GPT-4, Parser XML/PDF del Congreso",
    "solution_type": "Analizador Comparativo de Textos Legislativos y Ponencias",
    "economic_sectors": "Congreso de la República, Unidades de Trabajo Legislativo (UTL), Gremios Económicos, Asuntos Públicos",
    "use_cases": "Auditoría de micos legislativos, diferencias entre primero y segundo debate de proyectos de ley."
  },

  # ─── LÍNEA SEGURIDAD & ANALÍTICA ───
  {
    "name": "Barranquilla",
    "segment": "Sector Público",
    "tipo": "Software",
    "linea": "Seguridad & Analítica",
    "tags": ["Seguridad", "Gobierno", "Ciudad", "Observatorio", "Predicción Delitos", "Listo para propuesta"],
    "readyForSale": True,
    "slogan": "Analítica predictiva para la seguridad de Barranquilla",
    "description": "Observatorio de seguridad ciudadana con modelos predictivos de delito a nivel de cuadrante y barrio. Permite a la alcaldía y policía focalizar operativos de prevención.",
    "status": "En línea",
    "demoMode": "mostrar",
    "appUrl": "https://barranquilla-production.up.railway.app/",
    "githubUrl": "https://github.com/Juansotag/Barranquilla",
    "logo": "assets/Govlab.png",
    "videoUrl": "https://drive.google.com/file/d/1Xl2Nlq7l44o50H15gNlBqL4894xG960X/view?usp=drive_link",
    "pptUrl": "",
    "technologies": "Python, GeoPandas, Random Forest / XGBoost, Dash / Streamlit",
    "solution_type": "Observatorio Predictivo de Seguridad Ciudadana y Hotspots",
    "economic_sectors": "Alcaldías Distritales, Secretarías de Seguridad, Policía Metropolitana",
    "use_cases": "Planificación táctica del patrullaje policial y prevención focalizada de homicidios y hurtos."
  },

  # ─── LÍNEA SOSTENIBILIDAD & ESG ───
  {
    "name": "Test de sostenibilidad universitaria",
    "segment": "Sector Privado",
    "tipo": "Software",
    "linea": "Sostenibilidad & ESG",
    "tags": ["Educación", "Sostenibilidad", "ESG", "Universia", "React", "Supabase", "Listo para propuesta"],
    "readyForSale": True,
    "slogan": "Mide el compromiso ESG de tu universidad",
    "description": "Herramienta de autoevaluación y benchmarking de sostenibilidad para instituciones de educación superior. Métricas en gobernanza, impacto ambiental, inclusión y campus sostenible.",
    "status": "En línea",
    "demoMode": "mostrar",
    "appUrl": "https://test-sostenibilidad-production.up.railway.app/",
    "githubUrl": "https://github.com/Juansotag/Test-Sostenibilidad",
    "logo": "assets/projects/sostenibilidad.jpg",
    "videoUrl": "",
    "pptUrl": "",
    "technologies": "React, Supabase, Chart.js, Framework de Indicadores ESG Universia",
    "solution_type": "Plataforma de Diagnóstico y Benchmarking ESG",
    "economic_sectors": "Educación Superior, Redes Universitarias (Universia/MetaRed), Sector Corporativo ESG",
    "use_cases": "Medición de huella de carbono, políticas de inclusión y reporte de sostenibilidad universitaria."
  },
  {
    "name": "Asistente de agente para MetaRed",
    "segment": "Sector Privado",
    "tipo": "Software",
    "linea": "Sostenibilidad & ESG",
    "tags": ["Educación", "Tecnología", "MetaRed", "Universia", "Data Science", "Listo para propuesta"],
    "readyForSale": True,
    "slogan": "Analítica y recomendaciones para redes universitarias",
    "description": "Agente analítico desarrollado para la red MetaRed (Universia). Procesa encuestas de madurez digital universitaria y genera hojas de ruta de transformación tecnológica personalizadas.",
    "status": "En línea",
    "demoMode": "mostrar",
    "appUrl": "https://metared-production.up.railway.app/",
    "githubUrl": "https://github.com/Juansotag/MetaRed-Assistant",
    "logo": "assets/projects/sostenibilidad.jpg",
    "videoUrl": "",
    "pptUrl": "",
    "technologies": "Python, scikit-learn, OpenAI API, Streamlit / FastAPI",
    "solution_type": "Agente Asesor y Motor de Recomendación de Transformación Digital",
    "economic_sectors": "Educación Superior en Iberoamérica, Universia, MetaRed ESG y TIC",
    "use_cases": "Generación de hojas de ruta de transformación digital personalizadas para universidades de 8 países."
  },

  # ─── LÍNEA COMUNIDAD & ADMISIONES ───
  {
    "name": "MPAChat",
    "segment": "Sector Público",
    "tipo": "Software",
    "linea": "Comunidad & Admisiones",
    "tags": ["Educación", "Gobierno", "Posgrados", "CV Matching", "NLP", "Listo para propuesta"],
    "readyForSale": True,
    "slogan": "Orientación personalizada para aspirantes a posgrado",
    "description": "Chatbot con matching de perfil profesional para aspirantes a la Maestría en Políticas Públicas (MPA) de La Sabana. Analiza CV del aspirante y recomienda énfasis formativo.",
    "status": "En línea",
    "demoMode": "mostrar",
    "appUrl": "https://mpachat-production.up.railway.app/",
    "githubUrl": "https://github.com/Juansotag/MPAChat",
    "logo": "assets/photos/Aliados/escuela.png",
    "videoUrl": "",
    "pptUrl": "",
    "technologies": "Python, FastAPI, OpenAI Embeddings, Extracción de CV en PDF",
    "solution_type": "Asistente de Admisiones y Matching Vocacional con IA",
    "economic_sectors": "Educación Superior, Escuelas de Gobierno y Negocios, Direcciones de Admisiones",
    "use_cases": "Evaluación del perfil de aspirantes a posgrados y recomendación personalizada de plan de estudios."
  },
  {
    "name": "AlumniCV",
    "segment": "Sector Privado",
    "tipo": "Software",
    "linea": "Comunidad & Admisiones",
    "tags": ["Educación", "Empleo", "Talento", "Hojas de Vida", "ATS Scoring", "Listo para propuesta"],
    "readyForSale": True,
    "slogan": "Optimiza tu hoja de vida con retroalimentación IA",
    "description": "Plataforma para egresados de La Sabana que analiza hojas de vida frente a vacantes deseadas. Sugiere mejoras de redacción, palabras clave ATS y habilidades a fortalecer.",
    "status": "En línea",
    "demoMode": "mostrar",
    "appUrl": "https://alumnicv-production.up.railway.app/",
    "githubUrl": "https://github.com/Juansotag/AlumniCV",
    "logo": "assets/Govlab.png",
    "videoUrl": "",
    "pptUrl": "",
    "technologies": "FastAPI, PyPDF2, OpenAI GPT-4o, Motor de Evaluación de Competencias",
    "solution_type": "Optimizador de CV y Coach de Empleabilidad",
    "economic_sectors": "Educación Superior (Oficinas de Graduados), Firmas de Headhunting, Portales de Empleo",
    "use_cases": "Incremento del ratio de empleabilidad de egresados mediante adaptación de CV a filtros ATS corporativos."
  },
  {
    "name": "AlumniChat",
    "segment": "Sector Privado",
    "tipo": "Software",
    "linea": "Comunidad & Admisiones",
    "tags": ["Educación", "Comunidad", "Alumni", "Posgrados", "Chatbot", "Listo para propuesta"],
    "readyForSale": True,
    "slogan": "Conecta con la oferta de posgrados y vida profesional",
    "description": "Canal conversacional 24/7 para la comunidad de egresados. Información sobre educación continuada, beneficios para graduados, networking y eventos institucionales.",
    "status": "En línea",
    "demoMode": "mostrar",
    "appUrl": "https://alumnichat-production.up.railway.app/",
    "githubUrl": "https://github.com/Juansotag/AlumniChat",
    "logo": "assets/Govlab.png",
    "videoUrl": "",
    "pptUrl": "",
    "technologies": "FastAPI, OpenAI GPT-4o-mini, Supabase CRM integration",
    "solution_type": "Canal Conversacional Omnicanal de Fidelización de Egresados",
    "economic_sectors": "Educación Superior, Asociaciones de Antiguos Alumnos, Educación Continua",
    "use_cases": "Atención de consultas sobre certificados, convenios de descuento y re-enganche a programas de posgrado."
  },

  # ─── LÍNEA INNOVACIÓN & PROCESOS ───
  {
    "name": "Germina",
    "segment": "Sector Privado",
    "tipo": "Software",
    "linea": "Innovación & Procesos",
    "tags": ["Educación", "Emprendimiento", "Innovación", "Business Model", "Listo para propuesta"],
    "readyForSale": True,
    "slogan": "De la idea de investigación al modelo de negocio",
    "description": "Asistente para la Dirección de Innovación de Unisabana. Acompaña a investigadores y emprendedores en la estructuración de proyectos, validación de mercado y propiedad intelectual.",
    "status": "En línea",
    "demoMode": "mostrar",
    "appUrl": "https://germina-production.up.railway.app/",
    "githubUrl": "https://github.com/Juansotag/Germina",
    "logo": "assets/projects/germina.png",
    "videoUrl": "",
    "pptUrl": "",
    "technologies": "React, FastAPI, LLM Reasoning, Canvas Generator",
    "solution_type": "Copiloto de Transferencia Tecnológica y Emprendimiento",
    "economic_sectors": "Direcciones de Innovación Universitaria, Incubadoras, Aceleradoras de Startups",
    "use_cases": "Evaluación de madurez tecnológica (TRL), estructuración de patentes y modelos Canvas de spin-offs."
  },

  # ─── LÍNEA INTELIGENCIA GEOESPACIAL ───
  {
    "name": "Geovivienda",
    "segment": "Sector Privado",
    "tipo": "Software",
    "linea": "Inteligencia Geoespacial",
    "tags": ["Vivienda", "Ciudad", "Inmobiliario", "Leaflet", "Geoespacial", "Listo para propuesta"],
    "readyForSale": True,
    "slogan": "Inteligencia inmobiliaria y territorial en un mapa",
    "description": "Plataforma geoespacial que cruza oferta inmobiliaria, precios por metro cuadrado, estratificación y accesibilidad a servicios en Sabana Centro y Bogotá.",
    "status": "En línea",
    "demoMode": "mostrar",
    "appUrl": "https://geovivienda-production.up.railway.app/",
    "githubUrl": "https://github.com/Juansotag/Geovivienda",
    "logo": "assets/projects/geovivienda-main.png",
    "videoUrl": "",
    "pptUrl": "",
    "technologies": "Leaflet.js, OpenStreetMap, GeoPandas, FastAPI, PostgreSQL / PostGIS",
    "solution_type": "Plataforma de Inteligencia Territorial e Inmobiliaria (PropTech)",
    "economic_sectors": "Sector Inmobiliario, PropTech, Constructoras, Entidades de Planeación Urbana",
    "use_cases": "Estudios de mercado para nuevos desarrollos residenciales, análisis de plusvalía y accesibilidad."
  },

  # ─── LÍNEA ANALÍTICA CON IA ───
  {
    "name": "Data Copilot",
    "segment": "Transversal",
    "tipo": "Software",
    "linea": "Analítica con IA",
    "tags": ["Tecnología", "Analítica", "Empresa", "LangChain", "Plotly", "Auto-Charts", "Listo para propuesta"],
    "readyForSale": True,
    "slogan": "Pregúntale a tus datos en lenguaje natural",
    "description": "Copiloto analítico que traduce preguntas en español a consultas SQL/Python, genera visualizaciones interactivas automáticas y produce narrativas ejecutivas de hallazgos.",
    "status": "En línea",
    "demoMode": "mostrar",
    "appUrl": "https://data-copilot-production.up.railway.app/",
    "githubUrl": "https://github.com/Juansotag/DataCopilot",
    "logo": "assets/Govlab.png",
    "videoUrl": "",
    "pptUrl": "",
    "technologies": "LangChain, OpenAI GPT-4o, Plotly, Pandas, Text-to-SQL, Whisper",
    "solution_type": "Copiloto de Business Intelligence y Auto-Visualización en Lenguaje Natural",
    "economic_sectors": "Transversal Corporativo, Sector Financiero, Gobierno, Retail & Consumo Masivo",
    "use_cases": "Democratización del acceso a datos para ejecutivos no técnicos mediante consultas conversacionales."
  },

  # ─── LÍNEA DASHBOARDS & ANALÍTICA ───
  {
    "name": "Cuidar la Democracia",
    "segment": "Sector Público",
    "tipo": "Software",
    "linea": "Dashboards & Analítica",
    "tags": ["Democracia", "Gobierno", "Opinión", "INVAMER", "Dashboard", "Listo para propuesta"],
    "readyForSale": True,
    "slogan": "Visualiza lo que piensa el ciudadano",
    "description": "Dashboard interactivo con datos de encuesta sobre percepciones democráticas en Colombia (INVAMER/GovLab). Filtros sociodemográficos, mapas y gráficos en tiempo real.",
    "status": "En línea",
    "demoMode": "mostrar",
    "appUrl": "https://cuidar-la-democracia-production.up.railway.app/",
    "githubUrl": "https://github.com/Juansotag/Cuidar-la-Democracia",
    "logo": "assets/projects/democracia.png",
    "videoUrl": "https://drive.google.com/file/d/1cGZzC2g1HsFeL4M3TziwMUL9o692WI-x/view?usp=drive_link",
    "pptUrl": "",
    "technologies": "React, Chart.js, Leaflet, Micro-servicios de Datos INVAMER",
    "solution_type": "Dashboard Interactivo de Datos de Opinión y Cultura Ciudadana",
    "economic_sectors": "Sector Público, Think Tanks, Organizaciones Internacionales, Medios de Prensa",
    "use_cases": "Exploración multidimensional de confianza institucional, satisfacción ciudadana y demandas sociales."
  },
  {
    "name": "Data Promce",
    "segment": "Sector Público",
    "tipo": "Software",
    "linea": "Dashboards & Analítica",
    "tags": ["Gobierno", "Región", "Desarrollo", "FONDECUN", "Sankey", "Listo para propuesta"],
    "readyForSale": True,
    "slogan": "Seguimiento al impacto de proyectos de desarrollo",
    "description": "Tablero de visualización de indicadores de gestión, inversión y cobertura de los programas ejecutados por FONDECUN en los municipios de Cundinamarca.",
    "status": "En línea",
    "demoMode": "mostrar",
    "appUrl": "https://data-promce-production.up.railway.app/",
    "githubUrl": "https://github.com/Juansotag/Data-Promce",
    "logo": "assets/projects/datapromce.png",
    "videoUrl": "",
    "pptUrl": "",
    "technologies": "D3.js / Plotly (Diagramas Sankey), Python, Leaflet Mapas de Calor, ReportLab PDF",
    "solution_type": "Tablero de Control de Inversión Pública y Flujo de Recursos",
    "economic_sectors": "Fondos de Desarrollo Departamental (FONDECUN), Gobernaciones, Entidades Ejecutoras",
    "use_cases": "Trazabilidad de recursos desde la fuente presupuestal hasta el municipio beneficiario y reporte PDF."
  },
  {
    "name": "Sabana Centro Sostenible",
    "segment": "Sector Público",
    "tipo": "Software",
    "linea": "Dashboards & Analítica",
    "tags": ["Región", "Sostenibilidad", "Gobierno", "Sabana Centro", "Scoring IA", "Listo para propuesta"],
    "readyForSale": True,
    "slogan": "Monitoreo del desarrollo territorial en Sabana Centro",
    "description": "Plataforma de seguimiento a las metas de sostenibilidad y competitividad de los 11 municipios de la provincia de Sabana Centro, en alianza con Sabana Centro Cómo Vamos.",
    "status": "En línea",
    "demoMode": "mostrar",
    "appUrl": "https://sabana-centro-sostenible-production.up.railway.app/",
    "githubUrl": "https://github.com/Juansotag/Sabana-Centro-Sostenible",
    "logo": "assets/projects/scsv2.png",
    "videoUrl": "",
    "pptUrl": "",
    "technologies": "React, FastAPI, Algoritmos de Scoring Territorial, Supabase",
    "solution_type": "Plataforma Regional de Monitoreo de Objetivos de Desarrollo y Competitividad",
    "economic_sectors": "Think Tanks Regionales (Cómo Vamos), Cámaras de Comercio, Asociaciones de Municipios",
    "use_cases": "Evaluación comparativa entre municipios de Sabana Centro en salud, educación, movilidad y finanzas."
  },
  {
    "name": "SIAG",
    "segment": "Sector Privado",
    "tipo": "Dashboards",
    "linea": "Dashboards & Analítica",
    "tags": ["Educación", "Gestión", "Universidad", "Tableau", "Dashboard"],
    "readyForSale": False,
    "slogan": "Sistema de inteligencia analítica para la gestión",
    "description": "Dashboard institucional para el seguimiento de metas estratégicas, matrícula estudiantil, retención y desempeño financiero de unidades académicas.",
    "status": "En línea",
    "demoMode": "mostrar",
    "appUrl": "https://public.tableau.com/views/SIAG_Dashboard/Inicio",
    "githubUrl": "",
    "logo": "assets/Govlab.png",
    "videoUrl": "",
    "pptUrl": "",
    "technologies": "Tableau Server / Public, SQL Server, Pipelines ETL",
    "solution_type": "Dashboard Directivo de Analítica Institucional",
    "economic_sectors": "Educación Superior, Direcciones de Planeación y Finanzas Universitarias",
    "use_cases": "Seguimiento de KPI de retención estudiantil, balance financiero por facultad y cumplimiento de acreditación."
  },
  {
    "name": "Violencia Intrafamiliar en Colombia",
    "segment": "Sector Público",
    "tipo": "Dashboards",
    "linea": "Dashboards & Analítica",
    "tags": ["Seguridad", "Social", "Familia", "Policía", "Tableau"],
    "readyForSale": False,
    "slogan": "Radiografía nacional de la violencia en los hogares",
    "description": "Visualización analítica con datos de la Policía Nacional sobre denuncias de violencia intrafamiliar por departamento, municipio, grupo etario y género.",
    "status": "En línea",
    "demoMode": "mostrar",
    "appUrl": "https://public.tableau.com/views/ViolenciaIntrafamiliarColombia/Dashboard",
    "githubUrl": "",
    "logo": "assets/Govlab.png",
    "videoUrl": "",
    "pptUrl": "",
    "technologies": "Tableau Public, Datos Abiertos de Policía Nacional, Series Temporales",
    "solution_type": "Tablero Analítico Epidemiológico y de Convivencia",
    "economic_sectors": "Sector Público, Ministerio de Igualdad / ICBF, Secretarías de la Mujer, Policía Nacional",
    "use_cases": "Diseño de rutas de prevención de violencia de género e intrafamiliar focalizadas por municipio."
  },
  {
    "name": "Recursos hospitalarios por cada 100.000 habitantes",
    "segment": "Sector Público",
    "tipo": "Dashboards",
    "linea": "Dashboards & Analítica",
    "tags": ["Salud", "Hospitales", "Gobierno", "Capacidad Hospitalaria", "Tableau"],
    "readyForSale": False,
    "slogan": "Capacidad del sistema de salud en el territorio",
    "description": "Dashboard que mapea la disponibilidad de camas hospitalarias, UCI, ambulancias y personal médico por departamento frente a la densidad poblacional.",
    "status": "En línea",
    "demoMode": "mostrar",
    "appUrl": "https://public.tableau.com/views/RecursosHospitalariosColombia/Dashboard",
    "githubUrl": "",
    "logo": "assets/Govlab.png",
    "videoUrl": "",
    "pptUrl": "",
    "technologies": "Tableau Public, Registro Especial de Prestadores de Servicios de Salud (REPS), MinSalud",
    "solution_type": "Dashboard de Capacidad e Infraestructura de Salud Pública",
    "economic_sectors": "Ministerio de Salud, Secretarías Departamentales de Salud, EPS, Gremios de Clínicas (ACHC)",
    "use_cases": "Evaluación de déficit de camas de cuidados intensivos e intermedias por región geográfica."
  },
  {
    "name": "Registros de la Base Única de afiliados - Adres - Mayo 2025",
    "segment": "Sector Público",
    "tipo": "Dashboards",
    "linea": "Dashboards & Analítica",
    "tags": ["Salud", "Aseguramiento", "Gobierno", "ADRES", "EPS", "Tableau"],
    "readyForSale": False,
    "slogan": "Estructura del aseguramiento en salud en Colombia",
    "description": "Análisis de afiliación al Sistema General de Seguridad Social en Salud: régimen contributivo vs. subsidiado, pirámide de edad y cobertura departamental.",
    "status": "En línea",
    "demoMode": "mostrar",
    "appUrl": "https://public.tableau.com/views/BDUA_Adres_2025/Dashboard",
    "githubUrl": "",
    "logo": "assets/Govlab.png",
    "videoUrl": "",
    "pptUrl": "",
    "technologies": "Tableau Public, Microdatos BDUA - ADRES, Análisis Demográfico",
    "solution_type": "Tablero de Aseguramiento y Cobertura en Salud",
    "economic_sectors": "ADRES, Superintendencia Nacional de Salud, Empresas Promotoras de Salud (EPS), Aseguradoras",
    "use_cases": "Monitoreo del balance entre régimen contributivo y subsidiado, y cálculo de UPC por grupo etario."
  },
  {
    "name": "Envejecimiento poblacional en Colombia por Sexo y Área",
    "segment": "Sector Público",
    "tipo": "Dashboards",
    "linea": "Dashboards & Analítica",
    "tags": ["Demografía", "Salud", "Social", "Envejecimiento", "Tableau"],
    "readyForSale": False,
    "slogan": "Transición demográfica y territorio",
    "description": "Historia interactiva sobre las curvas de envejecimiento y pirámides poblacionales urbanas y rurales en Colombia.",
    "status": "En línea",
    "demoMode": "mostrar",
    "appUrl": "https://public.tableau.com/views/EnvejecimientoPoblacional_SexoArea/Story",
    "githubUrl": "",
    "logo": "assets/Govlab.png",
    "videoUrl": "",
    "pptUrl": "",
    "technologies": "Tableau Story Points, Proyecciones DANE, Modelado Demográfico",
    "solution_type": "Historia Interactiva de Datos Demográficos y Transición Etaria",
    "economic_sectors": "Departamento Nacional de Planeación (DNP), Fondos de Pensiones, Sector Salud, Gerontología",
    "use_cases": "Planificación a largo plazo de sistemas de cuidado, capacidad pensional y servicios para el adulto mayor."
  },
  {
    "name": "Panorama de la Extorsión en Colombia (2010-2024)",
    "segment": "Sector Público",
    "tipo": "Dashboards",
    "linea": "Dashboards & Analítica",
    "tags": ["Seguridad", "Justicia", "Policía", "Extorsión", "Tableau"],
    "readyForSale": False,
    "slogan": "Evolución de un delito de alto impacto",
    "description": "Análisis longitudinal de denuncias, modalidades y focos territoriales del delito de extorsión a lo largo de 14 años.",
    "status": "En línea",
    "demoMode": "mostrar",
    "appUrl": "https://public.tableau.com/views/ExtorsionColombia2010_2024/Dashboard",
    "githubUrl": "",
    "logo": "assets/Govlab.png",
    "videoUrl": "",
    "pptUrl": "",
    "technologies": "Tableau Public, Bases de Datos de GAULA / Policía Nacional, Series de Tiempo",
    "solution_type": "Dashboard Longitudinal de Inteligencia Criminológica",
    "economic_sectors": "Ministerio de Defensa, Policía Nacional / GAULA, Gremios del Comercio (Fenalco, Fedegan)",
    "use_cases": "Identificación de hotspots de extorsión carcelaria vs. presencial y temporadas de alta incidencia."
  },
  {
    "name": "Delitos Sexuales en Colombia",
    "segment": "Sector Público",
    "tipo": "Dashboards",
    "linea": "Dashboards & Analítica",
    "tags": ["Seguridad", "Justicia", "Social", "Protección", "Tableau"],
    "readyForSale": False,
    "slogan": "Evidencia para la protección ciudadana",
    "description": "Mapeo y caracterización de reportes de delitos sexuales para el diseño de políticas de prevención y justicia focalizada.",
    "status": "En línea",
    "demoMode": "mostrar",
    "appUrl": "https://public.tableau.com/views/DelitosSexualesColombia/Dashboard",
    "githubUrl": "",
    "logo": "assets/Govlab.png",
    "videoUrl": "",
    "pptUrl": "",
    "technologies": "Tableau Public, Estadísticas del SPOA / Fiscalía / Policía",
    "solution_type": "Tablero Analítico de Victimización y Protección Ciudadana",
    "economic_sectors": "Fiscalía General de la Nación, ICBF, Comisarías de Familia, Organizaciones de DDHH",
    "use_cases": "Focalización de campañas de prevención y fortalecimiento de rutas de atención de víctimas en infancia y juventud."
  },
  {
    "name": "El Panorama del envejecimiento poblacional en Colombia",
    "segment": "Sector Público",
    "tipo": "Dashboards",
    "linea": "Dashboards & Analítica",
    "tags": ["Demografía", "Salud", "Social", "Adulto Mayor", "Tableau"],
    "readyForSale": False,
    "slogan": "Retos de la longevidad y servicios sociales",
    "description": "Dashboard integral con indicadores de dependencia, índice de envejecimiento y distribución departamental.",
    "status": "En línea",
    "demoMode": "mostrar",
    "appUrl": "https://public.tableau.com/views/PanoramaEnvejecimientoColombia/Dashboard",
    "githubUrl": "",
    "logo": "assets/Govlab.png",
    "videoUrl": "",
    "pptUrl": "",
    "technologies": "Tableau Public, Índices de Dependencia Demográfica, DANE",
    "solution_type": "Dashboard Estratégico de Indicadores de Envejecimiento y Cuidado",
    "economic_sectors": "Sector Público Social, Cajas de Compensación Familiar, Industria de Seguros de Vida",
    "use_cases": "Estimación del índice de envejecimiento para diseño de centros de bienestar y políticas de cuidado."
  },
  {
    "name": "Suicidios en Colombia 2023-2024",
    "segment": "Sector Público",
    "tipo": "Dashboards",
    "linea": "Dashboards & Analítica",
    "tags": ["Salud", "Social", "Prevención", "Salud Mental", "Tableau"],
    "readyForSale": False,
    "slogan": "Datos para la salud mental pública",
    "description": "Monitoreo descriptivo y espacial de eventos de salud mental y suicidio reportados en el territorio nacional.",
    "status": "En línea",
    "demoMode": "mostrar",
    "appUrl": "https://public.tableau.com/views/SuicidiosColombia2023_2024/Dashboard",
    "githubUrl": "",
    "logo": "assets/Govlab.png",
    "videoUrl": "",
    "pptUrl": "",
    "technologies": "Tableau Public, Registros de Medicina Legal / SIVIGILA, Análisis Geoespacial",
    "solution_type": "Tablero de Vigilancia Epidemiológica en Salud Mental",
    "economic_sectors": "Ministerio de Salud, Secretarías de Salud, Universidades (Bienestar), Organizaciones de Salud Mental",
    "use_cases": "Identificación de grupos de edad en riesgo y focos territoriales para despliegue de líneas de apoyo psicológico."
  },
  {
    "name": "Llamadas totales al NUSE/123 por UPZ en Bogotá",
    "segment": "Sector Público",
    "tipo": "Dashboards",
    "linea": "Dashboards & Analítica",
    "tags": ["Emergencias", "Seguridad", "Ciudad", "Línea 123", "Tableau"],
    "readyForSale": False,
    "slogan": "Llamadas de emergencia a escala barrial",
    "description": "Distribución geográfica por Unidades de Planeamiento Zonal (UPZ) de llamadas atendidas por la línea única de emergencias de Bogotá.",
    "status": "En línea",
    "demoMode": "mostrar",
    "appUrl": "https://public.tableau.com/views/NUSE123_UPZ_Bogota/Dashboard",
    "githubUrl": "",
    "logo": "assets/Govlab.png",
    "videoUrl": "",
    "pptUrl": "",
    "technologies": "Tableau Public, Datos del Centro de Comando, Control, Comunicaciones y Cómputo (C4)",
    "solution_type": "Dashboard Geográfico de Incidentes y Despacho de Emergencias",
    "economic_sectors": "Secretaría de Seguridad de Bogotá, Centro de Comando C4, Policía Metropolitana, Bomberos",
    "use_cases": "Evaluación barrial del volumen de reportes por riñas, emergencias médicas y situaciones de seguridad."
  },
  {
    "name": "Precios y productividad del arroz - Forecasting",
    "segment": "Sector Público",
    "tipo": "Dashboards",
    "linea": "Dashboards & Analítica",
    "tags": ["Agro", "Comercio", "Economía", "Forecasting", "Precios Arroz", "Tableau"],
    "readyForSale": False,
    "slogan": "Pronóstico de precios y cosechas agrícolas",
    "description": "Modelo predictivo de series temporales de precios mayoristas y rendimiento por hectárea en el sector arrocero.",
    "status": "En línea",
    "demoMode": "mostrar",
    "appUrl": "https://public.tableau.com/views/ArrozForecasting/Dashboard",
    "githubUrl": "",
    "logo": "assets/Govlab.png",
    "videoUrl": "",
    "pptUrl": "",
    "technologies": "Tableau Public, Modelos ARIMA / Exponential Smoothing, Datos SIPSA / DANE",
    "solution_type": "Tablero Predictivo de Precios Agropecuarios y Forecasting",
    "economic_sectors": "Ministerio de Agricultura, Fedearroz / Gremios Agrícolas, Corabastos / Centrales de Abastos",
    "use_cases": "Anticipación de fluctuaciones de precios del arroz mayorista y planeación de siembras e inventarios."
  },
  {
    "name": "Siniestralidad vial en Bogotá - Forecasting",
    "segment": "Sector Público",
    "tipo": "Dashboards",
    "linea": "Dashboards & Analítica",
    "tags": ["Movilidad", "Seguridad", "Ciudad", "Forecasting", "Tránsito", "Tableau"],
    "readyForSale": False,
    "slogan": "Modelos predictivos de accidentalidad vial",
    "description": "Predicción de eventos de siniestros viales en corredores viales clave de Bogotá mediante técnicas de forecasting.",
    "status": "En línea",
    "demoMode": "mostrar",
    "appUrl": "https://public.tableau.com/views/SiniestralidadBogota_Forecasting/Dashboard",
    "githubUrl": "",
    "logo": "assets/Govlab.png",
    "videoUrl": "",
    "pptUrl": "",
    "technologies": "Tableau Public, Modelos Predictivos Prophet / ARIMA, Secretaría de Movilidad",
    "solution_type": "Tablero Predictivo de Siniestralidad y Tránsito Urbano",
    "economic_sectors": "Secretaría Distrital de Movilidad, Agencia Nacional de Seguridad Vial (ANSV), Aseguradoras (SOAT)",
    "use_cases": "Previsión de accidentalidad por día de la semana y época del año para despliegue de operativos viales."
  },
  {
    "name": "Siniestralidad vial en Bogotá - Siniestros",
    "segment": "Sector Público",
    "tipo": "Dashboards",
    "linea": "Dashboards & Analítica",
    "tags": ["Movilidad", "Seguridad", "Ciudad", "Accidentes", "Tableau"],
    "readyForSale": False,
    "slogan": "Registro y causas de accidentes de tránsito",
    "description": "Visualización histórica 2019-2023 de siniestros viales clasificados por tipo de vehículo, horario y localidad.",
    "status": "En línea",
    "demoMode": "mostrar",
    "appUrl": "https://public.tableau.com/views/SiniestralidadBogota_Siniestros/Dashboard",
    "githubUrl": "",
    "logo": "assets/Govlab.png",
    "videoUrl": "",
    "pptUrl": "",
    "technologies": "Tableau Public, Datos Abiertos de Movilidad Bogotá",
    "solution_type": "Dashboard Histórico y Tipológico de Siniestros Viales",
    "economic_sectors": "Movilidad Urbana, Empresas de Transporte Masivo, Policía de Tránsito",
    "use_cases": "Análisis de correlación entre tipo de vehículo (moto, bus, particular) y causas principales del siniestro."
  },
  {
    "name": "Siniestralidad vial en Bogotá - Víctimas",
    "segment": "Sector Público",
    "tipo": "Dashboards",
    "linea": "Dashboards & Analítica",
    "tags": ["Movilidad", "Salud", "Seguridad", "Víctimas", "Tableau"],
    "readyForSale": False,
    "slogan": "Perfil de actores viales y lesionados",
    "description": "Tablero enfocado en peatones, ciclistas y motociclistas afectados en eventos viales en la capital.",
    "status": "En línea",
    "demoMode": "mostrar",
    "appUrl": "https://public.tableau.com/views/SiniestralidadBogota_Victimas/Dashboard",
    "githubUrl": "",
    "logo": "assets/Govlab.png",
    "videoUrl": "",
    "pptUrl": "",
    "technologies": "Tableau Public, Datos de Fatalidades y Lesionados de Medicina Legal / Movilidad",
    "solution_type": "Dashboard de Vulnerabilidad y Mortalidad Vial",
    "economic_sectors": "Sector Salud (Urgencias), Agencia Nacional de Seguridad Vial, Colectivos de Movilidad Sostenible",
    "use_cases": "Priorización de infraestructura protegida para actores viales vulnerables (ciclorrutas, cruces peatonales)."
  },
  {
    "name": "Siniestralidad vial en Bogotá - Análisis espacial",
    "segment": "Sector Público",
    "tipo": "Dashboards",
    "linea": "Dashboards & Analítica",
    "tags": ["Movilidad", "Ciudad", "Urbanismo", "Mapas de Calor", "Tableau"],
    "readyForSale": False,
    "slogan": "Puntos críticos e intersecciones de alto riesgo",
    "description": "Análisis de concentración geoespacial de accidentes e identificación de tramos viales prioritarios para intervención.",
    "status": "En línea",
    "demoMode": "mostrar",
    "appUrl": "https://public.tableau.com/views/SiniestralidadBogota_Espacial/Dashboard",
    "githubUrl": "",
    "logo": "assets/Govlab.png",
    "videoUrl": "",
    "pptUrl": "",
    "technologies": "Tableau Geoanalítica, Kernel Density Estimation (KDE), Capas GIS de Bogotá",
    "solution_type": "Dashboard Espacial y Mapeo de Puntos Críticos (Blackspots)",
    "economic_sectors": "Instituto de Desarrollo Urbano (IDU), Secretaría de Movilidad, Concesiones Viales",
    "use_cases": "Identificación de intersecciones viales que requieren rediseño semafórico o pacificación de tráfico."
  },
  {
    "name": "Llamadas totales al NUSE/123 por UPZ en Bogotá - Forecasting",
    "segment": "Sector Público",
    "tipo": "Dashboards",
    "linea": "Dashboards & Analítica",
    "tags": ["Emergencias", "Seguridad", "Ciudad", "Forecasting", "NUSE 123", "Tableau"],
    "readyForSale": False,
    "slogan": "Pronóstico de demanda de atención de emergencias",
    "description": "Modelos predictivos de volumen de llamadas al NUSE por UPZ para optimizar el despliegue de patrullas y ambulancias.",
    "status": "En línea",
    "demoMode": "mostrar",
    "appUrl": "https://public.tableau.com/views/NUSE123_UPZ_Forecasting/Dashboard",
    "githubUrl": "",
    "logo": "assets/Govlab.png",
    "videoUrl": "",
    "pptUrl": "",
    "technologies": "Tableau Public, Modelado Predictivo SARIMA / Prophet, Datos C4",
    "solution_type": "Tablero Predictivo de Demanda de Recursos de Emergencia",
    "economic_sectors": "Centro de Despacho C4, Secretaría de Salud (CRUE), Policía de Bogotá",
    "use_cases": "Dimensionamiento de turnos de operadores del 123 y asignación preventiva de ambulancias en zonas de alta demanda."
  },

  # ─── LÍNEA SALUD & GEOANALÍTICA (ESTUDIOS) ───
  {
    "name": "Análisis Clínica Universidad de la Sabana",
    "segment": "Sector Público",
    "tipo": "Estudios & Análisis de datos",
    "linea": "Salud & Geoanalítica",
    "tags": ["Salud", "Hospitales", "Machine Learning", "ARIMA", "Prophet", "Gestión"],
    "readyForSale": False,
    "slogan": "Anticipa la demanda, optimiza los recursos",
    "description": "Sistema ML de series de tiempo (ARIMA y Prophet) con MAE inferior a 10% para pronosticar el número de pacientes NO-EPS y la facturación semanal de la Clínica.",
    "status": "En línea",
    "demoMode": "ppt",
    "appUrl": "",
    "githubUrl": "",
    "logo": "assets/photos/Aliados/clinica.png",
    "videoUrl": "",
    "pptUrl": "assets/projects/analisis_clinica.pdf",
    "technologies": "Python, ARIMA, Facebook Prophet, scikit-learn, Pandas, PDF Reporting",
    "solution_type": "Estudio Predictivo y Modelo ML de Demanda Hospitalaria y Facturación",
    "economic_sectors": "Sector Hospitalario, Clínicas Privadas, Redes Prestadoras de Salud (IPS)",
    "use_cases": "Pronóstico de facturación semanal y flujo de caja por servicios médicos particulares y convenios corporativos."
  },
  {
    "name": "Geoanálisis Clínica Universidad de la Sabana",
    "segment": "Sector Público",
    "tipo": "Estudios & Análisis de datos",
    "linea": "Salud & Geoanalítica",
    "tags": ["Salud", "Territorio", "Geoanalítica", "Hospitales", "Machine Learning"],
    "readyForSale": False,
    "slogan": "Encuentra al paciente antes de que llegue",
    "description": "Análisis predictivo geoespacial de la ubicación y patrones de desplazamiento de potenciales usuarios de servicios de salud privados en Sabana Centro.",
    "status": "En línea",
    "demoMode": "ppt",
    "appUrl": "",
    "githubUrl": "",
    "logo": "assets/photos/Aliados/clinica.png",
    "videoUrl": "",
    "pptUrl": "assets/projects/geoanalisis_clinica.pdf",
    "technologies": "QGIS / GeoPandas, Modelos Gravitacionales de Huff, Datos Sociodemográficos DANE",
    "solution_type": "Estudio de Inteligencia de Mercado Geoespacial para Salud",
    "economic_sectors": "Clínicas y Hospitales, Centros de Especialistas, Aseguradoras de Medicina Prepagada",
    "use_cases": "Identificación de municipios y zonas residenciales con mayor potencial de demanda de medicina ambulatoria."
  },

  # ─── LÍNEA POLÍTICAS PÚBLICAS & TERRITORIO ───
  {
    "name": "Observatorio Social de Zipaquirá - OSZ",
    "segment": "Sector Público",
    "tipo": "Estudios & Análisis de datos",
    "linea": "Políticas Públicas & Territorio",
    "tags": ["Gobierno", "Social", "Ciudad", "Zipaquirá", "Observatorio"],
    "readyForSale": False,
    "slogan": "Alcaldía de Zipaquirá",
    "description": "Desarrollo y diseño del primer observatorio social de la Región Sabana Centro para el seguimiento riguroso de indicadores sociales y bienestar.",
    "status": "En línea",
    "demoMode": "ppt",
    "appUrl": "",
    "githubUrl": "",
    "logo": "assets/projects/osz.png",
    "videoUrl": "",
    "pptUrl": "assets/projects/osz.pdf",
    "technologies": "Metodología de Indicadores Sociales, Python, ReportLab, Análisis de Encuestas",
    "solution_type": "Diseño Metodológico e Informe Estructurado de Observatorio Social",
    "economic_sectors": "Alcaldías Municipales, Secretarías de Desarrollo Social, Observatorios Territoriales",
    "use_cases": "Evaluación de pobreza multidimensional, empleo informal y vulnerabilidad social en Zipaquirá."
  },

  # ─── LÍNEA ELECTORAL & PRONÓSTICO ───
  {
    "name": "ELA-NOM",
    "segment": "Sector Público",
    "tipo": "Estudios & Análisis de datos",
    "linea": "Electoral & Pronóstico",
    "tags": ["Política", "Medios", "Electoral", "Pronóstico", "Minería de Redes"],
    "readyForSale": False,
    "slogan": "Pronostica elecciones con redes sociales",
    "description": "Aplicación de una novedosa metodología de pronóstico electoral (ELA-NOM) basada en minería de redes sociales con error predictivo inferior al 9%.",
    "status": "En línea",
    "demoMode": "ppt",
    "appUrl": "",
    "githubUrl": "",
    "logo": "assets/Govlab.png",
    "videoUrl": "",
    "pptUrl": "assets/projects/elanom.pdf",
    "technologies": "NLP, Minería de Redes Sociales (X/Twitter/TikTok), Algoritmo Estadístico ELA-NOM, Python",
    "solution_type": "Metodología y Modelo Predictivo Electoral Basado en Big Data Social",
    "economic_sectors": "Consultoría Política, Medios de Comunicación, Partidos Políticos, Campañas Electorales",
    "use_cases": "Pronóstico de intención de voto y tendencias electorales sin sesgos de muestreo telefónico tradicional."
  },

  # ─── LÍNEA EDUCACIÓN & FORMACIÓN ───
  {
    "name": "Doctorado en IA",
    "segment": "Transversal",
    "tipo": "Educación",
    "linea": "Educación & Formación",
    "tags": ["Educación", "Investigación", "Gobierno", "Posgrado", "Doctorado"],
    "readyForSale": False,
    "slogan": "Investiga el futuro, lidera el cambio",
    "description": "Programa doctoral de investigación de vanguardia en inteligencia artificial, enfocado en soluciones para el sector público y formulación de políticas basadas en evidencia.",
    "status": "En línea",
    "demoMode": "mostrar",
    "appUrl": "https://www.unisabana.edu.co/programas/posgrados/doctorado-en-inteligencia-artificial/",
    "githubUrl": "",
    "logo": "assets/Govlab.png",
    "videoUrl": "",
    "pptUrl": "",
    "technologies": "Deep Learning, Redes Neuronales, Ética de IA, Políticas Basadas en Datos",
    "solution_type": "Programa Académico Doctoral de Alta Investigación",
    "economic_sectors": "Educación Superior, Sector Público (MinCiencias), Centros de I+D+i Corporativos",
    "use_cases": "Formación de investigadores de nivel PhD para liderar la transformación con IA en Colombia y la región."
  },
  {
    "name": "Maestría en IA",
    "segment": "Transversal",
    "tipo": "Educación",
    "linea": "Educación & Formación",
    "tags": ["Educación", "Gobierno", "Empresa", "Maestría", "Analítica"],
    "readyForSale": False,
    "slogan": "Domina la IA, transforma tu sector",
    "description": "Programa de posgrado en inteligencia artificial y analítica aplicada con énfasis en gobierno digital, política pública y gestión estratégica organizacional.",
    "status": "En línea",
    "demoMode": "mostrar",
    "appUrl": "https://www.unisabana.edu.co/programas/posgrados/maestria-en-inteligencia-artificial-aplicada/",
    "githubUrl": "",
    "logo": "assets/Govlab.png",
    "videoUrl": "",
    "pptUrl": "",
    "technologies": "Machine Learning Aplicado, LLMs, MLOps, Gobierno Digital",
    "solution_type": "Programa de Posgrado y Maestría Profesional",
    "economic_sectors": "Sector Público y Privado, Directores de Tecnología (CTO/CDO), Consultoría Estratégica",
    "use_cases": "Capacitación de líderes ejecutivos y técnicos para implementar IA en organizaciones públicas y privadas."
  },
  {
    "name": "Pregrado en IA",
    "segment": "Transversal",
    "tipo": "Educación",
    "linea": "Educación & Formación",
    "tags": ["Educación", "Tecnología", "Ciencia", "Pregrado", "Ciencia de Datos"],
    "readyForSale": False,
    "slogan": "Aprende IA desde la raíz",
    "description": "Programa de pregrado en Ciencia de Datos e Inteligencia Artificial de la Universidad de La Sabana. Formación integral en modelos, algoritmos y aplicaciones reales.",
    "status": "En línea",
    "demoMode": "mostrar",
    "appUrl": "https://www.unisabana.edu.co/programas/carreras/ingenieria-en-inteligencia-artificial/",
    "githubUrl": "",
    "logo": "assets/Govlab.png",
    "videoUrl": "",
    "pptUrl": "",
    "technologies": "Python, PyTorch, Modelado Matemático, Bases de Datos, Algoritmos",
    "solution_type": "Programa Universitario de Pregrado Profesional",
    "economic_sectors": "Industria Tecnológica, Startups, Sector Financiero, Educación Superior",
    "use_cases": "Formación de ingenieros y científicos de datos desde pregrado con enfoque práctico y ético."
  },
  {
    "name": "Bootcamps en IA",
    "segment": "Transversal",
    "tipo": "Educación",
    "linea": "Educación & Formación",
    "tags": ["Educación", "Empresa", "Capacitación", "Bootcamp", "Formación Ejecutiva"],
    "readyForSale": False,
    "slogan": "Habilidades reales, en tiempo récord",
    "description": "Programas técnicos intensivos de capacitación en IA para profesionales y directivos del sector público y privado, orientados a casos de uso inmediatos.",
    "status": "En línea",
    "demoMode": "mostrar",
    "appUrl": "https://www.unisabana.edu.co/programas/educacion-continua/bootcamps-ia/",
    "githubUrl": "",
    "logo": "assets/Govlab.png",
    "videoUrl": "",
    "pptUrl": "",
    "technologies": "Prompt Engineering, Automatización con IA, No-Code/Low-Code, GenAI Tools",
    "solution_type": "Programa Intensivo de Educación Continua y Upskilling",
    "economic_sectors": "Sector Corporativo, Entidades Públicas, Pymes, Profesionales Independientes",
    "use_cases": "Entrenamiento rápido de equipos de trabajo en productividad, automatización de tareas y uso de herramientas de IA."
  }
]

# 1. Update products_data.json
products_json = []
for p in PRODUCTS_DETAIL:
    prod_entry = {
        "segment": p["segment"],
        "tipo": p["tipo"],
        "linea": p["linea"],
        "tags": p["tags"],
        "readyForSale": p["readyForSale"],
        "name": p["name"],
        "slogan": p["slogan"],
        "description": p["description"],
        "status": p["status"],
        "demoMode": p["demoMode"],
        "appUrl": p["appUrl"],
        "githubUrl": p["githubUrl"],
        "logo": p["logo"],
        "videoUrl": p["videoUrl"],
        "pptUrl": p["pptUrl"]
    }
    products_json.append(prod_entry)

with open("products_data.json", "w", encoding="utf-8") as f:
    json.dump(products_json, f, ensure_ascii=False, indent=2)

print(f"Updated products_data.json with {len(products_json)} products.")

# 2. Generate CSV: Productos_Software_GovLab_Sectores.csv
# CSV with UTF-8 BOM so Excel opens with proper accents and formatting
csv_filename = "Productos_Software_GovLab_Sectores.csv"
csv_headers = [
    "ID",
    "Nombre del Producto",
    "Tipo de Solución",
    "Línea / Categoría",
    "Segmento",
    "Estado",
    "Listo para Propuesta",
    "Tecnologías Utilizadas",
    "Sectores Económicos de Aplicación",
    "Tags del Portafolio",
    "Lema / Slogan",
    "Descripción General",
    "Casos de Uso Principales",
    "Link de Despliegue",
    "Repositorio GitHub",
    "Enlace Video Demo",
    "Enlace Presentación"
]

with open(csv_filename, "w", encoding="utf-8-sig", newline="") as f:
    writer = csv.writer(f, delimiter=";", quoting=csv.QUOTE_MINIMAL)
    writer.writerow(csv_headers)
    for i, p in enumerate(PRODUCTS_DETAIL, 1):
        writer.writerow([
            f"GL-{i:03d}",
            p["name"],
            p["solution_type"],
            p["linea"],
            p["segment"],
            p["status"],
            "Sí" if p["readyForSale"] else "No",
            p["technologies"],
            p["economic_sectors"],
            ", ".join(p["tags"]),
            p["slogan"],
            p["description"],
            p["use_cases"],
            p["appUrl"] if p["appUrl"] else "NA",
            p["githubUrl"] if p["githubUrl"] else "NA",
            p["videoUrl"] if p["videoUrl"] else "NA",
            p["pptUrl"] if p["pptUrl"] else "NA"
        ])

print(f"Created CSV: {csv_filename} with {len(PRODUCTS_DETAIL)} entries.")

# Also generate a specific CSV focusing strictly on the Software category products
software_csv_filename = "Productos_Software_GovLab.csv"
with open(software_csv_filename, "w", encoding="utf-8-sig", newline="") as f:
    writer = csv.writer(f, delimiter=";", quoting=csv.QUOTE_MINIMAL)
    writer.writerow(csv_headers)
    software_products = [p for p in PRODUCTS_DETAIL if p["tipo"] == "Software"]
    for i, p in enumerate(software_products, 1):
        writer.writerow([
            f"GL-SW-{i:03d}",
            p["name"],
            p["solution_type"],
            p["linea"],
            p["segment"],
            p["status"],
            "Sí" if p["readyForSale"] else "No",
            p["technologies"],
            p["economic_sectors"],
            ", ".join(p["tags"]),
            p["slogan"],
            p["description"],
            p["use_cases"],
            p["appUrl"] if p["appUrl"] else "NA",
            p["githubUrl"] if p["githubUrl"] else "NA",
            p["videoUrl"] if p["videoUrl"] else "NA",
            p["pptUrl"] if p["pptUrl"] else "NA"
        ])

print(f"Created CSV: {software_csv_filename} with {len(software_products)} software products.")
