# build_app_data.py
import json

products = [
  # â”€â”€â”€ LÃNEA PITCHLAB (SOFTWARE) â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  {
    "segment": "Sector PÃºblico",
    "tipo": "Software",
    "linea": "LÃ­nea PitchLab",
    "tags": ["PitchLab", "Discurso PolÃ­tico", "IA Generativa", "Claude", "Listo para la venta"],
    "readyForSale": True,
    "name": "PitchLab360",
    "slogan": "Analiza el discurso, mejora el mensaje",
    "description": "AnÃ¡lisis de discurso polÃ­tico con Claude (Anthropic). Perfil comunicativo, anÃ¡lisis emocional, stakeholders, encuadres narrativos y potencial digital. Probado con candidatos presidenciales.",
    "status": "En lÃ­nea",
    "demoMode": "mostrar",
    "appUrl": "https://pitchlab360-production.up.railway.app/",
    "githubUrl": "https://github.com/Juansotag/PitchLab360",
    "logo": "assets/projects/pitchlab360.jpg",
    "videoUrl": "https://drive.google.com/file/d/1bYLxn5TCm_Hwq6DG7-u7UYui5N5szYUm/view?usp=drive_link",
    "pptUrl": "",
  },
  {
    "segment": "Sector PÃºblico",
    "tipo": "Software",
    "linea": "LÃ­nea PitchLab",
    "tags": ["PitchLab", "Fact-checking", "Chrome Extension", "GPT-4o", "Listo para la venta"],
    "readyForSale": True,
    "name": "Polycheck",
    "slogan": "Verifica en tiempo real, no despuÃ©s",
    "description": "ExtensiÃ³n de Chrome para fact-checking en tiempo real sobre videos de YouTube y directos. IntegraciÃ³n GPT-4o + Gemini + Google Search para anÃ¡lisis forense del discurso.",
    "status": "En lÃ­nea",
    "demoMode": "mostrar",
    "appUrl": "",
    "githubUrl": "https://github.com/Juansotag/Polycheck",
    "logo": "assets/projects/polycheck.jpg",
    "videoUrl": "https://drive.google.com/file/d/111GwtqEWziIQFwi8BxMgQhiR6ZT-o2YW/view?usp=drive_link",
    "pptUrl": "",
  },
  {
    "segment": "Sector Privado",
    "tipo": "Software",
    "linea": "LÃ­nea PitchLab",
    "tags": ["PitchLab", "Pitch MÃ©dico", "INVIMA", "Entrenamiento", "Listo para la venta"],
    "readyForSale": True,
    "name": "PitchLab Med",
    "slogan": "Practica tu pitch mÃ©dico con estÃ¡ndares INVIMA",
    "description": "Plataforma para la prÃ¡ctica y evaluaciÃ³n de pitch mÃ©dicos con medidas de rigurosidad INVIMA. Entrenamiento conversacional para profesionales e industria farmacÃ©utica.",
    "status": "En lÃ­nea",
    "demoMode": "mostrar",
    "appUrl": "https://pitchlab-med.up.railway.app/",
    "githubUrl": "https://github.com/Juansotag/PitchLab360-comercial",
    "logo": "assets/projects/pitchlab360.jpg",
    "videoUrl": "",
    "pptUrl": "",
  },
  {
    "segment": "Sector PÃºblico",
    "tipo": "Software",
    "linea": "LÃ­nea PitchLab",
    "tags": ["PitchLab", "Avatar en Vivo", "Voz en Tiempo Real", "NegociaciÃ³n", "Listo para la venta"],
    "readyForSale": True,
    "name": "PitchLab Entrenamiento",
    "slogan": "Avatar conversacional para entrenamiento",
    "description": "Herramienta de la LÃ­nea PitchLab para el entrenamiento de conversaciones en voz en vivo, adaptado para negociaciones polÃ­ticas, comerciales o acadÃ©micas.",
    "status": "En lÃ­nea",
    "demoMode": "mostrar",
    "appUrl": "https://avatarentrenamiento.up.railway.app/",
    "githubUrl": "https://github.com/Juansotag/Avatar_entrenamiento",
    "logo": "assets/projects/pitchlab360.jpg",
    "videoUrl": "",
    "pptUrl": "",
  },

  # â”€â”€â”€ LÃNEA GOVTEST & OPINIÃ“N PÃšBLICA (SOFTWARE) â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  {
    "segment": "Sector PÃºblico",
    "tipo": "Software",
    "linea": "LÃ­nea GovTest & OpiniÃ³n",
    "tags": ["GovTest", "Afinidad PolÃ­tica", "Elecciones 2026", "Viral", "Listo para la venta"],
    "readyForSale": True,
    "name": "GovTest",
    "slogan": "Descubre tu candidato con datos",
    "description": "Test de afinidad polÃ­tica por dilemas de polÃ­tica pÃºblica. 16 preguntas, 14 candidatos presidenciales 2026, 7 arquetipos de votante y tarjeta viral descargable.",
    "status": "En lÃ­nea",
    "demoMode": "mostrar",
    "appUrl": "https://convergencia-electoral.up.railway.app/",
    "githubUrl": "https://github.com/GovLabSabana/test-dilema",
    "logo": "assets/projects/govtest.jpg",
    "videoUrl": "https://drive.google.com/file/d/1B1RWm_HmN4HlHjiIzlDzh58FqfGpITkX/view?usp=drive_link",
    "pptUrl": "",
  },
  {
    "segment": "Sector PÃºblico",
    "tipo": "Software",
    "linea": "LÃ­nea GovTest & OpiniÃ³n",
    "tags": ["GovTest", "9 Ejes IdeolÃ³gicos", "Supabase", "Ranking", "Listo para la venta"],
    "readyForSale": True,
    "name": "Test 9 Ejes",
    "slogan": "Tu posiciÃ³n en 9 ejes, tu candidato en un clic",
    "description": "Test de afinidad polÃ­tica por 9 ejes ideolÃ³gicos. Algoritmo euclidiano, ranking de candidatos, perfil personalizado y persistencia de datos en Supabase.",
    "status": "En lÃ­nea",
    "demoMode": "mostrar",
    "appUrl": "https://test9ejes.up.railway.app/",
    "githubUrl": "https://github.com/GovLabSabana/Test_9ejes",
    "logo": "assets/projects/test9ejes.jpg",
    "videoUrl": "https://drive.google.com/file/d/1IpEH495QROwq8k3VdkaD52tjbJKX68Iv/view?usp=drive_link",
    "pptUrl": "",
  },
  {
    "segment": "Sector PÃºblico",
    "tipo": "Software",
    "linea": "LÃ­nea GovTest & OpiniÃ³n",
    "tags": ["GovTest", "50 Preguntas", "Coyuntura Colombia", "Glassmorphism", "Listo para la venta"],
    "readyForSale": True,
    "name": "Test 9 Ejes Colombia",
    "slogan": "50 preguntas, un perfil ideolÃ³gico",
    "description": "VersiÃ³n extendida del test con 50 preguntas coyunturales sobre Colombia. Modo oscuro glassmorphism, compartir en alta resoluciÃ³n y datos anÃ³nimos en Supabase.",
    "status": "En lÃ­nea",
    "demoMode": "mostrar",
    "appUrl": "https://test9col.up.railway.app/",
    "githubUrl": "https://github.com/GovLabSabana/Test_9ejesColombia",
    "logo": "assets/projects/test9ejes.jpg",
    "videoUrl": "https://drive.google.com/file/d/1gXzEi2ZNE4daXYBnidmccgcgkWj2Db84/view?usp=drive_link",
    "pptUrl": "",
  },

  # â”€â”€â”€ LÃNEA ASISTENTES DE VOZ CON IA (SOFTWARE) â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  {
    "segment": "Sector PÃºblico",
    "tipo": "Software",
    "linea": "Asistentes de Voz",
    "tags": ["Asistentes de Voz", "LiveKit", "OpenAI Realtime", "CajicÃ¡", "WebRTC"],
    "readyForSale": False,
    "name": "AlcaldesaIA",
    "slogan": "PregÃºntale al municipio, Ã©l te responde",
    "description": "Asistente de voz en tiempo real sobre el Plan de Desarrollo de CajicÃ¡ 2024-2027. OpenAI Realtime API + LiveKit + WebRTC.",
    "status": "En mantenimiento",
    "demoMode": "mostrar",
    "appUrl": "https://asistente-virtual-cajica.up.railway.app/",
    "githubUrl": "https://github.com/GovLabSabana/cajica",
    "logo": "assets/projects/alcaldesa.png",
    "videoUrl": "",
    "pptUrl": "",
  },
  {
    "segment": "Sector Privado",
    "tipo": "Software",
    "linea": "Asistentes de Voz",
    "tags": ["Asistentes de Voz", "PQRS", "LiveKit", "OpenAI Realtime", "Santander", "Listo para la venta"],
    "readyForSale": True,
    "name": "Gober Santander",
    "slogan": "Un asistente pÃºblico para cada ciudadano",
    "description": "Asistente de voz conversacional para el sector pÃºblico. Procesamiento de PQRS, visualizaciÃ³n de datos e interfaz para funcionarios con OpenAI Realtime + LiveKit.",
    "status": "En lÃ­nea",
    "demoMode": "mostrar",
    "appUrl": "https://santander-production.up.railway.app/",
    "githubUrl": "https://github.com/GovLabSabana/Santander",
    "logo": "assets/projects/gober.png",
    "videoUrl": "https://drive.google.com/file/d/1JZj-tysFp6FlbX3NeH5Y4pINnr_1dNzg/view?usp=drive_link",
    "pptUrl": "",
  },
  {
    "segment": "Sector PÃºblico",
    "tipo": "Software",
    "linea": "Asistentes de Voz",
    "tags": ["Asistentes de Voz", "GovLab", "AtenciÃ³n al Ciudadano"],
    "readyForSale": False,
    "name": "Govi",
    "slogan": "El GovLab te habla, tÃº lo escuchas",
    "description": "Asistente basado en voz para la consulta y acercamiento al cliente del Laboratorio de Gobierno de la Universidad de La Sabana.",
    "status": "En mantenimiento",
    "demoMode": "mostrar",
    "appUrl": "",
    "githubUrl": "https://github.com/GovLabSabana/Govi2",
    "logo": "assets/Govlab.png",
    "videoUrl": "",
    "pptUrl": "",
  },
  {
    "segment": "Sector Privado",
    "tipo": "Software",
    "linea": "Asistentes de Voz",
    "tags": ["Asistentes de Voz", "Next.js", "LiveKit", "Silero VAD", "ConvergenceLab", "Listo para la venta"],
    "readyForSale": True,
    "name": "ConvergenceLab",
    "slogan": "Habla con la universidad, ella te escucha",
    "description": "Asistente de voz en tiempo real para el Convergence Lab de la Unisabana (Sabius). Permite consultar aliados e investigaciones relevantes. LiveKit Agents + OpenAI Realtime API + Silero VAD.",
    "status": "En lÃ­nea",
    "demoMode": "mostrar",
    "appUrl": "https://convergencelab.up.railway.app/",
    "githubUrl": "https://github.com/GovLabSabana/ConvergenceLAb",
    "logo": "assets/projects/convergence.png",
    "videoUrl": "https://drive.google.com/file/d/1r-HPmA_JXTUB45rQpJKJ7RzEZwTaReno/view?usp=drive_link",
    "pptUrl": "",
  },
  {
    "segment": "Sector Privado",
    "tipo": "Software",
    "linea": "Asistentes de Voz",
    "tags": ["Asistentes de Voz", "Llamadas Automatizadas", "Dapta", "Outbound Calls", "Listo para la venta"],
    "readyForSale": True,
    "name": "Alocandidato",
    "slogan": "La campaÃ±a que llama, nunca la que cansa",
    "description": "Sistema de llamadas de voz automatizadas a ciudadanos con preguntas interactivas sobre candidatos y propuestas con tecnologÃ­a Dapta.",
    "status": "En lÃ­nea",
    "demoMode": "mostrar",
    "appUrl": "",
    "githubUrl": "",
    "logo": "assets/projects/alocandidato.jpg",
    "videoUrl": "https://drive.google.com/file/d/1bOY7U-cqev5172oxBTSLvazsdPdM2hTT/view?usp=drive_link",
    "pptUrl": "",
  },

  # â”€â”€â”€ LÃNEA AGROINDUSTRIA & EXPORTACIÃ“N (SOFTWARE) â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  {
    "segment": "Sector Privado",
    "tipo": "Software",
    "linea": "Agroindustria & ExportaciÃ³n",
    "tags": ["Corpohass", "Aguacate Hass", "Trazabilidad", "FastAPI", "React", "Listo para la venta"],
    "readyForSale": True,
    "name": "HassApp",
    "slogan": "Del campo al mundo, con datos",
    "description": "Plataforma integral para gestiÃ³n de producciÃ³n, cosecha, insumos, exportaciÃ³n y sondeo de opiniÃ³n del sector aguacate Hass. FastAPI + React + MySQL + AWS S3.",
    "status": "En lÃ­nea",
    "demoMode": "mostrar",
    "appUrl": "https://heartfelt-success-production-8486.up.railway.app/",
    "githubUrl": "https://github.com/GovLabSabana/HassApp",
    "logo": "assets/projects/hassapp.png",
    "videoUrl": "https://drive.google.com/file/d/1WMHMOz0j_DHamcykskRayQAUyCyPpryw/view?usp=drive_link",
    "pptUrl": "",
  },
  {
    "segment": "Sector Privado",
    "tipo": "Software",
    "linea": "Agroindustria & ExportaciÃ³n",
    "tags": ["Corpohass", "DiagnÃ³stico Exportador", "TermÃ³metro IA", "FastAPI", "Listo para la venta"],
    "readyForSale": True,
    "name": "ExportaCheck",
    "slogan": "Â¿Listo para exportar? DescÃºbrelo hoy",
    "description": "Plataforma con termÃ³metro interactivo que evalÃºa el nivel de preparaciÃ³n exportadora de empresas agrÃ­colas y productoras. DiagnÃ³stico por dimensiones con IA. Next.js + FastAPI + Supabase.",
    "status": "En lÃ­nea",
    "demoMode": "mostrar",
    "appUrl": "https://exporta-facil-bot-production-e49c.up.railway.app/",
    "githubUrl": "https://github.com/GovLabSabana/TermoExportador",
    "logo": "assets/projects/exportacheck.jpg",
    "videoUrl": "https://drive.google.com/file/d/1X7QuSOTr0gCKC7rLTdSzvLsoyWHbyw_i/view?usp=drive_link",
    "pptUrl": "",
  },

  # â”€â”€â”€ LÃNEA NOTARÃAS & GESTIÃ“N DOCUMENTAL (SOFTWARE) â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  {
    "segment": "Sector Privado",
    "tipo": "Software",
    "linea": "NotarÃ­as & Documental",
    "tags": ["NotarÃ­as", "Borradores de Escrituras", "Chat IA", "Cumplimiento", "Listo para la venta"],
    "readyForSale": True,
    "name": "NotariaDoc",
    "slogan": "El borrador perfecto, sin esperas",
    "description": "MVP para construir borradores de escrituras notariales, verificaciÃ³n de requisitos de cumplimiento y asistente conversacional con RAG legal.",
    "status": "En lÃ­nea",
    "demoMode": "mostrar",
    "appUrl": "https://notariadoc-production.up.railway.app/",
    "githubUrl": "https://github.com/GovLabSabana/NotariaDoc",
    "logo": "assets/Govlab.png",
    "videoUrl": "https://drive.google.com/file/d/1BNngISeVJ6rFuEdgpbrmGFCxAjOLwgFE/view?usp=drive_link",
    "pptUrl": "",
  },
  {
    "segment": "Sector Privado",
    "tipo": "Software",
    "linea": "NotarÃ­as & Documental",
    "tags": ["NotarÃ­as", "Panel de Control", "PronÃ³stico", "Tiempos de Espera", "Listo para la venta"],
    "readyForSale": True,
    "name": "NotariaIQ",
    "slogan": "Control total de la notarÃ­a en un panel",
    "description": "Panel de control para notarÃ­as: seguimiento de usuarios, tiempos de espera, ingresos, egresos, anÃ¡lisis descriptivo y pronÃ³stico de afluencia con IA.",
    "status": "En lÃ­nea",
    "demoMode": "mostrar",
    "appUrl": "https://notariaiq-production.up.railway.app/",
    "githubUrl": "https://github.com/GovLabSabana/NotariaIQ",
    "logo": "assets/Govlab.png",
    "videoUrl": "https://drive.google.com/file/d/19wx_KXzy9Byorjwu40xK5E3ymxglD_aO/view?usp=drive_link",
    "pptUrl": "",
  },
  {
    "segment": "Sector Privado",
    "tipo": "Software",
    "linea": "NotarÃ­as & Documental",
    "tags": ["NotarÃ­as", "Constructoras", "Flujo de AprobaciÃ³n", "Cero Papel", "Listo para la venta"],
    "readyForSale": True,
    "name": "Radica NotarÃ­a",
    "slogan": "Radica, revisa y aprueba sin papel",
    "description": "Suite de automatizaciÃ³n documental para la NotarÃ­a Segunda de ZipaquirÃ¡. Formulario para constructoras + panel de digitadora con flujo de aprobaciÃ³n de escrituras.",
    "status": "En lÃ­nea",
    "demoMode": "mostrar",
    "appUrl": "https://radicanotaria-production.up.railway.app/",
    "githubUrl": "https://github.com/GovLabSabana/Radica_notaria",
    "logo": "assets/Govlab.png",
    "videoUrl": "https://drive.google.com/file/d/1cmOw8OCh4UhW1YzWrMBpbsMvaZZjnrSV/view?usp=drive_link",
    "pptUrl": "",
  },
  {
    "segment": "Sector PÃºblico",
    "tipo": "Software",
    "linea": "ProyecciÃ³n Social & Directiva",
    "tags": ["GestiÃ³n Documental", "Alto Gobierno", "SÃ­ntesis Ejecutiva", "Decisiones", "Listo para la venta"],
    "readyForSale": True,
    "name": "Resume Expedientes",
    "slogan": "Decisiones de alto gobierno en segundos",
    "description": "Herramienta con IA para resumir expedientes directivos complejos y apoyar la toma de decisiones estratÃ©gicas de alto gobierno.",
    "status": "En lÃ­nea",
    "demoMode": "mostrar",
    "appUrl": "https://expedientes.up.railway.app/",
    "githubUrl": "https://github.com/Juansotag/resumidor-expedientes",
    "logo": "assets/Govlab.png",
    "videoUrl": "",
    "pptUrl": "",
  },
  {
    "segment": "Sector PÃºblico",
    "tipo": "Software",
    "linea": "ProyecciÃ³n Social & Directiva",
    "tags": ["ProyecciÃ³n Social", "CRON", "WhatsApp", "Email", "Newsletter", "Listo para la venta"],
    "readyForSale": True,
    "name": "NewsletterMaker",
    "slogan": "Generador y envÃ­o de newsletter",
    "description": "Plataforma para la construcciÃ³n de Newsletters y la asignaciÃ³n de procesos asÃ­ncronos CRON por correo y WhatsApp para la DirecciÃ³n de ProyecciÃ³n Social.",
    "status": "En lÃ­nea",
    "demoMode": "mostrar",
    "appUrl": "https://newsletter-pse.up.railway.app/",
    "githubUrl": "https://github.com/Juansotag/Newsletter---Proyecci-n-social",
    "logo": "assets/Govlab.png",
    "videoUrl": "",
    "pptUrl": "",
  },

  # â”€â”€â”€ LÃNEA GESTIÃ“N PÃšBLICA, JURÃDICA & AMBIENTAL (SOFTWARE) â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  {
    "segment": "Sector PÃºblico",
    "tipo": "Software",
    "linea": "GestiÃ³n PÃºblica & Ambiental",
    "tags": ["CAR Cundinamarca", "PQRS AutomÃ¡tico", "IA", "ClasificaciÃ³n", "Listo para la venta"],
    "readyForSale": True,
    "name": "CAResponde",
    "slogan": "De la PQRS al ciudadano en segundos",
    "description": "Asistente en texto para la CAR Cundinamarca: recibe, categoriza, visualiza y genera respuestas automÃ¡ticas a PQRS con inteligencia artificial.",
    "status": "En lÃ­nea",
    "demoMode": "mostrar",
    "appUrl": "https://car-pqrs-production.up.railway.app/",
    "githubUrl": "https://github.com/GovLabSabana/CAR-pqrs",
    "logo": "assets/projects/caresponde.png",
    "videoUrl": "https://drive.google.com/file/d/1Z9kNrQxgHan2YKVw9oRovIzGJfLPp86j/view?usp=drive_link",
    "pptUrl": "",
  },
  {
    "segment": "Sector PÃºblico",
    "tipo": "Software",
    "linea": "GestiÃ³n PÃºblica & Ambiental",
    "tags": ["BogotÃ¡", "Plan de Desarrollo", "RAG FAISS", "GPT-4o", "Listo para la venta"],
    "readyForSale": True,
    "name": "AlcaldIA",
    "slogan": "El Plan de Desarrollo en tus manos",
    "description": "Asistente RAG sobre el Plan de Desarrollo Distrital de BogotÃ¡. BÃºsqueda semÃ¡ntica con FAISS + GPT-4o para consultas por meta, programa y presupuesto.",
    "status": "En lÃ­nea",
    "demoMode": "mostrar",
    "appUrl": "https://alcadia.up.railway.app/",
    "githubUrl": "https://github.com/GovLabSabana/AlcaldIA",
    "logo": "assets/Govlab.png",
    "videoUrl": "https://drive.google.com/file/d/1rfDiEcx6BD2r3HDHG5GSUVze8Bd8O9ww/view?usp=drive_link",
    "pptUrl": "",
  },
  {
    "segment": "Sector PÃºblico",
    "tipo": "Software",
    "linea": "GestiÃ³n PÃºblica & Ambiental",
    "tags": ["PolicÃ­a Ambiental", "LegislaciÃ³n Ambiental", "Jurisprudencia", "Carabineros"],
    "readyForSale": False,
    "name": "PoliciApp-Eco",
    "slogan": "La ley ambiental en campo",
    "description": "Asistente IA de legislaciÃ³n ambiental colombiana para la PolicÃ­a Ambiental y Carabineros. Cubre pesca, flora, fauna, minerÃ­a y recursos hÃ­dricos.",
    "status": "En mantenimiento",
    "demoMode": "mostrar",
    "appUrl": "",
    "githubUrl": "https://github.com/GovLabSabana/PoliciApp-Eco2",
    "logo": "assets/Govlab.png",
    "videoUrl": "",
    "pptUrl": "",
  },
  {
    "segment": "Sector PÃºblico",
    "tipo": "Software",
    "linea": "GestiÃ³n PÃºblica & Ambiental",
    "tags": ["PolicÃ­a Ambiental", "Normativa Ambiental", "Jurisprudencia", "Chatbot"],
    "readyForSale": False,
    "name": "PoliciaAmbiental",
    "slogan": "Jurisprudencia ambiental en campo",
    "description": "Chatbot para facilitar conocimientos de jurisprudencia y competencias operativas para la policÃ­a ambiental de Colombia.",
    "status": "En mantenimiento",
    "demoMode": "mostrar",
    "appUrl": "",
    "githubUrl": "https://github.com/GovLabSabana/Policia_ambiental",
    "logo": "assets/Govlab.png",
    "videoUrl": "",
    "pptUrl": "",
  },
  {
    "segment": "Sector PÃºblico",
    "tipo": "Software",
    "linea": "GestiÃ³n PÃºblica & Ambiental",
    "tags": ["ComparaciÃ³n Normativa", "Diff SemÃ¡ntico", "GPT-4", "Leyes"],
    "readyForSale": False,
    "name": "LegisCheck",
    "slogan": "Dos versiones, un solo vistazo",
    "description": "ComparaciÃ³n inteligente de documentos legislativos. Diff semÃ¡ntico con GPT-4, lÃ­nea de tiempo de cambios normativos y reportes PDF.",
    "status": "En mantenimiento",
    "demoMode": "mostrar",
    "appUrl": "",
    "githubUrl": "https://github.com/GovLabSabana/Paralelo",
    "logo": "assets/projects/Legischeck.png",
    "videoUrl": "",
    "pptUrl": "",
  },
  {
    "segment": "Sector PÃºblico",
    "tipo": "Software",
    "linea": "Seguridad & AnalÃ­tica",
    "tags": ["Observatorio de Seguridad", "PredicciÃ³n Delitos", "Barranquilla", "Listo para la venta"],
    "readyForSale": True,
    "name": "Barranquilla",
    "slogan": "Predice la criminalidad, protege la ciudad",
    "description": "App web para subir, analizar y predecir eventos de criminalidad y convivencia ciudadana para el Observatorio de Seguridad de Barranquilla.",
    "status": "En lÃ­nea",
    "demoMode": "mostrar",
    "appUrl": "https://barranquilla-production.up.railway.app/",
    "githubUrl": "https://github.com/GovLabSabana/Barranquilla",
    "logo": "assets/Govlab.png",
    "videoUrl": "https://drive.google.com/file/d/1X7_dn5FwxNv9XvoflFxJrNYQPzxmr8DJ/view?usp=drive_link",
    "pptUrl": "",
  },

  # â”€â”€â”€ LÃNEA SOSTENIBILIDAD & COMUNIDAD (SOFTWARE) â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  {
    "segment": "Sector Privado",
    "tipo": "Software",
    "linea": "Sostenibilidad & ESG",
    "tags": ["Universia", "ESG", "Benchmarking", "Supabase", "React", "Listo para la venta"],
    "readyForSale": True,
    "name": "Test de sostenibilidad universitaria",
    "slogan": "Mide tu sostenibilidad, mejora tu ranking",
    "description": "Sistema de evaluaciÃ³n universitaria en dimensiones Gobernanza, Social y Ambiental (ESG). Dashboard comparativo entre instituciones. React + Node + Supabase.",
    "status": "En lÃ­nea",
    "demoMode": "mostrar",
    "appUrl": "https://bot-sostenibilidad-esg.up.railway.app/",
    "githubUrl": "https://github.com/GovLabSabana/Universia",
    "logo": "assets/projects/sostenibilidad.jpg",
    "videoUrl": "https://drive.google.com/file/d/1GDyYWyFkWJktyAc-a9Alec8xrri4dNEU/view?usp=drive_link",
    "pptUrl": "",
  },
  {
    "segment": "Sector Privado",
    "tipo": "Software",
    "linea": "Sostenibilidad & ESG",
    "tags": ["MetaRed", "Universia", "Agente IA", "RegresiÃ³n", "Data Science", "Listo para la venta"],
    "readyForSale": True,
    "name": "Asistente de agente para MetaRed",
    "slogan": "Resultados de encuestas sobre sostenibilidad y agente de anÃ¡lisis",
    "description": "Herramienta para visualizar resultados de la encuesta de sostenibilidad de MetaRed / Universia, con un agente IA capaz de correr modelos de regresiÃ³n y analÃ­tica descriptiva.",
    "status": "En lÃ­nea",
    "demoMode": "mostrar",
    "appUrl": "https://metaredesg.up.railway.app/",
    "githubUrl": "https://github.com/Juansotag/Metared-by-Universia",
    "logo": "assets/projects/sostenibilidad.jpg",
    "videoUrl": "",
    "pptUrl": "",
  },
  {
    "segment": "Sector PÃºblico",
    "tipo": "Software",
    "linea": "Comunidad & Admisiones",
    "tags": ["Escuela de Gobierno", "MPA", "CV Matching", "RecomendaciÃ³n", "Listo para la venta"],
    "readyForSale": True,
    "name": "MPAChat",
    "slogan": "Tu perfil profesional para el MPA, en minutos",
    "description": "Asistente IA que analiza la hoja de vida de candidatos a la MaestrÃ­a en AdministraciÃ³n PÃºblica (MPA) de la Escuela de Gobierno, recomendando lÃ­neas y perfilando aspirantes.",
    "status": "En lÃ­nea",
    "demoMode": "mostrar",
    "appUrl": "https://mpachat-unisabana.up.railway.app/",
    "githubUrl": "https://github.com/Juansotag/MPAchat",
    "logo": "assets/photos/Aliados/escuela.png",
    "videoUrl": "",
    "pptUrl": "",
  },
  {
    "segment": "Sector PÃºblico",
    "tipo": "Software",
    "linea": "Comunidad & Admisiones",
    "tags": ["Suite Alumni", "Hojas de Vida", "Egresados", "Unisabana", "Listo para la venta"],
    "readyForSale": True,
    "name": "AlumniCV",
    "slogan": "Suite Alumni - Hojas de vida",
    "description": "Herramienta para egresados de la Universidad de La Sabana enfocada en optimizaciÃ³n, formato y gestiÃ³n de hojas de vida profesionales.",
    "status": "En lÃ­nea",
    "demoMode": "mostrar",
    "appUrl": "https://alumnicv.up.railway.app/",
    "githubUrl": "https://github.com/Juansotag/AlumniCV",
    "logo": "assets/Govlab.png",
    "videoUrl": "",
    "pptUrl": "",
  },
  {
    "segment": "Sector PÃºblico",
    "tipo": "Software",
    "linea": "Comunidad & Admisiones",
    "tags": ["Suite Alumni", "AcompaÃ±amiento", "Posgrados", "Chatbot", "Listo para la venta"],
    "readyForSale": True,
    "name": "AlumniChat",
    "slogan": "Chatbot de acompaÃ±amiento para egresados",
    "description": "Chatbot de acompaÃ±amiento y orientaciÃ³n acadÃ©mica/profesional para la comunidad de egresados de la Universidad de La Sabana.",
    "status": "En lÃ­nea",
    "demoMode": "mostrar",
    "appUrl": "https://alumnichat.up.railway.app/",
    "githubUrl": "https://github.com/Juansotag/AlumniChat",
    "logo": "assets/Govlab.png",
    "videoUrl": "",
    "pptUrl": "",
  },
  {
    "segment": "Sector PÃºblico",
    "tipo": "Software",
    "linea": "InnovaciÃ³n & Procesos",
    "tags": ["InnovaciÃ³n Unisabana", "Business Model Canvas", "Propiedad Intelectual", "Listo para la venta"],
    "readyForSale": True,
    "name": "Germina",
    "slogan": "Asistente de innovaciÃ³n con IA",
    "description": "Plataforma para el seguimiento de procesos de innovaciÃ³n, emprendimiento y autorÃ­a intelectual de la Universidad de La Sabana. Genera documentos y apoya en Business Model Canvas.",
    "status": "En lÃ­nea",
    "demoMode": "mostrar",
    "appUrl": "https://germina.up.railway.app/",
    "githubUrl": "https://github.com/Juansotag/germina",
    "logo": "assets/projects/germina.png",
    "videoUrl": "",
    "pptUrl": "",
  },
  {
    "segment": "Sector Privado",
    "tipo": "Software",
    "linea": "Inteligencia Geoespacial",
    "tags": ["Geoespacial", "Vivienda", "Leaflet", "FincaRaÃ­z", "Estratos", "Listo para la venta"],
    "readyForSale": True,
    "name": "Geovivienda",
    "slogan": "Ubica, analiza y decide dÃ³nde vivir",
    "description": "Plataforma inmobiliaria con analÃ­tica geoespacial: scraping de mercado, distancias a Transmilenio/SITP/ciclorutas, estrato promedio a 200m y mapas interactivos con Leaflet.",
    "status": "En lÃ­nea",
    "demoMode": "mostrar",
    "appUrl": "https://geovivienda.up.railway.app/",
    "githubUrl": "https://github.com/Juansotag/Geovivienda-main",
    "logo": "assets/projects/geovivienda-main.png",
    "videoUrl": "https://drive.google.com/file/d/1awsOrJvFAQg4JV4zUP4_4vhpDaucnehM/view?usp=drive_link",
    "pptUrl": "",
  },
  {
    "segment": "Sector Privado",
    "tipo": "Software",
    "linea": "AnalÃ­tica con IA",
    "tags": ["LangChain", "Plotly", "Whisper", "TTS", "Auto-GrÃ¡ficos", "Listo para la venta"],
    "readyForSale": True,
    "name": "Data Copilot",
    "slogan": "PregÃºntale a tus datos con tu propia voz",
    "description": "Asistente de anÃ¡lisis de datos con LangChain + GPT-4 + Whisper. Carga CSV/Excel, genera grÃ¡ficos interactivos con Plotly y responde por voz y texto.",
    "status": "En lÃ­nea",
    "demoMode": "mostrar",
    "appUrl": "https://datacopilot.up.railway.app/",
    "githubUrl": "https://github.com/GovLabSabana/Data_copilot",
    "logo": "assets/Govlab.png",
    "videoUrl": "",
    "pptUrl": "",
  },

  # â”€â”€â”€ DASHBOARDS WEB & PLATAFORMAS (SOFTWARE) â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  {
    "segment": "Sector PÃºblico",
    "tipo": "Software",
    "linea": "Dashboards & AnalÃ­tica",
    "tags": ["INVAMER", "PercepciÃ³n DemocrÃ¡tica", "Tiempo Real", "Filtros DemogrÃ¡ficos", "Listo para la venta"],
    "readyForSale": True,
    "name": "Cuidar la Democracia",
    "slogan": "Visualiza lo que piensa el ciudadano",
    "description": "Dashboard interactivo con datos de encuesta sobre percepciones democrÃ¡ticas en Colombia (INVAMER/GovLab). Filtros sociodemogrÃ¡ficos, mapas y grÃ¡ficos en tiempo real.",
    "status": "En lÃ­nea",
    "demoMode": "mostrar",
    "appUrl": "https://cuidar-la-democracia-production.up.railway.app/",
    "githubUrl": "https://github.com/Juansotag/Cuidar-la-Democracia",
    "logo": "assets/projects/democracia.png",
    "videoUrl": "https://drive.google.com/file/d/1cGZzC2g1HsFeL4M3TziwMUL9o692WI-x/view?usp=drive_link",
    "pptUrl": "",
  },
  {
    "segment": "Sector PÃºblico",
    "tipo": "Software",
    "linea": "Dashboards & AnalÃ­tica",
    "tags": ["FONDECUN", "Cundinamarca", "Sankey", "Mapa de Calor", "Reportes PDF", "Listo para la venta"],
    "readyForSale": True,
    "name": "Data Promce",
    "slogan": "Sigue cada instituciÃ³n, mide cada etapa",
    "description": "Plataforma de seguimiento del programa FONDECUN en IEDs de Cundinamarca. Mapa de calor, Sankey, anÃ¡lisis cualitativo con IA y exportaciÃ³n a PDF/Excel.",
    "status": "En lÃ­nea",
    "demoMode": "mostrar",
    "appUrl": "https://fondecun-production.up.railway.app/",
    "githubUrl": "https://github.com/GovLabSabana/FONDECUN",
    "logo": "assets/projects/datapromce.png",
    "videoUrl": "https://drive.google.com/file/d/1TJcmWLiAGKcxoCspHzYNniXq0ip3uiFw/view?usp=drive_link",
    "pptUrl": "",
  },
  {
    "segment": "Sector PÃºblico",
    "tipo": "Software",
    "linea": "Dashboards & AnalÃ­tica",
    "tags": ["Sabana Centro CÃ³mo Vamos", "Matching Planes", "Scoring IA", "Desarrollo Regional", "Listo para la venta"],
    "readyForSale": True,
    "name": "Sabana Centro Sostenible",
    "slogan": "Conecta proyectos con planes de desarrollo",
    "description": "Matching entre proyectos estratÃ©gicos de Sabana Centro y planes de desarrollo municipales. Scoring semÃ¡ntico con IA de visiÃ³n regional e impacto.",
    "status": "En lÃ­nea",
    "demoMode": "mostrar",
    "appUrl": "https://sabanacentrosostenible.up.railway.app/",
    "githubUrl": "https://github.com/GovLabSabana/SCS_V2",
    "logo": "assets/projects/scsv2.png",
    "videoUrl": "https://drive.google.com/file/d/1WARAZMkb6xri4bO8MIxiPEIVHqOUqbfo/view?usp=drive_link",
    "pptUrl": "",
  },

  # â”€â”€â”€ DASHBOARDS TABLEAU â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  {
    "segment": "Sector PÃºblico",
    "tipo": "Dashboards",
    "linea": "Dashboards & AnalÃ­tica",
    "tags": ["Tableau", "Metas Institucionales", "App MÃ³vil", "Dashboard"],
    "readyForSale": True,
    "name": "SIAG",
    "slogan": "Sigue en tiempo real a tu organizaciÃ³n",
    "description": "Suite de seguimiento de metas institucionales en tiempo real con integraciÃ³n en aplicaciÃ³n web, Android e iOS.",
    "status": "En lÃ­nea",
    "demoMode": "mostrar",
    "appUrl": "https://public.tableau.com/app/profile/juan.sotelo.aguilar/viz/Cardesk-Gestin/Dashboard1",
    "githubUrl": "",
    "logo": "assets/Govlab.png",
    "videoUrl": "https://drive.google.com/file/d/1iZEkSOuXZ5h4kMB0xZBnUOpvovll0vQx/view?usp=drive_link",
    "pptUrl": "",
  },
  {
    "segment": "Sector PÃºblico",
    "tipo": "Dashboards",
    "linea": "Dashboards & AnalÃ­tica",
    "tags": ["Tableau", "Seguridad Ciudadana", "PolicÃ­a Nacional", "Datos Abiertos"],
    "readyForSale": True,
    "name": "Violencia Intrafamiliar en Colombia",
    "slogan": "Monitoreo y tendencias a nivel nacional",
    "description": "Dashboard interactivo con anÃ¡lisis territorial y temporal de denuncias de violencia intrafamiliar en Colombia.",
    "status": "En lÃ­nea",
    "demoMode": "mostrar",
    "appUrl": "https://public.tableau.com/app/profile/juan.sotelo.aguilar/viz/Datos-Polica/Violenciaintrafamiliar",
    "githubUrl": "",
    "logo": "assets/Govlab.png",
    "videoUrl": "",
    "pptUrl": "",
  },
  {
    "segment": "Sector PÃºblico",
    "tipo": "Dashboards",
    "linea": "Dashboards & AnalÃ­tica",
    "tags": ["Tableau", "Salud PÃºblica", "Capacidad Hospitalaria", "Indicadores"],
    "readyForSale": True,
    "name": "Recursos hospitalarios por cada 100.000 habitantes",
    "slogan": "Capacidad del sistema de salud en Colombia",
    "description": "VisualizaciÃ³n comparativa de camas, mÃ©dicos y recursos de atenciÃ³n hospitalaria en los municipios y departamentos del paÃ­s.",
    "status": "En lÃ­nea",
    "demoMode": "mostrar",
    "appUrl": "https://public.tableau.com/app/profile/juan.sotelo.aguilar/viz/Recursoshospitalariosporcada100_00habitantes-2022/Dashboard1",
    "githubUrl": "",
    "logo": "assets/Govlab.png",
    "videoUrl": "",
    "pptUrl": "",
  },
  {
    "segment": "Sector PÃºblico",
    "tipo": "Dashboards",
    "linea": "Dashboards & AnalÃ­tica",
    "tags": ["Tableau", "ADRES", "Afiliaciones Salud", "DemografÃ­a"],
    "readyForSale": True,
    "name": "Registros de la Base Ãšnica de afiliados - Adres - Mayo 2025",
    "slogan": "RadiografÃ­a del aseguramiento en salud",
    "description": "Tablero analÃ­tico de la Base de Datos Ãšnica de Afiliados (BDUA) con perfiles sociodemogrÃ¡ficos y rÃ©gimen de aseguramiento.",
    "status": "En lÃ­nea",
    "demoMode": "mostrar",
    "appUrl": "https://public.tableau.com/app/profile/juan.sotelo.aguilar/viz/RegistrosdelaBasedeDatosnicadeAfiliados-ADRES-Mayo2025/Perfilesdelosafiliados",
    "githubUrl": "",
    "logo": "assets/Govlab.png",
    "videoUrl": "",
    "pptUrl": "",
  },
  {
    "segment": "Sector PÃºblico",
    "tipo": "Dashboards",
    "linea": "Dashboards & AnalÃ­tica",
    "tags": ["Tableau", "DemografÃ­a", "Envejecimiento", "PolÃ­ticas Poblacionales"],
    "readyForSale": True,
    "name": "Envejecimiento poblacional en Colombia por Sexo y Ãrea",
    "slogan": "TransiciÃ³n demogrÃ¡fica y territorio",
    "description": "Historia interactiva sobre las curvas de envejecimiento y pirÃ¡mides poblacionales urbanas y rurales en Colombia.",
    "status": "En lÃ­nea",
    "demoMode": "mostrar",
    "appUrl": "https://public.tableau.com/app/profile/juan.sotelo.aguilar/viz/EnvejecimientopoblacionalenColombiaporSexoyArea/Historia1",
    "githubUrl": "",
    "logo": "assets/Govlab.png",
    "videoUrl": "",
    "pptUrl": "",
  },
  {
    "segment": "Sector PÃºblico",
    "tipo": "Dashboards",
    "linea": "Dashboards & AnalÃ­tica",
    "tags": ["Tableau", "Seguridad", "ExtorsiÃ³n", "Series Temporales"],
    "readyForSale": True,
    "name": "Panorama de la ExtorsiÃ³n en Colombia (2010-2024)",
    "slogan": "EvoluciÃ³n de un delito de alto impacto",
    "description": "AnÃ¡lisis longitudinal de denuncias, modalidades y focos territoriales del delito de extorsiÃ³n a lo largo de 14 aÃ±os.",
    "status": "En lÃ­nea",
    "demoMode": "mostrar",
    "appUrl": "https://public.tableau.com/app/profile/juan.sotelo.aguilar/viz/PanoramadelaextorsinenColombia2010-2024/Dashboard1",
    "githubUrl": "",
    "logo": "assets/Govlab.png",
    "videoUrl": "",
    "pptUrl": "",
  },
  {
    "segment": "Sector PÃºblico",
    "tipo": "Dashboards",
    "linea": "Dashboards & AnalÃ­tica",
    "tags": ["Tableau", "Justicia", "ProtecciÃ³n", "Datos Policiales"],
    "readyForSale": True,
    "name": "Delitos Sexuales en Colombia",
    "slogan": "Evidencia para la protecciÃ³n ciudadana",
    "description": "Mapeo y caracterizaciÃ³n de reportes de delitos sexuales para el diseÃ±o de polÃ­ticas de prevenciÃ³n y justicia focalizada.",
    "status": "En lÃ­nea",
    "demoMode": "mostrar",
    "appUrl": "https://public.tableau.com/app/profile/juan.sotelo.aguilar/viz/DelitossexualesenColombia_17300861605130/Dashboard1",
    "githubUrl": "",
    "logo": "assets/Govlab.png",
    "videoUrl": "",
    "pptUrl": "",
  },
  {
    "segment": "Sector PÃºblico",
    "tipo": "Dashboards",
    "linea": "Dashboards & AnalÃ­tica",
    "tags": ["Tableau", "DemografÃ­a", "Cuidado", "Adulto Mayor"],
    "readyForSale": True,
    "name": "El Panorama del envejecimiento poblacional en Colombia",
    "slogan": "Retos de la longevidad y servicios sociales",
    "description": "Dashboard integral con indicadores de dependencia, Ã­ndice de envejecimiento y distribuciÃ³n departamental.",
    "status": "En lÃ­nea",
    "demoMode": "mostrar",
    "appUrl": "https://public.tableau.com/app/profile/juan.sotelo.aguilar/viz/ElpanoramadelenvejecimientopoblacionalenColombia/Dashboard1",
    "githubUrl": "",
    "logo": "assets/Govlab.png",
    "videoUrl": "",
    "pptUrl": "",
  },
  {
    "segment": "Sector PÃºblico",
    "tipo": "Dashboards",
    "linea": "Dashboards & AnalÃ­tica",
    "tags": ["Tableau", "Salud Mental", "EpidemiologÃ­a", "PrevenciÃ³n"],
    "readyForSale": True,
    "name": "Suicidios en Colombia 2023-2024",
    "slogan": "Datos para la salud mental pÃºblica",
    "description": "Monitoreo descriptivo y espacial de eventos de salud mental y suicidio reportados en el territorio nacional.",
    "status": "En lÃ­nea",
    "demoMode": "mostrar",
    "appUrl": "https://public.tableau.com/app/profile/juan.sotelo.aguilar/viz/Suicidios-2023-2024/Dashboard12",
    "githubUrl": "",
    "logo": "assets/Govlab.png",
    "videoUrl": "",
    "pptUrl": "",
  },
  {
    "segment": "Sector PÃºblico",
    "tipo": "Dashboards",
    "linea": "Dashboards & AnalÃ­tica",
    "tags": ["Tableau", "NUSE 123", "BogotÃ¡", "UPZ", "Emergencias"],
    "readyForSale": True,
    "name": "Llamadas totales al NUSE/123 por UPZ en BogotÃ¡",
    "slogan": "Llamadas de emergencia a escala barrial",
    "description": "DistribuciÃ³n geogrÃ¡fica por Unidades de Planeamiento Zonal (UPZ) de llamadas atendidas por la lÃ­nea Ãºnica de emergencias de BogotÃ¡.",
    "status": "En lÃ­nea",
    "demoMode": "mostrar",
    "appUrl": "https://public.tableau.com/app/profile/juan.sotelo.aguilar/viz/LlamadastotalesalNUSEporUPZ/Vistadistrital",
    "githubUrl": "",
    "logo": "assets/Govlab.png",
    "videoUrl": "",
    "pptUrl": "",
  },
  {
    "segment": "Sector PÃºblico",
    "tipo": "Dashboards",
    "linea": "Dashboards & AnalÃ­tica",
    "tags": ["Tableau", "Agro", "Precios Arroz", "Forecasting", "Modelos Predictivos"],
    "readyForSale": True,
    "name": "Precios y productividad del arroz - Forecasting",
    "slogan": "PronÃ³stico de precios y cosechas agrÃ­colas",
    "description": "Modelo predictivo de series temporales de precios mayoristas y rendimiento por hectÃ¡rea en el sector arrocero.",
    "status": "En lÃ­nea",
    "demoMode": "mostrar",
    "appUrl": "https://public.tableau.com/app/profile/juan.sotelo.aguilar/viz/Dashboardarroz/Dashboard1",
    "githubUrl": "",
    "logo": "assets/Govlab.png",
    "videoUrl": "",
    "pptUrl": "",
  },
  {
    "segment": "Sector PÃºblico",
    "tipo": "Dashboards",
    "linea": "Dashboards & AnalÃ­tica",
    "tags": ["Tableau", "Movilidad", "Siniestralidad Vial", "Forecasting", "BogotÃ¡"],
    "readyForSale": True,
    "name": "Siniestralidad vial en BogotÃ¡ - Forecasting",
    "slogan": "Modelos predictivos de accidentalidad vial",
    "description": "PredicciÃ³n de eventos de siniestros viales en corredores viales clave de BogotÃ¡ mediante tÃ©cnicas de forecasting.",
    "status": "En lÃ­nea",
    "demoMode": "mostrar",
    "appUrl": "https://public.tableau.com/app/profile/juan.sotelo.aguilar/viz/Siniestralidadvial-2019-2023V2-forecasting/SiniestralidadvialenBogotD_C_-Modelopredictivo-2019-2023",
    "githubUrl": "",
    "logo": "assets/Govlab.png",
    "videoUrl": "",
    "pptUrl": "",
  },
  {
    "segment": "Sector PÃºblico",
    "tipo": "Dashboards",
    "linea": "Dashboards & AnalÃ­tica",
    "tags": ["Tableau", "Movilidad", "Accidentes", "BogotÃ¡"],
    "readyForSale": True,
    "name": "Siniestralidad vial en BogotÃ¡ - Siniestros",
    "slogan": "Registro y causas de accidentes de trÃ¡nsito",
    "description": "VisualizaciÃ³n histÃ³rica 2019-2023 de siniestros viales clasificados por tipo de vehÃ­culo, horario y localidad.",
    "status": "En lÃ­nea",
    "demoMode": "mostrar",
    "appUrl": "https://public.tableau.com/app/profile/juan.sotelo.aguilar/viz/Siniestralidadvial-2019-2023V2-Siniestros/SiniestralidadvialenBogotD_C_-2019-2023",
    "githubUrl": "",
    "logo": "assets/Govlab.png",
    "videoUrl": "",
    "pptUrl": "",
  },
  {
    "segment": "Sector PÃºblico",
    "tipo": "Dashboards",
    "linea": "Dashboards & AnalÃ­tica",
    "tags": ["Tableau", "Movilidad", "VÃ­ctimas", "Seguridad Vial"],
    "readyForSale": True,
    "name": "Siniestralidad vial en BogotÃ¡ - VÃ­ctimas",
    "slogan": "Perfil de actores viales y lesionados",
    "description": "Tablero enfocado en peatones, ciclistas y motociclistas afectados en eventos viales en la capital.",
    "status": "En lÃ­nea",
    "demoMode": "mostrar",
    "appUrl": "https://public.tableau.com/app/profile/juan.sotelo.aguilar/viz/Siniestralidadvial-2019-2023V2-Vctimas/VctimasdelasiniestralidadvialenBogotD_C_-2019-2023",
    "githubUrl": "",
    "logo": "assets/Govlab.png",
    "videoUrl": "",
    "pptUrl": "",
  },
  {
    "segment": "Sector PÃºblico",
    "tipo": "Dashboards",
    "linea": "Dashboards & AnalÃ­tica",
    "tags": ["Tableau", "GeoanalÃ­tica", "Mapas de Calor", "Puntos CrÃ­ticos"],
    "readyForSale": True,
    "name": "Siniestralidad vial en BogotÃ¡ - AnÃ¡lisis espacial",
    "slogan": "Puntos crÃ­ticos e intersecciones de alto riesgo",
    "description": "AnÃ¡lisis de concentraciÃ³n geoespacial de accidentes e identificaciÃ³n de tramos viales prioritarios para intervenciÃ³n.",
    "status": "En lÃ­nea",
    "demoMode": "mostrar",
    "appUrl": "https://public.tableau.com/app/profile/juan.sotelo.aguilar/viz/Siniestralidadvial-2019-2023V2-Anlisisespacial/SiniestralidadvialenBogotD_C_-2019-2023-Anlisisespacial",
    "githubUrl": "",
    "logo": "assets/Govlab.png",
    "videoUrl": "",
    "pptUrl": "",
  },
  {
    "segment": "Sector PÃºblico",
    "tipo": "Dashboards",
    "linea": "Dashboards & AnalÃ­tica",
    "tags": ["Tableau", "Forecasting", "LÃ­nea 123", "UPZ", "Capacidad Operativa"],
    "readyForSale": True,
    "name": "Llamadas totales al NUSE/123 por UPZ en BogotÃ¡ - Forecasting",
    "slogan": "PronÃ³stico de demanda de atenciÃ³n de emergencias",
    "description": "Modelos predictivos de volumen de llamadas al NUSE por UPZ para optimizar el despliegue de patrullas y ambulancias.",
    "status": "En lÃ­nea",
    "demoMode": "mostrar",
    "appUrl": "https://public.tableau.com/app/profile/juan.sotelo.aguilar/viz/LlamadasalNUSEporUPZ/VistaporUPZ",
    "githubUrl": "",
    "logo": "assets/Govlab.png",
    "videoUrl": "",
    "pptUrl": "",
  },

  # â”€â”€â”€ ESTUDIOS & ANÃLISIS DE DATOS â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  {
    "segment": "Sector PÃºblico",
    "tipo": "Estudios & AnÃ¡lisis de datos",
    "linea": "Salud & GeoanalÃ­tica",
    "tags": ["Machine Learning", "ClÃ­nica Unisabana", "ARIMA", "Prophet", "Pacientes NO-EPS"],
    "readyForSale": False,
    "name": "AnÃ¡lisis ClÃ­nica Universidad de la Sabana",
    "slogan": "Anticipa la demanda, optimiza los recursos",
    "description": "Sistema ML de series de tiempo (ARIMA y Prophet) con MAE inferior a 10% para pronosticar el nÃºmero de pacientes NO-EPS y la facturaciÃ³n semanal de la ClÃ­nica.",
    "status": "Activo",
    "demoMode": "ppt",
    "appUrl": "",
    "githubUrl": "https://github.com/GovLabSabana/ModeloClinica",
    "logo": "assets/photos/Aliados/clinica.png",
    "videoUrl": "",
    "pptUrl": "assets/decks/modelo_clÃ­nica.pdf",
  },
  {
    "segment": "Sector PÃºblico",
    "tipo": "Estudios & AnÃ¡lisis de datos",
    "linea": "Salud & GeoanalÃ­tica",
    "tags": ["GeoanalÃ­tica", "ClÃ­nica Unisabana", "Pacientes Potenciales", "Inteligencia Territorial"],
    "readyForSale": False,
    "name": "GeoanÃ¡lisis ClÃ­nica Universidad de la Sabana",
    "slogan": "Encuentra al paciente antes de que llegue",
    "description": "AnÃ¡lisis predictivo geoespacial de la ubicaciÃ³n y patrones de desplazamiento de potenciales usuarios de servicios de salud privados en Sabana Centro.",
    "status": "Activo",
    "demoMode": "ppt",
    "appUrl": "",
    "githubUrl": "",
    "logo": "assets/photos/Aliados/clinica.png",
    "videoUrl": "https://drive.google.com/file/d/1KdjNdT396zr8c9nPjeeX_xjB-99c_8Ka/view?usp=drive_link",
    "pptUrl": "assets/decks/modelo_geo_clÃ­nica.pdf",
  },
  {
    "segment": "Sector PÃºblico",
    "tipo": "Estudios & AnÃ¡lisis de datos",
    "linea": "PolÃ­ticas PÃºblicas & Territorio",
    "tags": ["OSZ", "ZipaquirÃ¡", "Indicadores Sociales", "Observatorio Social"],
    "readyForSale": False,
    "name": "Observatorio Social de ZipaquirÃ¡ - OSZ",
    "slogan": "AlcaldÃ­a de ZipaquirÃ¡",
    "description": "Desarrollo y diseÃ±o del primer observatorio social de la RegiÃ³n Sabana Centro para el seguimiento riguroso de indicadores sociales y bienestar.",
    "status": "Activo",
    "demoMode": "ppt",
    "appUrl": "",
    "githubUrl": "",
    "logo": "assets/projects/osz.png",
    "videoUrl": "",
    "pptUrl": "assets/decks/Observatorio Social de ZipaquirÃ¡.pdf",
  },
  {
    "segment": "Sector PÃºblico",
    "tipo": "Estudios & AnÃ¡lisis de datos",
    "linea": "Electoral & PronÃ³stico",
    "tags": ["PronÃ³stico Electoral", "Redes Sociales", "MetodologÃ­a ELA-NOM", "Error < 9%"],
    "readyForSale": False,
    "name": "ELA-NOM",
    "slogan": "Pronostica elecciones con redes sociales",
    "description": "AplicaciÃ³n de una novedosa metodologÃ­a de pronÃ³stico electoral (ELA-NOM) basada en minerÃ­a de redes sociales con error predictivo inferior al 9%.",
    "status": "Activo",
    "demoMode": "mostrar",
    "appUrl": "",
    "githubUrl": "https://github.com/Juansotag/ELA_NOM",
    "logo": "assets/Govlab.png",
    "videoUrl": "",
    "pptUrl": "",
  },

  # â”€â”€â”€ EDUCACIÃ“N (FORMACIÃ“N PROFESIONAL EN IA) â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  {
    "segment": "Transversal",
    "tipo": "EducaciÃ³n",
    "linea": "EducaciÃ³n & FormaciÃ³n",
    "tags": ["Doctorado", "Posgrado", "InvestigaciÃ³n IA", "Sector PÃºblico"],
    "readyForSale": True,
    "name": "Doctorado en IA",
    "slogan": "Investiga el futuro, lidera el cambio",
    "description": "Programa doctoral de investigaciÃ³n de vanguardia en inteligencia artificial, enfocado en soluciones para el sector pÃºblico y formulaciÃ³n de polÃ­ticas basadas en evidencia.",
    "status": "Activo",
    "demoMode": "mostrar",
    "appUrl": "https://www.unisabana.edu.co/programas/posgrados/doctorado-en-inteligencia-artificial",
    "githubUrl": "",
    "logo": "assets/Govlab.png",
    "videoUrl": "",
    "pptUrl": "",
  },
  {
    "segment": "Transversal",
    "tipo": "EducaciÃ³n",
    "linea": "EducaciÃ³n & FormaciÃ³n",
    "tags": ["MaestrÃ­a", "Posgrado", "AnalÃ­tica Aplicada", "Toma de Decisiones"],
    "readyForSale": True,
    "name": "MaestrÃ­a en IA",
    "slogan": "Domina la IA, transforma tu sector",
    "description": "Programa de posgrado en inteligencia artificial y analÃ­tica aplicada con Ã©nfasis en gobierno digital, polÃ­tica pÃºblica y gestiÃ³n estratÃ©gica organizacional.",
    "status": "Activo",
    "demoMode": "mostrar",
    "appUrl": "https://www.unisabana.edu.co/programas/posgrados/maestria-en-analitica-aplicada",
    "githubUrl": "",
    "logo": "assets/Govlab.png",
    "videoUrl": "",
    "pptUrl": "",
  },
  {
    "segment": "Transversal",
    "tipo": "EducaciÃ³n",
    "linea": "EducaciÃ³n & FormaciÃ³n",
    "tags": ["Pregrado", "Ciencia de Datos", "Modelado MatemÃ¡tico", "Unisabana"],
    "readyForSale": True,
    "name": "Pregrado en IA",
    "slogan": "Aprende IA desde la raÃ­z",
    "description": "Programa de pregrado en Ciencia de Datos e Inteligencia Artificial de la Universidad de La Sabana. FormaciÃ³n integral en modelos, algoritmos y aplicaciones reales.",
    "status": "Activo",
    "demoMode": "mostrar",
    "appUrl": "https://www.unisabana.edu.co/programas/pregrados/ciencia-de-datos",
    "githubUrl": "",
    "logo": "assets/Govlab.png",
    "videoUrl": "",
    "pptUrl": "",
  },
  {
    "segment": "Transversal",
    "tipo": "EducaciÃ³n",
    "linea": "EducaciÃ³n & FormaciÃ³n",
    "tags": ["Bootcamps", "EducaciÃ³n Continua", "FormaciÃ³n Ejecutiva", "PrÃ¡ctica"],
    "readyForSale": True,
    "name": "Bootcamps en IA",
    "slogan": "Habilidades reales, en tiempo rÃ©cord",
    "description": "Programas tÃ©cnicos intensivos de capacitaciÃ³n en IA para profesionales y directivos del sector pÃºblico y privado, orientados a casos de uso inmediatos.",
    "status": "Activo",
    "demoMode": "mostrar",
    "appUrl": "https://www.unisabana.edu.co/programas/educacion-continua/curso/curso-experto-en-inteligencia-artificial-para-profesionales-innovadores",
    "githubUrl": "",
    "logo": "assets/Govlab.png",
    "videoUrl": "",
    "pptUrl": "",
  },
]

with open("products_data.json", "w", encoding="utf-8") as f:
    json.dump(products, f, ensure_ascii=False, indent=2)
print("products_data.json updated without emojis.")

