const PRODUCTS = [
  {
    segment: 'Sector Público',
    type: 'Dashboards & Analítica de datos',
    name: 'Cuidar la Democracia',
    slogan: 'Visualiza lo que piensa el ciudadano',
    description: 'Dashboard interactivo con datos de encuesta sobre percepciones democráticas en Colombia (INVAMER/GovLab). Filtros sociodemográficos, mapas y gráficos en tiempo real.',
    status: 'En línea',
    demoMode: 'mostrar',
    appUrl: 'https://cuidar-la-democracia-production.up.railway.app/',
    githubUrl: 'https://github.com/Juansotag/Cuidar-la-Democracia',
    logo: 'assets/projects/democracia.png',
    videoUrl: 'https://drive.google.com/file/d/1cGZzC2g1HsFeL4M3TziwMUL9o692WI-x/view?usp=drive_link',
    pptUrl: '',
  },
  {
    segment: 'Sector Público',
    type: 'Dashboards & Analítica de datos',
    name: 'Data Promce',
    slogan: 'Sigue cada institución, mide cada etapa',
    description: 'Plataforma de seguimiento del programa FONDECUN en IEDs de Cundinamarca. Mapa de calor, Sankey, análisis cualitativo con IA y exportación a PDF/Excel.',
    status: 'En línea',
    demoMode: 'mostrar',
    appUrl: '',
    githubUrl: 'https://github.com/GovLabSabana/FONDECUN',
    logo: 'assets/projects/datapromce.png',
    videoUrl: 'https://drive.google.com/file/d/1TJcmWLiAGKcxoCspHzYNniXq0ip3uiFw/view?usp=drive_link',
    pptUrl: '',
  },
  {
    segment: 'Sector Público',
    type: 'Asistentes de Voz con IA',
    name: 'AlcaldesaIA',
    slogan: 'Pregúntale al municipio, él te responde',
    description: 'Asistente de voz en tiempo real sobre el Plan de Desarrollo de Cajicá 2024-2027. OpenAI Realtime API + LiveKit + WebRTC.',
    status: 'En mantenimiento',
    demoMode: 'mostrar',
    appUrl: 'https://asistente-virtual-cajica.up.railway.app/',
    githubUrl: 'https://github.com/GovLabSabana/cajica',
    logo: 'assets/projects/alcaldesa.png',
    videoUrl: '',
    pptUrl: '',
  },
  {
    segment: 'Sector Público',
    type: 'Simuladores & Comunicación Política',
    name: 'PitchLab360',
    slogan: 'Analiza el discurso, mejora el mensaje',
    description: 'Análisis de discurso político con Claude (Anthropic). Perfil comunicativo, análisis emocional, stakeholders, encuadres narrativos y potencial digital.',
    status: 'En línea',
    demoMode: 'mostrar',
    appUrl: 'https://pitchlab360-production.up.railway.app/',
    githubUrl: 'https://github.com/Juansotag/PitchLab360',
    logo: 'assets/projects/pitchlab360.jpg',
    videoUrl: 'https://drive.google.com/file/d/1bYLxn5TCm_Hwq6DG7-u7UYui5N5szYUm/view?usp=drive_link',
    pptUrl: '',
  },
  {
    segment: 'Sector Público',
    type: 'Simuladores & Comunicación Política',
    name: 'Polycheck',
    slogan: 'Verifica en tiempo real, no después',
    description: 'Extensión de Chrome para fact-checking en tiempo real sobre videos de YouTube. GPT-4o + Gemini + Google Search. Análisis forense del discurso político.',
    status: 'En línea',
    demoMode: 'mostrar',
    appUrl: '',
    githubUrl: 'https://github.com/Juansotag/Polycheck',
    logo: 'assets/projects/polycheck.jpg',
    videoUrl: 'https://drive.google.com/file/d/111GwtqEWziIQFwi8BxMgQhiR6ZT-o2YW/view?usp=drive_link',
    pptUrl: '',
  },
  {
    segment: 'Sector Público',
    type: 'Simuladores & Comunicación Política',
    name: 'GovTest',
    slogan: 'Descubre tu candidato con datos',
    description: 'Test de afinidad política por dilemas de política pública. 16 preguntas, 14 candidatos 2026, 7 arquetipos de votante. Tarjeta viral descargable.',
    status: 'En línea',
    demoMode: 'mostrar',
    appUrl: 'https://convergencia-electoral.up.railway.app/',
    githubUrl: 'https://github.com/GovLabSabana/test-dilema',
    logo: 'assets/projects/govtest.jpg',
    videoUrl: 'https://drive.google.com/file/d/1B1RWm_HmN4HlHjiIzlDzh58FqfGpITkX/view?usp=drive_link',
    pptUrl: '',
  },
  {
    segment: 'Sector Público',
    type: 'Simuladores & Comunicación Política',
    name: 'Test 9 Ejes',
    slogan: 'Tu posición en 9 ejes, tu candidato en un clic',
    description: 'Test de afinidad política por 9 ejes ideológicos. Algoritmo euclidiano, ranking de candidatos, perfil personalizado y persistencia en Supabase.',
    status: 'En línea',
    demoMode: 'mostrar',
    appUrl: 'https://test9ejes.up.railway.app/',
    githubUrl: 'https://github.com/GovLabSabana/Test_9ejes',
    logo: 'assets/projects/test9ejes.jpg',
    videoUrl: 'https://drive.google.com/file/d/1IpEH495QROwq8k3VdkaD52tjbJKX68Iv/view?usp=drive_link',
    pptUrl: '',
  },
  {
    segment: 'Sector Público',
    type: 'Simuladores & Comunicación Política',
    name: 'Test 9 Ejes Colombia',
    slogan: '50 preguntas, un perfil ideológico',
    description: 'Versión extendida del test con 50 preguntas coyunturales sobre Colombia. Modo oscuro glassmorphism, compartir en alta resolución, datos anónimos en Supabase.',
    status: 'En línea',
    demoMode: 'mostrar',
    appUrl: 'https://test9col.up.railway.app/',
    githubUrl: 'https://github.com/GovLabSabana/Test_9ejesColombia',
    logo: 'assets/projects/test9ejes.jpg',
    videoUrl: 'https://drive.google.com/file/d/1gXzEi2ZNE4daXYBnidmccgcgkWj2Db84/view?usp=drive_link',
    pptUrl: '',
  },
  {
    segment: 'Sector Público',
    type: 'Dashboards & Analítica de datos',
    name: 'Sabana Centro Sostenible',
    slogan: 'Conecta proyectos con planes de desarrollo',
    description: 'Matching entre proyectos estratégicos de Sabana Centro y planes de desarrollo municipales. Scoring semántico con IA: especificidad, visión regional e impacto.',
    status: 'En línea',
    demoMode: 'mostrar',
    appUrl: 'https://sabanacentrosostenible.up.railway.app/',
    githubUrl: 'https://github.com/GovLabSabana/SCS_V2',
    logo: 'assets/projects/scsv2.png',
    videoUrl: 'https://drive.google.com/file/d/1WARAZMkb6xri4bO8MIxiPEIVHqOUqbfo/view?usp=drive_link',
    pptUrl: '',
  },
  {
    segment: 'Sector Privado',
    type: 'Asistentes de Voz con IA',
    name: 'ConvergenceLab',
    slogan: 'Habla con la universidad, ella te escucha',
    description: 'Asistente de voz en tiempo real para el Convergence Lab de la Unisabana. LiveKit Agents + OpenAI Realtime API + Silero VAD. Frontend Next.js.',
    status: 'En línea',
    demoMode: 'mostrar',
    appUrl: 'https://convergencelab.up.railway.app/',
    githubUrl: 'https://github.com/GovLabSabana/ConvergenceLAb',
    logo: 'assets/projects/convergence.png',
    videoUrl: 'https://drive.google.com/file/d/1r-HPmA_JXTUB45rQpJKJ7RzEZwTaReno/view?usp=drive_link',
    pptUrl: '',
  },
  {
    segment: 'Sector Privado',
    type: 'Asistentes de Voz con IA',
    name: 'Gober Santander',
    slogan: 'Un asistente público para cada ciudadano',
    description: 'Asistente de voz conversacional para el sector público. Procesamiento de PQRS, visualización de datos, interfaz para funcionarios. OpenAI Realtime + LiveKit.',
    status: 'En línea',
    demoMode: 'mostrar',
    appUrl: 'https://santander-production.up.railway.app/',
    githubUrl: 'https://github.com/GovLabSabana/Santander',
    logo: 'assets/projects/gober.png',
    videoUrl: 'https://drive.google.com/file/d/1JZj-tysFp6FlbX3NeH5Y4pINnr_1dNzg/view?usp=drive_link',
    pptUrl: '',
  },
  {
    segment: 'Sector Privado',
    type: 'ChatBots & Automatización',
    name: 'ExportaCheck',
    slogan: '¿Listo para exportar? Descúbrelo hoy',
    description: 'Plataforma con termómetro interactivo que evalúa el nivel de preparación exportadora de empresas. Diagnóstico por dimensiones con IA. Next.js + FastAPI + Supabase.',
    status: 'En línea',
    demoMode: 'mostrar',
    appUrl: 'https://exporta-facil-bot-production-e49c.up.railway.app/',
    githubUrl: 'https://github.com/GovLabSabana/TermoExportador',
    logo: 'assets/projects/exportacheck.jpg',
    videoUrl: 'https://drive.google.com/file/d/1X7QuSOTr0gCKC7rLTdSzvLsoyWHbyw_i/view?usp=drive_link',
    pptUrl: '',
  },
  {
    segment: 'Sector Privado',
    type: 'ChatBots & Automatización',
    name: 'Test de sostenibilidad universitaria',
    slogan: 'Mide tu sostenibilidad, mejora tu ranking',
    description: 'Sistema de evaluación universitaria en dimensiones Gobernanza, Social y Ambiental (ESG). Dashboard comparativo entre instituciones. React + Node + Supabase.',
    status: 'En línea',
    demoMode: 'mostrar',
    appUrl: 'https://bot-sostenibilidad-esg.up.railway.app/',
    githubUrl: 'https://github.com/GovLabSabana/Universia',
    logo: 'assets/projects/sostenibilidad.jpg',
    videoUrl: 'https://drive.google.com/file/d/1GDyYWyFkWJktyAc-a9Alec8xrri4dNEU/view?usp=drive_link',
    pptUrl: '',
  },
  {
    segment: 'Sector Privado',
    type: 'Inteligencia Geoespacial',
    name: 'Geovivienda',
    slogan: 'Ubica, analiza y decide dónde vivir',
    description: 'Plataforma inmobiliaria con análisis geoespacial: scraping de FincaRaíz, distancias a Transmilenio/SITP/ciclorutas, estrato promedio 200m, mapa interactivo con Leaflet.',
    status: 'En línea',
    demoMode: 'mostrar',
    appUrl: 'https://geovivienda-production.up.railway.app/',
    githubUrl: 'https://github.com/GovLabSabana/Geovivienda',
    logo: 'assets/projects/geovivienda.png',
    videoUrl: 'https://drive.google.com/file/d/1awsOrJvFAQg4JV4zUP4_4vhpDaucnehM/view?usp=drive_link',
    pptUrl: '',
  },
  {
    segment: 'Transversal',
    type: 'Formación Profesional en IA',
    name: 'Bootcamps en IA',
    slogan: 'Habilidades reales, en tiempo récord',
    description: 'Programas de formación técnica intensiva en IA para profesionales y equipos. Orientados a aplicaciones prácticas en distintos sectores.',
    status: 'Activo',
    demoMode: 'mostrar',
    appUrl: 'https://www.unisabana.edu.co/programas/educacion-continua/curso/curso-experto-en-inteligencia-artificial-para-profesionales-innovadores',
    githubUrl: '',
    logo: 'assets/Govlab.png',
    videoUrl: '',
    pptUrl: '',
  },
  {
    segment: 'Sector Público',
    type: 'Dashboards & Analítica de datos',
    name: 'Análisis Clínica Universidad de la Sabana',
    slogan: 'Anticipa la demanda, optimiza los recursos',
    description: 'Sistema ML para identificar y predecir el número de pacientes NO-EPS y su facturación semanal en la Clínica Universidad de la Sabana.',
    status: 'Activo',
    demoMode: 'ppt',
    appUrl: '',
    githubUrl: '',
    logo: 'assets/photos/Aliados/clinica.png',
    videoUrl: '',
    pptUrl: 'assets/decks/modelo_clínica.pdf',
  },
  {
    segment: 'Sector Público',
    type: 'Inteligencia Geoespacial',
    name: 'Geoanálisis Clínica Universidad de la Sabana',
    slogan: 'Encuentra al paciente antes de que llegue',
    description: 'Análisis predictivo geoespacial de la ubicación de potenciales clientes NO-EPS de la Clínica Universidad de la Sabana.',
    status: 'Activo',
    demoMode: 'ppt',
    appUrl: '',
    githubUrl: '',
    logo: 'assets/photos/Aliados/clinica.png',
    videoUrl: 'https://drive.google.com/file/d/1KdjNdT396zr8c9nPjeeX_xjB-99c_8Ka/view?usp=drive_link',
    pptUrl: 'assets/decks/modelo_geo_clínica.pdf',
  },
  {
    segment: 'Sector Público',
    type: 'ChatBots & Automatización',
    name: 'CAResponde',
    slogan: 'De la PQRS al ciudadano en segundos',
    description: 'Asistente en texto para la CAR Cundinamarca: recibe, categoriza, visualiza y responde PQRS automáticamente con IA.',
    status: 'En línea',
    demoMode: 'mostrar',
    appUrl: 'https://car-pqrs-production.up.railway.app/',
    githubUrl: 'https://github.com/GovLabSabana/CAR-pqrs',
    logo: 'assets/projects/caresponde.png',
    videoUrl: 'https://drive.google.com/file/d/1Z9kNrQxgHan2YKVw9oRovIzGJfLPp86j/view?usp=drive_link',
    pptUrl: '',
  },
  {
    segment: 'Sector Privado',
    type: 'Dashboards & Analítica de datos',
    name: 'HassApp',
    slogan: 'Del campo al mundo, con datos',
    description: 'Plataforma integral para gestión de producción, cosecha, insumos y exportación de aguacate Hass. FastAPI + React + MySQL + AWS S3.',
    status: 'En línea',
    demoMode: 'mostrar',
    appUrl: 'https://heartfelt-success-production-8486.up.railway.app/',
    githubUrl: 'https://github.com/GovLabSabana/HassApp',
    logo: 'assets/projects/hassapp.png',
    videoUrl: 'https://drive.google.com/file/d/1WMHMOz0j_DHamcykskRayQAUyCyPpryw/view?usp=drive_link',
    pptUrl: '',
  },
  {
    segment: 'Sector Público',
    type: 'Dashboards & Analítica de datos',
    name: 'Barranquilla',
    slogan: 'Predice la criminalidad, protege la ciudad',
    description: 'App web para subir, analizar y predecir eventos de criminalidad y convivencia ciudadana. Diseñada para el Observatorio de Criminalidad de Barranquilla.',
    status: 'En línea',
    demoMode: 'mostrar',
    appUrl: 'https://barranquilla-production.up.railway.app/',
    githubUrl: 'https://github.com/GovLabSabana/Barranquilla',
    logo: 'assets/Govlab.png',
    videoUrl: 'https://drive.google.com/file/d/1X7_dn5FwxNv9XvoflFxJrNYQPzxmr8DJ/view?usp=drive_link',
    pptUrl: '',
  },
  {
    segment: 'Sector Público',
    type: 'ChatBots & Automatización',
    name: 'AlcaldIA',
    slogan: 'El Plan de Desarrollo en tus manos',
    description: 'Asistente RAG sobre el Plan de Desarrollo Distrital de Bogotá. Búsqueda semántica con FAISS + GPT-4o. Respuestas por objetivo, programa y presupuesto.',
    status: 'En línea',
    demoMode: 'mostrar',
    appUrl: 'https://alcadia.up.railway.app/',
    githubUrl: 'https://github.com/GovLabSabana/AlcaldIA',
    logo: 'assets/Govlab.png',
    videoUrl: 'https://drive.google.com/file/d/1rfDiEcx6BD2r3HDHG5GSUVze8Bd8O9ww/view?usp=drive_link',
    pptUrl: '',
  },
  {
    segment: 'Sector Público',
    type: 'ChatBots & Automatización',
    name: 'PoliciApp-Eco',
    slogan: 'La ley ambiental en campo',
    description: 'Asistente IA de legislación ambiental colombiana para la Policía Ambiental y Carabineros. Cubre pesca, flora, fauna, minería y recursos hídricos.',
    status: 'En mantenimiento',
    demoMode: 'mostrar',
    appUrl: '',
    githubUrl: 'https://github.com/GovLabSabana/PoliciApp-Eco2',
    logo: 'assets/Govlab.png',
    videoUrl: '',
    pptUrl: '',
  },
  {
    segment: 'Sector Público',
    type: 'ChatBots & Automatización',
    name: 'LegisCheck',
    slogan: 'Dos versiones, un solo vistazo',
    description: 'Comparación inteligente de documentos legislativos. Diff semántico con GPT-4, línea de tiempo con hitos y reportes descargables en PDF.',
    status: 'En mantenimiento',
    demoMode: 'mostrar',
    appUrl: '',
    githubUrl: 'https://github.com/GovLabSabana/Paralelo',
    logo: 'assets/projects/Legischeck.png',
    videoUrl: '',
    pptUrl: '',
  },
  {
    segment: 'Sector Privado',
    type: 'Asistentes de Voz con IA',
    name: 'Alocandidato',
    slogan: 'La campaña que llama, nunca la que cansa',
    description: 'Video de muestra con Dapta para llamadas de voz automatizadas a ciudadanos con preguntas sobre candidatos políticos.',
    status: 'En línea',
    demoMode: 'mostrar',
    appUrl: '',
    githubUrl: '',
    logo: 'assets/projects/alocandidato.jpg',
    videoUrl: 'https://drive.google.com/file/d/1bOY7U-cqev5172oxBTSLvazsdPdM2hTT/view?usp=drive_link',
    pptUrl: '',
  },
  {
    segment: 'Sector Privado',
    type: 'ChatBots & Automatización',
    name: 'Data Copilot',
    slogan: 'Pregúntale a tus datos con tu propia voz',
    description: 'Asistente de análisis de datos con LangChain + GPT-4 + Whisper. Acepta CSV/Excel, genera gráficos interactivos con Plotly, responde por texto y por voz (TTS).',
    status: 'En línea',
    demoMode: 'mostrar',
    appUrl: 'https://datacopilot.up.railway.app/',
    githubUrl: 'https://github.com/GovLabSabana/Data_copilot',
    logo: 'assets/Govlab.png',
    videoUrl: '',
    pptUrl: '',
  },
  {
    segment: 'Sector Privado',
    type: 'Gestión Documental con IA',
    name: 'NotariaDoc',
    slogan: 'El borrador perfecto, sin esperas',
    description: 'MVP para construir borradores de escrituras, análisis de cumplimiento y chat IA para notarías.',
    status: 'En línea',
    demoMode: 'mostrar',
    appUrl: 'https://notariadoc-production.up.railway.app/',
    githubUrl: 'https://github.com/GovLabSabana/NotariaDoc',
    logo: 'assets/Govlab.png',
    videoUrl: 'https://drive.google.com/file/d/1BNngISeVJ6rFuEdgpbrmGFCxAjOLwgFE/view?usp=drive_link',
    pptUrl: '',
  },
  {
    segment: 'Sector Privado',
    type: 'Gestión Documental con IA',
    name: 'NotariaIQ',
    slogan: 'Control total de la notaría en un panel',
    description: 'Panel de control para notarías: seguimiento de usuarios, tiempos de espera, ingresos, egresos, análisis descriptivo y pronóstico.',
    status: 'En línea',
    demoMode: 'mostrar',
    appUrl: 'https://notariaiq-production.up.railway.app/',
    githubUrl: 'https://github.com/GovLabSabana/NotariaIQ',
    logo: 'assets/Govlab.png',
    videoUrl: 'https://drive.google.com/file/d/19wx_KXzy9Byorjwu40xK5E3ymxglD_aO/view?usp=drive_link',
    pptUrl: '',
  },
  {
    segment: 'Sector Privado',
    type: 'Gestión Documental con IA',
    name: 'Radica Notaría',
    slogan: 'Radica, revisa y aprueba sin papel',
    description: 'Suite de automatización documental para la Notaría Segunda de Zipaquirá. Formulario para constructoras + panel de digitadora con flujo de aprobación de escrituras.',
    status: 'En línea',
    demoMode: 'mostrar',
    appUrl: 'https://radicanotaria-production.up.railway.app/',
    githubUrl: 'https://github.com/GovLabSabana/Radica_notaria',
    logo: 'assets/Govlab.png',
    videoUrl: 'https://drive.google.com/file/d/1cmOw8OCh4UhW1YzWrMBpbsMvaZZjnrSV/view?usp=drive_link',
    pptUrl: '',
  },
  {
    segment: 'Sector Público',
    type: 'Dashboards & Analítica de datos',
    name: 'SIAG',
    slogan: 'Sigue en tiempo real a tu organización',
    description: 'Suite de seguimiento de metas institucionales en tiempo real con aplicación web, Android y IOS',
    status: 'En línea',
    demoMode: 'mostrar',
    appUrl: 'https://public.tableau.com/app/profile/juan.sotelo.aguilar/viz/Cardesk-Gestin/Dashboard1',
    githubUrl: '',
    logo: 'assets/Govlab.png',
    videoUrl: 'https://drive.google.com/file/d/1iZEkSOuXZ5h4kMB0xZBnUOpvovll0vQx/view?usp=drive_link',
    pptUrl: '',
  },
  {
    segment: 'Sector Público',
    type: 'Dashboards & Analítica de datos',
    name: 'Violencia Intrafamiliar en Colombia',
    slogan: '',
    description: '',
    status: 'En línea',
    demoMode: 'mostrar',
    appUrl: 'https://public.tableau.com/app/profile/juan.sotelo.aguilar/viz/Datos-Polica/Violenciaintrafamiliar',
    githubUrl: '',
    logo: 'assets/Govlab.png',
    videoUrl: '',
    pptUrl: '',
  },
  {
    segment: 'Sector Público',
    type: 'Dashboards & Analítica de datos',
    name: 'Recursos hospitalarios por cada 100.000 habitantes',
    slogan: '',
    description: '',
    status: 'En línea',
    demoMode: 'mostrar',
    appUrl: 'https://public.tableau.com/app/profile/juan.sotelo.aguilar/viz/Recursoshospitalariosporcada100_00habitantes-2022/Dashboard1',
    githubUrl: '',
    logo: 'assets/Govlab.png',
    videoUrl: '',
    pptUrl: '',
  },
  {
    segment: 'Sector Público',
    type: 'Dashboards & Analítica de datos',
    name: 'Registros de la Base Única de afiliados - Adres - Mayo 2025',
    slogan: '',
    description: '',
    status: 'En línea',
    demoMode: 'mostrar',
    appUrl: 'https://public.tableau.com/app/profile/juan.sotelo.aguilar/viz/RegistrosdelaBasedeDatosnicadeAfiliados-ADRES-Mayo2025/Perfilesdelosafiliados',
    githubUrl: '',
    logo: 'assets/Govlab.png',
    videoUrl: '',
    pptUrl: '',
  },
  {
    segment: 'Sector Público',
    type: 'Dashboards & Analítica de datos',
    name: 'Envejecimiento poblacional en Colombia por Sexo y Área',
    slogan: '',
    description: '',
    status: 'En línea',
    demoMode: 'mostrar',
    appUrl: 'https://public.tableau.com/app/profile/juan.sotelo.aguilar/viz/EnvejecimientopoblacionalenColombiaporSexoyArea/Historia1',
    githubUrl: '',
    logo: 'assets/Govlab.png',
    videoUrl: '',
    pptUrl: '',
  },
  {
    segment: 'Sector Público',
    type: 'Dashboards & Analítica de datos',
    name: 'Panorama de la Extorsión en Colombia (2010-2024)',
    slogan: '',
    description: '',
    status: 'En línea',
    demoMode: 'mostrar',
    appUrl: 'https://public.tableau.com/app/profile/juan.sotelo.aguilar/viz/PanoramadelaextorsinenColombia2010-2024/Dashboard1',
    githubUrl: '',
    logo: 'assets/Govlab.png',
    videoUrl: '',
    pptUrl: '',
  },
  {
    segment: 'Sector Público',
    type: 'Dashboards & Analítica de datos',
    name: 'Delitos Sexuales en Colombia',
    slogan: '',
    description: '',
    status: 'En línea',
    demoMode: 'mostrar',
    appUrl: 'https://public.tableau.com/app/profile/juan.sotelo.aguilar/viz/DelitossexualesenColombia_17300861605130/Dashboard1',
    githubUrl: '',
    logo: 'assets/Govlab.png',
    videoUrl: '',
    pptUrl: '',
  },
  {
    segment: 'Sector Público',
    type: 'Dashboards & Analítica de datos',
    name: 'El Panorama del envejecimiento poblacional en Colombia',
    slogan: '',
    description: '',
    status: 'En línea',
    demoMode: 'mostrar',
    appUrl: 'https://public.tableau.com/app/profile/juan.sotelo.aguilar/viz/ElpanoramadelenvejecimientopoblacionalenColombia/Dashboard1',
    githubUrl: '',
    logo: 'assets/Govlab.png',
    videoUrl: '',
    pptUrl: '',
  },
  {
    segment: 'Sector Público',
    type: 'Dashboards & Analítica de datos',
    name: 'Suicidios en Colombia 2023-2024',
    slogan: '',
    description: '',
    status: 'En línea',
    demoMode: 'mostrar',
    appUrl: 'https://public.tableau.com/app/profile/juan.sotelo.aguilar/viz/Suicidios-2023-2024/Dashboard12',
    githubUrl: '',
    logo: 'assets/Govlab.png',
    videoUrl: '',
    pptUrl: '',
  },
  {
    segment: 'Sector Público',
    type: 'Dashboards & Analítica de datos',
    name: 'Llamadas totales al NUSE/123 por UPZ en Bogotá',
    slogan: '',
    description: '',
    status: 'En línea',
    demoMode: 'mostrar',
    appUrl: 'https://public.tableau.com/app/profile/juan.sotelo.aguilar/viz/LlamadastotalesalNUSEporUPZ/Vistadistrital',
    githubUrl: '',
    logo: 'assets/Govlab.png',
    videoUrl: '',
    pptUrl: '',
  },
  {
    segment: 'Sector Público',
    type: 'Dashboards & Analítica de datos',
    name: 'Precios y productividad del arroz - Forecasting',
    slogan: '',
    description: '',
    status: 'En línea',
    demoMode: 'mostrar',
    appUrl: 'https://public.tableau.com/app/profile/juan.sotelo.aguilar/viz/Dashboardarroz/Dashboard1',
    githubUrl: '',
    logo: 'assets/Govlab.png',
    videoUrl: '',
    pptUrl: '',
  },
  {
    segment: 'Sector Público',
    type: 'Dashboards & Analítica de datos',
    name: 'Sinestralidad vial en Bogotá - Forecasting',
    slogan: '',
    description: '',
    status: 'En línea',
    demoMode: 'mostrar',
    appUrl: 'https://public.tableau.com/app/profile/juan.sotelo.aguilar/viz/Siniestralidadvial-2019-2023V2-forecasting/SiniestralidadvialenBogotD_C_-Modelopredictivo-2019-2023',
    githubUrl: '',
    logo: 'assets/Govlab.png',
    videoUrl: '',
    pptUrl: '',
  },
  {
    segment: 'Sector Público',
    type: 'Dashboards & Analítica de datos',
    name: 'Sinestralidad vial en Bogotá - Siniestros',
    slogan: '',
    description: '',
    status: 'En línea',
    demoMode: 'mostrar',
    appUrl: 'https://public.tableau.com/app/profile/juan.sotelo.aguilar/viz/Siniestralidadvial-2019-2023V2-Siniestros/SiniestralidadvialenBogotD_C_-2019-2023',
    githubUrl: '',
    logo: 'assets/Govlab.png',
    videoUrl: '',
    pptUrl: '',
  },
  {
    segment: 'Sector Público',
    type: 'Dashboards & Analítica de datos',
    name: 'Sinestralidad vial en Bogotá - Víctimas',
    slogan: '',
    description: '',
    status: 'En línea',
    demoMode: 'mostrar',
    appUrl: 'https://public.tableau.com/app/profile/juan.sotelo.aguilar/viz/Siniestralidadvial-2019-2023V2-Vctimas/VctimasdelasiniestralidadvialenBogotD_C_-2019-2023',
    githubUrl: '',
    logo: 'assets/Govlab.png',
    videoUrl: '',
    pptUrl: '',
  },
  {
    segment: 'Sector Público',
    type: 'Dashboards & Analítica de datos',
    name: 'Sinestralidad vial en Bogotá - Análisis espacial',
    slogan: '',
    description: '',
    status: 'En línea',
    demoMode: 'mostrar',
    appUrl: 'https://public.tableau.com/app/profile/juan.sotelo.aguilar/viz/Siniestralidadvial-2019-2023V2-Anlisisespacial/SiniestralidadvialenBogotD_C_-2019-2023-Anlisisespacial',
    githubUrl: '',
    logo: 'assets/Govlab.png',
    videoUrl: '',
    pptUrl: '',
  },
  {
    segment: 'Sector Público',
    type: 'Dashboards & Analítica de datos',
    name: 'Llamadas totales al NUSE/123 por UPZ en Bogotá - Forecasting',
    slogan: '',
    description: '',
    status: 'En línea',
    demoMode: 'mostrar',
    appUrl: 'https://public.tableau.com/app/profile/juan.sotelo.aguilar/viz/LlamadasalNUSEporUPZ/VistaporUPZ',
    githubUrl: '',
    logo: 'assets/Govlab.png',
    videoUrl: '',
    pptUrl: '',
  },
  {
    segment: 'Sector Privado',
    type: 'ChatBots & Automatización',
    name: 'Asistente de agente para MetaRed',
    slogan: 'Resultados de encuestas sobre sostenibilidad y agente de análisis',
    description: 'Herramienta que permite ver los resultados de la encuesta sobre políticas de sostenibilidad en instituciones de educación superior de la red iberoamericana de universidades. Tiene un chat con funciones de agente que permite correr modelos de regresión y hacer analítica descriptiva.',
    status: 'En línea',
    demoMode: 'mostrar',
    appUrl: '',
    githubUrl: '',
    logo: 'assets/projects/sostenibilidad.jpg',
    videoUrl: '',
    pptUrl: '',
  },
  {
    segment: 'Sector Público',
    type: 'Dashboards & Analítica de datos',
    name: 'Observatorio Social de Zipaquirá - OSZ',
    slogan: 'Alcaldía de Zipaquirá',
    description: 'Desarrollo del primer observatorio social de la Región Sabana Centro, para el seguimiento de indicadores sociales.',
    status: 'Activo',
    demoMode: 'ppt',
    appUrl: '',
    githubUrl: '',
    logo: 'assets/projects/osz.png',
    videoUrl: '',
    pptUrl: 'assets/decks/Observatorio Social de Zipaquirá.pdf',
  },
  {
    segment: 'Sector Público',
    type: 'ChatBots & Automatización',
    name: 'MPAChat',
    slogan: 'Tu perfil profesional para el MPA, en minutos',
    description: 'Chat con IA que analiza el CV de los interesados en la Maestría en Administración Pública (MPA / Masters in Public Administration) de la Escuela de Gobierno de la Unisabana. Genera recomendaciones personalizadas, construye un perfil del candidato y guarda su hoja de vida e información.',
    status: 'En línea',
    demoMode: 'mostrar',
    appUrl: 'https://mpachat-unisabana.up.railway.app/',
    githubUrl: 'https://github.com/Juansotag/MPAchat',
    logo: 'assets/photos/Aliados/escuela.png',
    videoUrl: '',
    pptUrl: '',
  },
  {
    segment: 'Sector Público',
    type: 'Gestión Documental con IA',
    name: 'AlumniCV',
    slogan: 'Suite Alumni - Hojas de vida',
    description: 'Herramienta para egresados de la Universidad de La Sabana enfocada en construcción y gestión de hojas de vida.',
    status: 'En línea',
    demoMode: 'mostrar',
    appUrl: 'https://alumnicv.up.railway.app/',
    githubUrl: 'https://github.com/Juansotag/AlumniCV',
    logo: 'assets/Govlab.png',
    videoUrl: '',
    pptUrl: '',
  },
  {
    segment: 'Sector Público',
    type: 'ChatBots & Automatización',
    name: 'AlumniChat',
    slogan: 'Chatbot de acompañamiento para egresados',
    description: 'Chatbot de acompañamiento para egresados de la Universidad de La Sabana, parte de la suite Alumni.',
    status: 'En línea',
    demoMode: 'mostrar',
    appUrl: 'https://alumnichat.up.railway.app/',
    githubUrl: 'https://github.com/Juansotag/AlumniChat',
    logo: 'assets/Govlab.png',
    videoUrl: '',
    pptUrl: '',
  },
  {
    segment: 'Sector Público',
    type: 'ChatBots & Automatización',
    name: 'Germina',
    slogan: 'Asistente de innovación con IA',
    description: 'Asistente de innovación con IA para el proceso de innovación del GovLab, Universidad de La Sabana.',
    status: 'En línea',
    demoMode: 'mostrar',
    appUrl: 'https://germina.up.railway.app/',
    githubUrl: 'https://github.com/Juansotag/germina',
    logo: 'assets/projects/germina.png',
    videoUrl: '',
    pptUrl: '',
  },
  {
    segment: 'Sector Privado',
    type: 'Inteligencia Geoespacial',
    name: 'Geovivienda-main',
    slogan: 'Analítica geoespacial de vivienda',
    description: 'Analítica geoespacial de vivienda en arriendo para apoyar decisiones de política pública y planeación urbana.',
    status: 'En línea',
    demoMode: 'mostrar',
    appUrl: 'https://geovivienda.up.railway.app/',
    githubUrl: 'https://github.com/Juansotag/Geovivienda-main',
    logo: 'assets/projects/geovivienda-main.png',
    videoUrl: '',
    pptUrl: '',
  },
  {
    segment: 'Sector Público',
    type: 'Simuladores & Comunicación Política',
    name: 'Avatar_entrenamiento',
    slogan: 'Avatar conversacional para entrenamiento',
    description: 'Avatar conversacional para entrenamiento; reconstrucción del proyecto TTS_Avatar (candidatos presidenciales).',
    status: 'En línea',
    demoMode: 'mostrar',
    appUrl: 'https://avatarentrenamiento.up.railway.app/',
    githubUrl: 'https://github.com/Juansotag/Avatar_entrenamiento',
    logo: 'assets/Govlab.png',
    videoUrl: '',
    pptUrl: '',
  },
  {
    segment: 'Sector Público',
    type: 'Gestión Documental con IA',
    name: 'Newsletter-Proyección-social',
    slogan: 'Generador y envío de newsletter',
    description: 'Generador/envío de newsletter para la Dirección de Proyección Social y Co-Creación de la Universidad de La Sabana.',
    status: 'En línea',
    demoMode: 'mostrar',
    appUrl: 'https://newsletter-pse.up.railway.app/',
    githubUrl: 'https://github.com/Juansotag/Newsletter---Proyecci-n-social',
    logo: 'assets/Govlab.png',
    videoUrl: '',
    pptUrl: '',
  },
  {
    segment: 'Sector Público',
    type: 'Simuladores & Comunicación Política',
    name: 'ELA-NOM',
    slogan: 'Pronostica elecciones con redes sociales',
    description: 'Aplicación de una nueva metodología para el pronóstico electoral llamado ELA-NOM que usa redes sociales para pronosticar resultados electorales con un error inferior al 9%.',
    status: 'En desarrollo',
    demoMode: 'mostrar',
    appUrl: '',
    githubUrl: 'https://github.com/Juansotag/ELA_NOM',
    logo: 'assets/Govlab.png',
    videoUrl: '',
    pptUrl: '',
  },
  {
    segment: 'Sector Público',
    type: 'Asistentes de Voz con IA',
    name: 'Govi',
    slogan: 'El GovLab te habla, tú lo escuchas',
    description: 'Asistente basado en voz para la consulta y acercamiento al cliente del Laboratorio de Gobierno de la Universidad de la Sabana.',
    status: 'En mantenimiento',
    demoMode: 'mostrar',
    appUrl: '',
    githubUrl: 'https://github.com/GovLabSabana/Govi2',
    logo: 'assets/Govlab.png',
    videoUrl: '',
    pptUrl: '',
  },
  {
    segment: 'Sector Privado',
    type: 'Simuladores & Comunicación Política',
    name: 'PitchLab Med',
    slogan: 'Practica tu pitch médico con estándares INVIMA',
    description: 'Plataforma para la práctica de pitch médicos con medidas de rigurosidad INVIMA. Entrenamiento conversacional para profesionales de la salud.',
    status: 'En línea',
    demoMode: 'mostrar',
    appUrl: 'https://pitchlab-med.up.railway.app/',
    githubUrl: 'https://github.com/Juansotag/PitchLab360-comercial',
    logo: 'assets/Govlab.png',
    videoUrl: '',
    pptUrl: '',
  },
  {
    segment: 'Sector Público',
    type: 'ChatBots & Automatización',
    name: 'PoliciaAmbiental',
    slogan: 'Jurisprudencia ambiental en campo',
    description: 'Chatbot para facilitar conocimientos de jurisprudencia para la policía ambiental de Colombia. Cobertura de normativa sobre flora, fauna, recursos hídricos y ecosistemas.',
    status: 'En mantenimiento',
    demoMode: 'mostrar',
    appUrl: '',
    githubUrl: 'https://github.com/GovLabSabana/Policia_ambiental',
    logo: 'assets/Govlab.png',
    videoUrl: '',
    pptUrl: '',
  },
  {
    segment: 'Sector Público',
    type: 'Gestión Documental con IA',
    name: 'Resume Expedientes',
    slogan: 'Decisiones de alto gobierno en segundos',
    description: 'Herramienta para resumir expedientes directivos y dirigir decisiones de alto gobierno con IA. Extracción de puntos clave y síntesis ejecutiva.',
    status: 'En línea',
    demoMode: 'mostrar',
    appUrl: 'https://expedientes.up.railway.app/',
    githubUrl: 'https://github.com/Juansotag/resumidor-expedientes',
    logo: 'assets/Govlab.png',
    videoUrl: '',
    pptUrl: '',
  },
];
