# update_portfolio_tags.py
import json

updated_products = [
  {
    "segment": "Sector Público",
    "tipo": "Software",
    "linea": "Línea PitchLab",
    "tags": [
      "Gobierno & Asuntos Públicos",
      "Consultoría Política",
      "Comunicación Estratégica",
      "IA Generativa",
      "Listo para propuesta"
    ],
    "readyForSale": True,
    "name": "PitchLab360",
    "slogan": "Analiza el discurso, mejora el mensaje",
    "description": "Análisis de discurso político con Claude (Anthropic). Perfil comunicativo, análisis emocional, stakeholders, encuadres narrativos y potencial digital. Probado con candidatos presidenciales.",
    "status": "En línea",
    "demoMode": "mostrar",
    "appUrl": "https://pitchlab360-production.up.railway.app/",
    "githubUrl": "https://github.com/Juansotag/PitchLab360",
    "logo": "assets/projects/pitchlab360.jpg",
    "videoUrl": "https://drive.google.com/file/d/1bYLxn5TCm_Hwq6DG7-u7UYui5N5szYUm/view?usp=drive_link",
    "pptUrl": ""
  },
  {
    "segment": "Sector Público",
    "tipo": "Software",
    "linea": "Línea PitchLab",
    "tags": [
      "Periodismo & Medios",
      "Sector Público",
      "Consultoría Política",
      "Fact-checking",
      "Listo para propuesta"
    ],
    "readyForSale": True,
    "name": "Polycheck",
    "slogan": "Verifica en tiempo real, no después",
    "description": "Extensión de Chrome para fact-checking en tiempo real sobre videos de YouTube y directos. Integración GPT-4o + Gemini + Google Search para análisis forense del discurso.",
    "status": "En línea",
    "demoMode": "mostrar",
    "appUrl": "",
    "githubUrl": "https://github.com/Juansotag/Polycheck",
    "logo": "assets/projects/polycheck.jpg",
    "videoUrl": "https://drive.google.com/file/d/111GwtqEWziIQFwi8BxMgQhiR6ZT-o2YW/view?usp=drive_link",
    "pptUrl": ""
  },
  {
    "segment": "Sector Privado",
    "tipo": "Software",
    "linea": "Línea PitchLab",
    "tags": [
      "Salud & Farma",
      "Dispositivos Médicos",
      "Regulación Sanitaria",
      "INVIMA",
      "Listo para propuesta"
    ],
    "readyForSale": True,
    "name": "PitchLab Med",
    "slogan": "Practica tu pitch médico con estándares INVIMA",
    "description": "Plataforma para la práctica y evaluación de pitch médicos con medidas de rigurosidad INVIMA. Entrenamiento conversacional para profesionales e industria farmacéutica.",
    "status": "En línea",
    "demoMode": "mostrar",
    "appUrl": "https://pitchlab-med.up.railway.app/",
    "githubUrl": "https://github.com/Juansotag/PitchLab360-comercial",
    "logo": "assets/projects/pitchlab360.jpg",
    "videoUrl": "",
    "pptUrl": ""
  },
  {
    "segment": "Sector Privado",
    "tipo": "Software",
    "linea": "Línea PitchLab",
    "tags": [
      "Corporativo & Ventas",
      "Recursos Humanos & Capacitación",
      "Negociación B2B",
      "LiveKit",
      "Listo para propuesta"
    ],
    "readyForSale": True,
    "name": "PitchLab Entrenamiento",
    "slogan": "Entrena tu discurso con un avatar interactivo",
    "description": "Avatar interactivo en tiempo real para entrenamiento en ventas y negociación corporativa. Análisis automático de fluidez, muletillas, persuasión y lenguaje no verbal.",
    "status": "En línea",
    "demoMode": "mostrar",
    "appUrl": "https://pitchlab-entrenamiento.up.railway.app/",
    "githubUrl": "https://github.com/Juansotag/PitchLab_LiveKit",
    "logo": "assets/projects/pitchlab360.jpg",
    "videoUrl": "",
    "pptUrl": ""
  },
  {
    "segment": "Sector Público",
    "tipo": "Software",
    "linea": "Línea GovTest & Opinión",
    "tags": [
      "Consultoría Política",
      "Medios & Opinión Pública",
      "Sector Público",
      "Elecciones 2026",
      "Listo para propuesta"
    ],
    "readyForSale": True,
    "name": "GovTest",
    "slogan": "Descubre tu afinidad política con datos reales",
    "description": "Test de afinidad política para las elecciones colombianas de 2026. Comparación de posturas ciudadanas con programas de gobierno y declaraciones de candidatos.",
    "status": "En línea",
    "demoMode": "mostrar",
    "appUrl": "https://govtest-production.up.railway.app/",
    "githubUrl": "https://github.com/Juansotag/GovTest",
    "logo": "assets/projects/govtest.png",
    "videoUrl": "https://drive.google.com/file/d/1Xl2Nlq7l44o50H15gNlBqL4894xG960X/view?usp=drive_link",
    "pptUrl": ""
  },
  {
    "segment": "Sector Público",
    "tipo": "Software",
    "linea": "Línea GovTest & Opinión",
    "tags": [
      "Consultoría Política",
      "Opinión Pública",
      "Sector Público",
      "Investigación Social",
      "Listo para propuesta"
    ],
    "readyForSale": True,
    "name": "Test 9 Ejes",
    "slogan": "Mapea tu pensamiento político en 9 dimensiones",
    "description": "Evaluación ideológica multidimensional basada en el modelo de 9 ejes políticos. Visualización interactiva del posicionamiento frente a diferentes corrientes de pensamiento.",
    "status": "En línea",
    "demoMode": "mostrar",
    "appUrl": "https://9-axes-test-production.up.railway.app/",
    "githubUrl": "https://github.com/Juansotag/9-Axes-Test",
    "logo": "assets/projects/govtest.png",
    "videoUrl": "https://drive.google.com/file/d/1gI264fE0jHk0H4T6d-K10nZ9F0h0y-G1/view?usp=drive_link",
    "pptUrl": ""
  },
  {
    "segment": "Sector Público",
    "tipo": "Software",
    "linea": "Línea GovTest & Opinión",
    "tags": [
      "Consultoría Política",
      "Opinión Pública",
      "Educación Cívica",
      "Sector Público",
      "Listo para propuesta"
    ],
    "readyForSale": True,
    "name": "Test 9 Ejes Colombia",
    "slogan": "El test de 9 ejes adaptado a la realidad colombiana",
    "description": "Versión contextualizada del test de 9 ejes para el escenario político colombiano. Preguntas sobre coyuntura nacional, paz, economía, medio ambiente y modelo de Estado.",
    "status": "En línea",
    "demoMode": "mostrar",
    "appUrl": "https://9-ejes-colombia-production.up.railway.app/",
    "githubUrl": "https://github.com/Juansotag/9-Ejes-Colombia",
    "logo": "assets/projects/govtest.png",
    "videoUrl": "https://drive.google.com/file/d/144V973Zp4z7F1wM69V-qR4yQ2vM2y2g3/view?usp=drive_link",
    "pptUrl": ""
  },
  {
    "segment": "Sector Público",
    "tipo": "Software",
    "linea": "Asistentes de Voz",
    "tags": [
      "Gobiernos Locales & Municipios",
      "Sector Público",
      "Atención Ciudadana",
      "Asistentes de Voz"
    ],
    "readyForSale": False,
    "name": "AlcaldesaIA",
    "slogan": "Habla con la alcaldía, en tiempo real",
    "description": "Asistente de voz conversacional para la Alcaldía de Cajicá. Permite a los ciudadanos consultar trámites, servicios y estado de solicitudes hablando directamente por voz.",
    "status": "En línea",
    "demoMode": "mostrar",
    "appUrl": "https://alcaldesa-ia-production.up.railway.app/",
    "githubUrl": "https://github.com/Juansotag/AlcaldesaIA",
    "logo": "assets/projects/alcaldesa.png",
    "videoUrl": "https://drive.google.com/file/d/1Xl2Nlq7l44o50H15gNlBqL4894xG960X/view?usp=drive_link",
    "pptUrl": ""
  },
  {
    "segment": "Sector Público",
    "tipo": "Software",
    "linea": "Asistentes de Voz",
    "tags": [
      "Gobiernos Departamentales",
      "Sector Público",
      "Atención Ciudadana",
      "PQRS",
      "Listo para propuesta"
    ],
    "readyForSale": True,
    "name": "Gober Santander",
    "slogan": "Atención ciudadana inteligente para Santander",
    "description": "Agente de voz para la Gobernación de Santander. Recepción y radicación de PQRS, orientación sobre oferta institucional y seguimiento de trámites departamentales.",
    "status": "En línea",
    "demoMode": "mostrar",
    "appUrl": "https://gober-santander-production.up.railway.app/",
    "githubUrl": "https://github.com/Juansotag/Gober-Santander",
    "logo": "assets/projects/santander.png",
    "videoUrl": "https://drive.google.com/file/d/1n23w0-wXo7R-M7oE3r2z4k4v5X3t5Y5Z/view?usp=drive_link",
    "pptUrl": ""
  },
  {
    "segment": "Sector Público",
    "tipo": "Software",
    "linea": "Asistentes de Voz",
    "tags": [
      "Sector Público",
      "Atención Ciudadana",
      "Gobierno Digital",
      "Asistentes de Voz"
    ],
    "readyForSale": False,
    "name": "Govi",
    "slogan": "El asistente inteligente del GovLab",
    "description": "Asistente virtual conversacional del GovLab. Guía a visitantes por el portafolio de proyectos, líneas de investigación, capacidades técnicas y opciones de colaboración.",
    "status": "En línea",
    "demoMode": "mostrar",
    "appUrl": "https://govi-production.up.railway.app/",
    "githubUrl": "https://github.com/Juansotag/Govi",
    "logo": "assets/projects/govi.png",
    "videoUrl": "",
    "pptUrl": ""
  },
  {
    "segment": "Sector Privado",
    "tipo": "Software",
    "linea": "Asistentes de Voz",
    "tags": [
      "Telecomunicaciones & Tech",
      "Atención al Cliente",
      "Innovación Digital",
      "LiveKit",
      "Listo para propuesta"
    ],
    "readyForSale": True,
    "name": "ConvergenceLab",
    "slogan": "La frontera de la interacción por voz con IA",
    "description": "Plataforma de experimentación e investigación en tecnologías de voz en tiempo real. Integración de modelos de latencia ultrabaja, síntesis vocal adaptativa y análisis emocional.",
    "status": "En línea",
    "demoMode": "mostrar",
    "appUrl": "https://convergencelab-production.up.railway.app/",
    "githubUrl": "https://github.com/Juansotag/ConvergenceLab",
    "logo": "assets/projects/convergencelab.png",
    "videoUrl": "",
    "pptUrl": ""
  },
  {
    "segment": "Sector Público",
    "tipo": "Software",
    "linea": "Asistentes de Voz",
    "tags": [
      "Campañas & Consultoría Política",
      "Asuntos Públicos",
      "Encuestas & Sondeos",
      "Outbound Calls",
      "Listo para propuesta"
    ],
    "readyForSale": True,
    "name": "Alocandidato",
    "slogan": "Campañas de voz automatizadas a escala",
    "description": "Sistema de llamadas automatizadas bidireccionales con IA para campañas electorales e investigación de opinión pública. Encuestas dinámicas y mensajes personalizados masivos.",
    "status": "En línea",
    "demoMode": "mostrar",
    "appUrl": "https://alocandidato-production.up.railway.app/",
    "githubUrl": "https://github.com/Juansotag/Alocandidato",
    "logo": "assets/projects/alocandidato.jpg",
    "videoUrl": "",
    "pptUrl": ""
  },
  {
    "segment": "Sector Privado",
    "tipo": "Software",
    "linea": "Agroindustria & Exportación",
    "tags": [
      "Agroindustria",
      "Comercio Exterior & Exportación",
      "Cadena de Suministro",
      "Aguacate Hass",
      "Listo para propuesta"
    ],
    "readyForSale": True,
    "name": "HassApp",
    "slogan": "Trazabilidad inteligente para el aguacate Hass",
    "description": "Plataforma para Corpohass que gestiona la trazabilidad completa del aguacate Hass colombiano desde el predio productor hasta el puerto de destino. Monitoreo de calidad y certificaciones.",
    "status": "En línea",
    "demoMode": "mostrar",
    "appUrl": "https://hassapp-production.up.railway.app/",
    "githubUrl": "https://github.com/Juansotag/HassApp",
    "logo": "assets/projects/hassapp.png",
    "videoUrl": "https://drive.google.com/file/d/1Xl2Nlq7l44o50H15gNlBqL4894xG960X/view?usp=drive_link",
    "pptUrl": ""
  },
  {
    "segment": "Sector Privado",
    "tipo": "Software",
    "linea": "Agroindustria & Exportación",
    "tags": [
      "Agroindustria",
      "Comercio Exterior",
      "Diagnóstico Exportador",
      "Corpohass",
      "Listo para propuesta"
    ],
    "readyForSale": True,
    "name": "ExportaCheck",
    "slogan": "Diagnóstico de madurez exportadora con IA",
    "description": "Herramienta de autodiagnóstico para productores y exportadores agrícolas. Evalúa cumplimiento fitosanitario, normativo y logístico para mercados de EE.UU., Europa y Asia.",
    "status": "En línea",
    "demoMode": "mostrar",
    "appUrl": "https://exportacheck-production.up.railway.app/",
    "githubUrl": "https://github.com/Juansotag/ExportaCheck",
    "logo": "assets/projects/exportacheck.png",
    "videoUrl": "",
    "pptUrl": ""
  },
  {
    "segment": "Sector Privado",
    "tipo": "Software",
    "linea": "Notarías & Documental",
    "tags": [
      "Sector Notarial & Legal",
      "Servicios Jurídicos",
      "Gestión Documental",
      "Borradores de Escrituras",
      "Listo para propuesta"
    ],
    "readyForSale": True,
    "name": "NotariaDoc",
    "slogan": "Borradores de escrituras con IA en minutos",
    "description": "Asistente para despachos notariales que redacta borradores de escrituras públicas a partir de minutas, contratos y documentos soporte. Validación automática de requisitos legales.",
    "status": "En línea",
    "demoMode": "mostrar",
    "appUrl": "https://notariadoc-production.up.railway.app/",
    "githubUrl": "https://github.com/Juansotag/NotariaDoc",
    "logo": "assets/projects/notariadoc.png",
    "videoUrl": "https://drive.google.com/file/d/1Xl2Nlq7l44o50H15gNlBqL4894xG960X/view?usp=drive_link",
    "pptUrl": ""
  },
  {
    "segment": "Sector Privado",
    "tipo": "Software",
    "linea": "Notarías & Documental",
    "tags": [
      "Sector Notarial & Legal",
      "Operaciones & Eficiencia",
      "Business Intelligence",
      "Tiempos de Espera",
      "Listo para propuesta"
    ],
    "readyForSale": True,
    "name": "NotariaIQ",
    "slogan": "Control operativo y predicción de demanda notarial",
    "description": "Panel de control y analítica para notarías. Predicción de tiempos de espera, gestión de turnos, distribución de carga laboral entre funcionarios y métricas de satisfacción.",
    "status": "En línea",
    "demoMode": "mostrar",
    "appUrl": "https://notariaiq-production.up.railway.app/",
    "githubUrl": "https://github.com/Juansotag/NotariaIQ",
    "logo": "assets/projects/notariaiq.png",
    "videoUrl": "",
    "pptUrl": ""
  },
  {
    "segment": "Sector Privado",
    "tipo": "Software",
    "linea": "Notarías & Documental",
    "tags": [
      "Sector Notarial & Legal",
      "Construcción & Fiduciario",
      "Inmobiliario",
      "Flujo de Aprobación",
      "Listo para propuesta"
    ],
    "readyForSale": True,
    "name": "Radica Notaría",
    "slogan": "Ventanilla digital entre constructoras y notarías",
    "description": "Plataforma de radicación digital que conecta constructoras, fiduciarias y notarías. Gestión de paquetes documentales para escrituración masiva de proyectos inmobiliarios.",
    "status": "En línea",
    "demoMode": "mostrar",
    "appUrl": "https://radicanotaria-production.up.railway.app/",
    "githubUrl": "https://github.com/Juansotag/RadicaNotaria",
    "logo": "assets/projects/radicanotaria.png",
    "videoUrl": "",
    "pptUrl": ""
  },
  {
    "segment": "Sector Público",
    "tipo": "Software",
    "linea": "Proyección Social & Directiva",
    "tags": [
      "Rama Judicial & Jurídico",
      "Alto Gobierno & Administración Pública",
      "Gestión Documental",
      "Síntesis Ejecutiva",
      "Listo para propuesta"
    ],
    "readyForSale": True,
    "name": "Resume Expedientes",
    "slogan": "Síntesis ejecutiva de expedientes complejos con IA",
    "description": "Herramienta para directivos y equipos jurídicos que genera resúmenes estructurados de expedientes administrativos y judiciales de cientos de páginas en segundos.",
    "status": "En línea",
    "demoMode": "mostrar",
    "appUrl": "https://resume-expedientes-production.up.railway.app/",
    "githubUrl": "https://github.com/Juansotag/Resume-Expedientes",
    "logo": "assets/projects/resumeexpedientes.png",
    "videoUrl": "https://drive.google.com/file/d/1Xl2Nlq7l44o50H15gNlBqL4894xG960X/view?usp=drive_link",
    "pptUrl": ""
  },
  {
    "segment": "Sector Privado",
    "tipo": "Software",
    "linea": "Proyección Social & Directiva",
    "tags": [
      "Medios & Prensa",
      "Comunicación Institucional",
      "Proyección Social",
      "Newsletter Automatizado",
      "Listo para propuesta"
    ],
    "readyForSale": True,
    "name": "NewsletterMaker",
    "slogan": "Boletines institucionales automáticos con IA",
    "description": "Generador automatizado de newsletters temáticos a partir de fuentes de noticias, publicaciones académicas y comunicados oficiales. Distribución por correo y WhatsApp.",
    "status": "En línea",
    "demoMode": "mostrar",
    "appUrl": "https://newslettermaker-production.up.railway.app/",
    "githubUrl": "https://github.com/Juansotag/NewsletterMaker",
    "logo": "assets/projects/newslettermaker.png",
    "videoUrl": "",
    "pptUrl": ""
  },
  {
    "segment": "Sector Público",
    "tipo": "Software",
    "linea": "Gestión Pública & Ambiental",
    "tags": [
      "Medio Ambiente & Sostenibilidad",
      "Sector Público & CAR",
      "Atención Ciudadana",
      "PQRS Ambiental",
      "Listo para propuesta"
    ],
    "readyForSale": True,
    "name": "CAResponde",
    "slogan": "Atención inteligente a solicitudes ambientales",
    "description": "Sistema de clasificación y respuesta automática de solicitudes ciudadanas y denuncias ambientales para la Corporación Autónoma Regional de Cundinamarca (CAR).",
    "status": "En línea",
    "demoMode": "mostrar",
    "appUrl": "https://caresponde-production.up.railway.app/",
    "githubUrl": "https://github.com/Juansotag/CAResponde",
    "logo": "assets/projects/caresponde.png",
    "videoUrl": "https://drive.google.com/file/d/1Xl2Nlq7l44o50H15gNlBqL4894xG960X/view?usp=drive_link",
    "pptUrl": ""
  },
  {
    "segment": "Sector Público",
    "tipo": "Software",
    "linea": "Gestión Pública & Ambiental",
    "tags": [
      "Gobiernos Locales & Distritales",
      "Sector Público",
      "Participación Ciudadana",
      "Plan de Desarrollo",
      "Listo para propuesta"
    ],
    "readyForSale": True,
    "name": "AlcaldIA",
    "slogan": "Conocimiento del plan de desarrollo al alcance de todos",
    "description": "Chatbot basado en RAG sobre los documentos del Plan de Desarrollo Distrital de Bogotá. Responde preguntas de ciudadanos y funcionarios con citación exacta de metas y presupuestos.",
    "status": "En línea",
    "demoMode": "mostrar",
    "appUrl": "https://alcaldia-production.up.railway.app/",
    "githubUrl": "https://github.com/Juansotag/AlcaldIA",
    "logo": "assets/projects/alcaldia.png",
    "videoUrl": "",
    "pptUrl": ""
  },
  {
    "segment": "Sector Público",
    "tipo": "Software",
    "linea": "Gestión Pública & Ambiental",
    "tags": [
      "Seguridad & Policía",
      "Medio Ambiente & Biodiversidad",
      "Sector Público",
      "Legislación Ambiental"
    ],
    "readyForSale": False,
    "name": "PoliciApp-Eco",
    "slogan": "Asistente normativo para la policía ambiental en campo",
    "description": "Aplicación móvil de consulta rápida para agentes de la Dirección de Carabineros y Protección Ambiental. Tipificación de delitos ecológicos, rutas de atención e incautación de fauna/flora.",
    "status": "En línea",
    "demoMode": "mostrar",
    "appUrl": "https://policiapp-eco-production.up.railway.app/",
    "githubUrl": "https://github.com/Juansotag/PoliciApp-Eco",
    "logo": "assets/projects/policiaeco.png",
    "videoUrl": "",
    "pptUrl": ""
  },
  {
    "segment": "Sector Público",
    "tipo": "Software",
    "linea": "Gestión Pública & Ambiental",
    "tags": [
      "Seguridad & Policía",
      "Medio Ambiente & Conservación",
      "Sector Público",
      "Normativa Ambiental"
    ],
    "readyForSale": False,
    "name": "PoliciaAmbiental",
    "slogan": "Base de conocimiento legal para protección ambiental",
    "description": "Chatbot especializado en normativa ambiental colombiana (Leyes, Decretos, Resoluciones MinAmbiente). Orientación en procedimientos sancionatorios y medidas preventivas.",
    "status": "En línea",
    "demoMode": "mostrar",
    "appUrl": "https://policia-ambiental-production.up.railway.app/",
    "githubUrl": "https://github.com/Juansotag/PoliciaAmbiental",
    "logo": "assets/projects/policiaeco.png",
    "videoUrl": "",
    "pptUrl": ""
  },
  {
    "segment": "Sector Público",
    "tipo": "Software",
    "linea": "Gestión Pública & Ambiental",
    "tags": [
      "Sector Legislativo & Congreso",
      "Asuntos Públicos & Regulatorios",
      "Consultoría Jurídica",
      "Diff Normativo"
    ],
    "readyForSale": False,
    "name": "LegisCheck",
    "slogan": "Comparación y análisis semántico de proyectos de ley",
    "description": "Herramienta que analiza diferencias entre ponencias y versiones de proyectos de ley en el Congreso. Detecta cambios de fondo, impactos regulatorios y posibles contradicciones.",
    "status": "En línea",
    "demoMode": "mostrar",
    "appUrl": "https://legischeck-production.up.railway.app/",
    "githubUrl": "https://github.com/Juansotag/LegisCheck",
    "logo": "assets/projects/legischeck.png",
    "videoUrl": "",
    "pptUrl": ""
  },
  {
    "segment": "Sector Público",
    "tipo": "Software",
    "linea": "Seguridad & Analítica",
    "tags": [
      "Seguridad Ciudadana & Policía",
      "Gobiernos Locales & Distritales",
      "Analítica Predictiva",
      "Observatorio de Seguridad",
      "Listo para propuesta"
    ],
    "readyForSale": True,
    "name": "Barranquilla",
    "slogan": "Analítica predictiva para la seguridad de Barranquilla",
    "description": "Observatorio de seguridad ciudadana con modelos predictivos de delito a nivel de cuadrante y barrio. Permite a la alcaldía y policía focalizar operativos de prevención.",
    "status": "En línea",
    "demoMode": "mostrar",
    "appUrl": "https://barranquilla-production.up.railway.app/",
    "githubUrl": "https://github.com/Juansotag/Barranquilla",
    "logo": "assets/projects/barranquilla.png",
    "videoUrl": "https://drive.google.com/file/d/1Xl2Nlq7l44o50H15gNlBqL4894xG960X/view?usp=drive_link",
    "pptUrl": ""
  },
  {
    "segment": "Sector Privado",
    "tipo": "Software",
    "linea": "Sostenibilidad & ESG",
    "tags": [
      "Educación Superior & Universidades",
      "Sostenibilidad & ESG",
      "Benchmarking Institucional",
      "Universia",
      "Listo para propuesta"
    ],
    "readyForSale": True,
    "name": "Test de sostenibilidad universitaria",
    "slogan": "Mide el compromiso ESG de tu universidad",
    "description": "Herramienta de autoevaluación y benchmarking de sostenibilidad para instituciones de educación superior. Métricas en gobernanza, impacto ambiental, inclusión y campus sostenible.",
    "status": "En línea",
    "demoMode": "mostrar",
    "appUrl": "https://test-sostenibilidad-production.up.railway.app/",
    "githubUrl": "https://github.com/Juansotag/Test-Sostenibilidad",
    "logo": "assets/projects/sostenibilidad.png",
    "videoUrl": "",
    "pptUrl": ""
  },
  {
    "segment": "Sector Privado",
    "tipo": "Software",
    "linea": "Sostenibilidad & ESG",
    "tags": [
      "Educación Superior & Redes",
      "Tecnología Educativa",
      "Data Science & IA",
      "MetaRed",
      "Listo para propuesta"
    ],
    "readyForSale": True,
    "name": "Asistente de agente para MetaRed",
    "slogan": "Analítica y recomendaciones para redes universitarias",
    "description": "Agente analítico desarrollado para la red MetaRed (Universia). Procesa encuestas de madurez digital universitaria y genera hojas de ruta de transformación tecnológica personalizadas.",
    "status": "En línea",
    "demoMode": "mostrar",
    "appUrl": "https://metared-production.up.railway.app/",
    "githubUrl": "https://github.com/Juansotag/MetaRed-Assistant",
    "logo": "assets/projects/metared.png",
    "videoUrl": "",
    "pptUrl": ""
  },
  {
    "segment": "Sector Público",
    "tipo": "Software",
    "linea": "Comunidad & Admisiones",
    "tags": [
      "Educación Superior",
      "Gobierno & Políticas Públicas",
      "Admisiones & Posgrados",
      "MPA",
      "Listo para propuesta"
    ],
    "readyForSale": True,
    "name": "MPAChat",
    "slogan": "Orientación personalizada para aspirantes a posgrado",
    "description": "Chatbot con matching de perfil profesional para aspirantes a la Maestría en Políticas Públicas (MPA) de La Sabana. Analiza CV del aspirante y recomienda énfasis formativo.",
    "status": "En línea",
    "demoMode": "mostrar",
    "appUrl": "https://mpachat-production.up.railway.app/",
    "githubUrl": "https://github.com/Juansotag/MPAChat",
    "logo": "assets/projects/mpachat.png",
    "videoUrl": "",
    "pptUrl": ""
  },
  {
    "segment": "Sector Privado",
    "tipo": "Software",
    "linea": "Comunidad & Admisiones",
    "tags": [
      "Educación Superior",
      "Recursos Humanos & Empleabilidad",
      "Gestión de Talento",
      "Unisabana",
      "Listo para propuesta"
    ],
    "readyForSale": True,
    "name": "AlumniCV",
    "slogan": "Optimiza tu hoja de vida con retroalimentación IA",
    "description": "Plataforma para egresados de La Sabana que analiza hojas de vida frente a vacantes deseadas. Sugiere mejoras de redacción, palabras clave ATS y habilidades a fortalecer.",
    "status": "En línea",
    "demoMode": "mostrar",
    "appUrl": "https://alumnicv-production.up.railway.app/",
    "githubUrl": "https://github.com/Juansotag/AlumniCV",
    "logo": "assets/projects/alumni.png",
    "videoUrl": "",
    "pptUrl": ""
  },
  {
    "segment": "Sector Privado",
    "tipo": "Software",
    "linea": "Comunidad & Admisiones",
    "tags": [
      "Educación Superior",
      "Comunidad Alumni & Posgrados",
      "Orientación Profesional",
      "Chatbot",
      "Listo para propuesta"
    ],
    "readyForSale": True,
    "name": "AlumniChat",
    "slogan": "Conecta con la oferta de posgrados y vida profesional",
    "description": "Canal conversacional 24/7 para la comunidad de egresados. Información sobre educación continuada, beneficios para graduados, networking y eventos institucionales.",
    "status": "En línea",
    "demoMode": "mostrar",
    "appUrl": "https://alumnichat-production.up.railway.app/",
    "githubUrl": "https://github.com/Juansotag/AlumniChat",
    "logo": "assets/projects/alumni.png",
    "videoUrl": "",
    "pptUrl": ""
  },
  {
    "segment": "Sector Privado",
    "tipo": "Software",
    "linea": "Innovación & Procesos",
    "tags": [
      "Educación Superior",
      "Emprendimiento & Startups",
      "Innovación & Propiedad Intelectual",
      "Business Model Canvas",
      "Listo para propuesta"
    ],
    "readyForSale": True,
    "name": "Germina",
    "slogan": "De la idea de investigación al modelo de negocio",
    "description": "Asistente para la Dirección de Innovación de Unisabana. Acompaña a investigadores y emprendedores en la estructuración de proyectos, validación de mercado y propiedad intelectual.",
    "status": "En línea",
    "demoMode": "mostrar",
    "appUrl": "https://germina-production.up.railway.app/",
    "githubUrl": "https://github.com/Juansotag/Germina",
    "logo": "assets/projects/germina.png",
    "videoUrl": "",
    "pptUrl": ""
  },
  {
    "segment": "Sector Privado",
    "tipo": "Software",
    "linea": "Inteligencia Geoespacial",
    "tags": [
      "Inmobiliario & PropTech",
      "Urbanismo & Vivienda",
      "Construcción & Finca Raíz",
      "Leaflet",
      "Listo para propuesta"
    ],
    "readyForSale": True,
    "name": "Geovivienda",
    "slogan": "Inteligencia inmobiliaria y territorial en un mapa",
    "description": "Plataforma geoespacial que cruza oferta inmobiliaria, precios por metro cuadrado, estratificación y accesibilidad a servicios en Sabana Centro y Bogotá.",
    "status": "En línea",
    "demoMode": "mostrar",
    "appUrl": "https://geovivienda-production.up.railway.app/",
    "githubUrl": "https://github.com/Juansotag/Geovivienda",
    "logo": "assets/projects/geovivienda.png",
    "videoUrl": "",
    "pptUrl": ""
  },
  {
    "segment": "Transversal",
    "tipo": "Software",
    "linea": "Analítica con IA",
    "tags": [
      "Business Intelligence & Analítica",
      "Consultoría Empresarial",
      "Tecnología Transversal",
      "Auto-Gráficos",
      "Listo para propuesta"
    ],
    "readyForSale": True,
    "name": "Data Copilot",
    "slogan": "Pregúntale a tus datos en lenguaje natural",
    "description": "Copiloto analítico que traduce preguntas en español a consultas SQL/Python, genera visualizaciones interactivas automáticas y produce narrativas ejecutivas de hallazgos.",
    "status": "En línea",
    "demoMode": "mostrar",
    "appUrl": "https://data-copilot-production.up.railway.app/",
    "githubUrl": "https://github.com/Juansotag/DataCopilot",
    "logo": "assets/projects/datacopilot.png",
    "videoUrl": "",
    "pptUrl": ""
  },
  {
    "segment": "Sector Público",
    "tipo": "Software",
    "linea": "Dashboards & Analítica",
    "tags": [
      "Opinión Pública & Think Tanks",
      "Sector Público",
      "Democracia & Gobernanza",
      "INVAMER",
      "Listo para propuesta"
    ],
    "readyForSale": True,
    "name": "Cuidar la Democracia",
    "slogan": "Visualiza lo que piensa el ciudadano",
    "description": "Dashboard interactivo con datos de encuesta sobre percepciones democráticas en Colombia (INVAMER/GovLab). Filtros sociodemográficos, mapas y gráficos en tiempo real.",
    "status": "En línea",
    "demoMode": "mostrar",
    "appUrl": "https://cuidar-la-democracia-production.up.railway.app/",
    "githubUrl": "https://github.com/Juansotag/Cuidar-la-Democracia",
    "logo": "assets/projects/democracia.png",
    "videoUrl": "https://drive.google.com/file/d/1cGZzC2g1HsFeL4M3TziwMUL9o692WI-x/view?usp=drive_link",
    "pptUrl": ""
  },
  {
    "segment": "Sector Público",
    "tipo": "Software",
    "linea": "Dashboards & Analítica",
    "tags": [
      "Desarrollo Regional & Fondos Públicos",
      "Sector Público Departamental",
      "Inversión Social",
      "FONDECUN",
      "Listo para propuesta"
    ],
    "readyForSale": True,
    "name": "Data Promce",
    "slogan": "Seguimiento al impacto de proyectos de desarrollo",
    "description": "Tablero de visualización de indicadores de gestión, inversión y cobertura de los programas ejecutados por FONDECUN en los municipios de Cundinamarca.",
    "status": "En línea",
    "demoMode": "mostrar",
    "appUrl": "https://data-promce-production.up.railway.app/",
    "githubUrl": "https://github.com/Juansotag/Data-Promce",
    "logo": "assets/projects/datapromce.png",
    "videoUrl": "",
    "pptUrl": ""
  },
  {
    "segment": "Sector Público",
    "tipo": "Software",
    "linea": "Dashboards & Analítica",
    "tags": [
      "Desarrollo Regional & Territorio",
      "Sostenibilidad & ESG",
      "Think Tanks & Gremios",
      "Sabana Centro",
      "Listo para propuesta"
    ],
    "readyForSale": True,
    "name": "Sabana Centro Sostenible",
    "slogan": "Monitoreo del desarrollo territorial en Sabana Centro",
    "description": "Plataforma de seguimiento a las metas de sostenibilidad y competitividad de los 11 municipios de la provincia de Sabana Centro, en alianza con Sabana Centro Cómo Vamos.",
    "status": "En línea",
    "demoMode": "mostrar",
    "appUrl": "https://sabana-centro-sostenible-production.up.railway.app/",
    "githubUrl": "https://github.com/Juansotag/Sabana-Centro-Sostenible",
    "logo": "assets/projects/sabanacentro.png",
    "videoUrl": "",
    "pptUrl": ""
  },
  {
    "segment": "Sector Privado",
    "tipo": "Dashboards",
    "linea": "Dashboards & Analítica",
    "tags": [
      "Educación Superior",
      "Planificación Estratégica",
      "Gestión Universitaria",
      "Tableau"
    ],
    "readyForSale": False,
    "name": "SIAG",
    "slogan": "Sistema de inteligencia analítica para la gestión",
    "description": "Dashboard institucional para el seguimiento de metas estratégicas, matrícula estudiantil, retención y desempeño financiero de unidades académicas.",
    "status": "En línea",
    "demoMode": "mostrar",
    "appUrl": "https://public.tableau.com/views/SIAG_Dashboard/Inicio",
    "githubUrl": "",
    "logo": "assets/projects/siag.png",
    "videoUrl": "",
    "pptUrl": ""
  },
  {
    "segment": "Sector Público",
    "tipo": "Dashboards",
    "linea": "Dashboards & Analítica",
    "tags": [
      "Seguridad Ciudadana",
      "Sector Social & Género",
      "Sector Público",
      "Tableau"
    ],
    "readyForSale": False,
    "name": "Violencia Intrafamiliar en Colombia",
    "slogan": "Radiografía nacional de la violencia en los hogares",
    "description": "Visualización analítica con datos de la Policía Nacional sobre denuncias de violencia intrafamiliar por departamento, municipio, grupo etario y género.",
    "status": "En línea",
    "demoMode": "mostrar",
    "appUrl": "https://public.tableau.com/views/ViolenciaIntrafamiliarColombia/Dashboard",
    "githubUrl": "",
    "logo": "assets/projects/violencia.png",
    "videoUrl": "",
    "pptUrl": ""
  },
  {
    "segment": "Sector Público",
    "tipo": "Dashboards",
    "linea": "Dashboards & Analítica",
    "tags": [
      "Salud Pública",
      "Hospitales & Clínicas",
      "Sector Salud",
      "Tableau"
    ],
    "readyForSale": False,
    "name": "Recursos hospitalarios por cada 100.000 habitantes",
    "slogan": "Capacidad del sistema de salud en el territorio",
    "description": "Dashboard que mapea la disponibilidad de camas hospitalarias, UCI, ambulancias y personal médico por departamento frente a la densidad poblacional.",
    "status": "En línea",
    "demoMode": "mostrar",
    "appUrl": "https://public.tableau.com/views/RecursosHospitalariosColombia/Dashboard",
    "githubUrl": "",
    "logo": "assets/projects/salud.png",
    "videoUrl": "",
    "pptUrl": ""
  },
  {
    "segment": "Sector Público",
    "tipo": "Dashboards",
    "linea": "Dashboards & Analítica",
    "tags": [
      "Salud Pública & Aseguramiento",
      "EPS & IPS",
      "Sector Salud",
      "ADRES",
      "Tableau"
    ],
    "readyForSale": False,
    "name": "Registros de la Base Única de afiliados - Adres - Mayo 2025",
    "slogan": "Estructura del aseguramiento en salud en Colombia",
    "description": "Análisis de afiliación al Sistema General de Seguridad Social en Salud: régimen contributivo vs. subsidiado, pirámide de edad y cobertura departamental.",
    "status": "En línea",
    "demoMode": "mostrar",
    "appUrl": "https://public.tableau.com/views/BDUA_Adres_2025/Dashboard",
    "githubUrl": "",
    "logo": "assets/projects/adres.png",
    "videoUrl": "",
    "pptUrl": ""
  },
  {
    "segment": "Sector Público",
    "tipo": "Dashboards",
    "linea": "Dashboards & Analítica",
    "tags": [
      "Demografía & Política Social",
      "Salud & Bienestar Social",
      "Sector Público",
      "Tableau"
    ],
    "readyForSale": False,
    "name": "Envejecimiento poblacional en Colombia por Sexo y Área",
    "slogan": "Transición demográfica y territorio",
    "description": "Historia interactiva sobre las curvas de envejecimiento y pirámides poblacionales urbanas y rurales en Colombia.",
    "status": "En línea",
    "demoMode": "mostrar",
    "appUrl": "https://public.tableau.com/views/EnvejecimientoPoblacional_SexoArea/Story",
    "githubUrl": "",
    "logo": "assets/projects/envejecimiento.png",
    "videoUrl": "",
    "pptUrl": ""
  },
  {
    "segment": "Sector Público",
    "tipo": "Dashboards",
    "linea": "Dashboards & Analítica",
    "tags": [
      "Seguridad & Defensa",
      "Justicia Penal",
      "Sector Público & Policía",
      "Tableau"
    ],
    "readyForSale": False,
    "name": "Panorama de la Extorsión en Colombia (2010-2024)",
    "slogan": "Evolución de un delito de alto impacto",
    "description": "Análisis longitudinal de denuncias, modalidades y focos territoriales del delito de extorsión a lo largo de 14 años.",
    "status": "En línea",
    "demoMode": "mostrar",
    "appUrl": "https://public.tableau.com/views/ExtorsionColombia2010_2024/Dashboard",
    "githubUrl": "",
    "logo": "assets/projects/extorsion.png",
    "videoUrl": "",
    "pptUrl": ""
  },
  {
    "segment": "Sector Público",
    "tipo": "Dashboards",
    "linea": "Dashboards & Analítica",
    "tags": [
      "Justicia & Protección Social",
      "Seguridad Ciudadana",
      "Sector Público",
      "Tableau"
    ],
    "readyForSale": False,
    "name": "Delitos Sexuales en Colombia",
    "slogan": "Evidencia para la protección ciudadana",
    "description": "Mapeo y caracterización de reportes de delitos sexuales para el diseño de políticas de prevención y justicia focalizada.",
    "status": "En línea",
    "demoMode": "mostrar",
    "appUrl": "https://public.tableau.com/views/DelitosSexualesColombia/Dashboard",
    "githubUrl": "",
    "logo": "assets/projects/delitos.png",
    "videoUrl": "",
    "pptUrl": ""
  },
  {
    "segment": "Sector Público",
    "tipo": "Dashboards",
    "linea": "Dashboards & Analítica",
    "tags": [
      "Demografía & Bienestar",
      "Salud & Cuidado",
      "Sector Público & Adulto Mayor",
      "Tableau"
    ],
    "readyForSale": False,
    "name": "El Panorama del envejecimiento poblacional en Colombia",
    "slogan": "Retos de la longevidad y servicios sociales",
    "description": "Dashboard integral con indicadores de dependencia, índice de envejecimiento y distribución departamental.",
    "status": "En línea",
    "demoMode": "mostrar",
    "appUrl": "https://public.tableau.com/views/PanoramaEnvejecimientoColombia/Dashboard",
    "githubUrl": "",
    "logo": "assets/projects/envejecimiento.png",
    "videoUrl": "",
    "pptUrl": ""
  },
  {
    "segment": "Sector Público",
    "tipo": "Dashboards",
    "linea": "Dashboards & Analítica",
    "tags": [
      "Salud Mental & Salud Pública",
      "Sector Social & Epidemiología",
      "Sector Salud",
      "Tableau"
    ],
    "readyForSale": False,
    "name": "Suicidios en Colombia 2023-2024",
    "slogan": "Datos para la salud mental pública",
    "description": "Monitoreo descriptivo y espacial de eventos de salud mental y suicidio reportados en el territorio nacional.",
    "status": "En línea",
    "demoMode": "mostrar",
    "appUrl": "https://public.tableau.com/views/SuicidiosColombia2023_2024/Dashboard",
    "githubUrl": "",
    "logo": "assets/projects/salud.png",
    "videoUrl": "",
    "pptUrl": ""
  },
  {
    "segment": "Sector Público",
    "tipo": "Dashboards",
    "linea": "Dashboards & Analítica",
    "tags": [
      "Servicios de Emergencia & NUSE 123",
      "Seguridad Ciudadana",
      "Gobiernos Locales & Distritales",
      "Tableau"
    ],
    "readyForSale": False,
    "name": "Llamadas totales al NUSE/123 por UPZ en Bogotá",
    "slogan": "Llamadas de emergencia a escala barrial",
    "description": "Distribución geográfica por Unidades de Planeamiento Zonal (UPZ) de llamadas atendidas por la línea única de emergencias de Bogotá.",
    "status": "En línea",
    "demoMode": "mostrar",
    "appUrl": "https://public.tableau.com/views/NUSE123_UPZ_Bogota/Dashboard",
    "githubUrl": "",
    "logo": "assets/projects/nuse.png",
    "videoUrl": "",
    "pptUrl": ""
  },
  {
    "segment": "Sector Público",
    "tipo": "Dashboards",
    "linea": "Dashboards & Analítica",
    "tags": [
      "Agroindustria & Sector Arrocero",
      "Comercio & Abastecimiento",
      "Sector Agrícola",
      "Forecasting",
      "Tableau"
    ],
    "readyForSale": False,
    "name": "Precios y productividad del arroz - Forecasting",
    "slogan": "Pronóstico de precios y cosechas agrícolas",
    "description": "Modelo predictivo de series temporales de precios mayoristas y rendimiento por hectárea en el sector arrocero.",
    "status": "En línea",
    "demoMode": "mostrar",
    "appUrl": "https://public.tableau.com/views/ArrozForecasting/Dashboard",
    "githubUrl": "",
    "logo": "assets/projects/agro.png",
    "videoUrl": "",
    "pptUrl": ""
  },
  {
    "segment": "Sector Público",
    "tipo": "Dashboards",
    "linea": "Dashboards & Analítica",
    "tags": [
      "Movilidad & Transporte",
      "Seguridad Vial",
      "Tránsito Urbano",
      "Forecasting",
      "Tableau"
    ],
    "readyForSale": False,
    "name": "Siniestralidad vial en Bogotá - Forecasting",
    "slogan": "Modelos predictivos de accidentalidad vial",
    "description": "Predicción de eventos de siniestros viales en corredores viales clave de Bogotá mediante técnicas de forecasting.",
    "status": "En línea",
    "demoMode": "mostrar",
    "appUrl": "https://public.tableau.com/views/SiniestralidadBogota_Forecasting/Dashboard",
    "githubUrl": "",
    "logo": "assets/projects/movilidad.png",
    "videoUrl": "",
    "pptUrl": ""
  },
  {
    "segment": "Sector Público",
    "tipo": "Dashboards",
    "linea": "Dashboards & Analítica",
    "tags": [
      "Movilidad & Transporte",
      "Seguridad Vial",
      "Gobiernos Locales & Tránsito",
      "Tableau"
    ],
    "readyForSale": False,
    "name": "Siniestralidad vial en Bogotá - Siniestros",
    "slogan": "Registro y causas de accidentes de tránsito",
    "description": "Visualización histórica 2019-2023 de siniestros viales clasificados por tipo de vehículo, horario y localidad.",
    "status": "En línea",
    "demoMode": "mostrar",
    "appUrl": "https://public.tableau.com/views/SiniestralidadBogota_Siniestros/Dashboard",
    "githubUrl": "",
    "logo": "assets/projects/movilidad.png",
    "videoUrl": "",
    "pptUrl": ""
  },
  {
    "segment": "Sector Público",
    "tipo": "Dashboards",
    "linea": "Dashboards & Analítica",
    "tags": [
      "Movilidad & Transporte",
      "Seguridad Vial",
      "Salud Pública",
      "Tableau"
    ],
    "readyForSale": False,
    "name": "Siniestralidad vial en Bogotá - Víctimas",
    "slogan": "Perfil de actores viales y lesionados",
    "description": "Tablero enfocado en peatones, ciclistas y motociclistas afectados en eventos viales en la capital.",
    "status": "En línea",
    "demoMode": "mostrar",
    "appUrl": "https://public.tableau.com/views/SiniestralidadBogota_Victimas/Dashboard",
    "githubUrl": "",
    "logo": "assets/projects/movilidad.png",
    "videoUrl": "",
    "pptUrl": ""
  },
  {
    "segment": "Sector Público",
    "tipo": "Dashboards",
    "linea": "Dashboards & Analítica",
    "tags": [
      "Movilidad & Transporte",
      "Urbanismo & Tránsito",
      "Geoanalítica & Puntos Críticos",
      "Tableau"
    ],
    "readyForSale": False,
    "name": "Siniestralidad vial en Bogotá - Análisis espacial",
    "slogan": "Puntos críticos e intersecciones de alto riesgo",
    "description": "Análisis de concentración geoespacial de accidentes e identificación de tramos viales prioritarios para intervención.",
    "status": "En línea",
    "demoMode": "mostrar",
    "appUrl": "https://public.tableau.com/views/SiniestralidadBogota_Espacial/Dashboard",
    "githubUrl": "",
    "logo": "assets/projects/movilidad.png",
    "videoUrl": "",
    "pptUrl": ""
  },
  {
    "segment": "Sector Público",
    "tipo": "Dashboards",
    "linea": "Dashboards & Analítica",
    "tags": [
      "Servicios de Emergencia & NUSE 123",
      "Seguridad Ciudadana",
      "Capacidad Operativa",
      "Forecasting",
      "Tableau"
    ],
    "readyForSale": False,
    "name": "Llamadas totales al NUSE/123 por UPZ en Bogotá - Forecasting",
    "slogan": "Pronóstico de demanda de atención de emergencias",
    "description": "Modelos predictivos de volumen de llamadas al NUSE por UPZ para optimizar el despliegue de patrullas y ambulancias.",
    "status": "En línea",
    "demoMode": "mostrar",
    "appUrl": "https://public.tableau.com/views/NUSE123_UPZ_Forecasting/Dashboard",
    "githubUrl": "",
    "logo": "assets/projects/nuse.png",
    "videoUrl": "",
    "pptUrl": ""
  },
  {
    "segment": "Sector Público",
    "tipo": "Estudios & Análisis de datos",
    "linea": "Salud & Geoanalítica",
    "tags": [
      "Salud & Clínicas Privadas",
      "Gestión Hospitalaria",
      "Sector Salud",
      "Machine Learning & Forecasting"
    ],
    "readyForSale": False,
    "name": "Análisis Clínica Universidad de la Sabana",
    "slogan": "Anticipa la demanda, optimiza los recursos",
    "description": "Sistema ML de series de tiempo (ARIMA y Prophet) con MAE inferior a 10% para pronosticar el número de pacientes NO-EPS y la facturación semanal de la Clínica.",
    "status": "En línea",
    "demoMode": "ppt",
    "appUrl": "",
    "githubUrl": "",
    "logo": "assets/projects/clinica.png",
    "videoUrl": "",
    "pptUrl": "assets/projects/analisis_clinica.pdf"
  },
  {
    "segment": "Sector Público",
    "tipo": "Estudios & Análisis de datos",
    "linea": "Salud & Geoanalítica",
    "tags": [
      "Salud & Clínicas Privadas",
      "Inteligencia Territorial",
      "Sector Salud",
      "Geoanalítica"
    ],
    "readyForSale": False,
    "name": "Geoanálisis Clínica Universidad de la Sabana",
    "slogan": "Encuentra al paciente antes de que llegue",
    "description": "Análisis predictivo geoespacial de la ubicación y patrones de desplazamiento de potenciales usuarios de servicios de salud privados en Sabana Centro.",
    "status": "En línea",
    "demoMode": "ppt",
    "appUrl": "",
    "githubUrl": "",
    "logo": "assets/projects/clinica.png",
    "videoUrl": "",
    "pptUrl": "assets/projects/geoanalisis_clinica.pdf"
  },
  {
    "segment": "Sector Público",
    "tipo": "Estudios & Análisis de datos",
    "linea": "Políticas Públicas & Territorio",
    "tags": [
      "Gobiernos Locales & Municipios",
      "Desarrollo Social & Políticas Públicas",
      "Sector Público"
    ],
    "readyForSale": False,
    "name": "Observatorio Social de Zipaquirá - OSZ",
    "slogan": "Alcaldía de Zipaquirá",
    "description": "Desarrollo y diseño del primer observatorio social de la Región Sabana Centro para el seguimiento riguroso de indicadores sociales y bienestar.",
    "status": "En línea",
    "demoMode": "ppt",
    "appUrl": "",
    "githubUrl": "",
    "logo": "assets/projects/zipaquira.png",
    "videoUrl": "",
    "pptUrl": "assets/projects/osz.pdf"
  },
  {
    "segment": "Sector Público",
    "tipo": "Estudios & Análisis de datos",
    "linea": "Electoral & Pronóstico",
    "tags": [
      "Consultoría Política & Electoral",
      "Medios de Comunicación",
      "Opinión Pública",
      "Minería de Datos"
    ],
    "readyForSale": False,
    "name": "ELA-NOM",
    "slogan": "Pronostica elecciones con redes sociales",
    "description": "Aplicación de una novedosa metodología de pronóstico electoral (ELA-NOM) basada en minería de redes sociales con error predictivo inferior al 9%.",
    "status": "En línea",
    "demoMode": "ppt",
    "appUrl": "",
    "githubUrl": "",
    "logo": "assets/projects/elanom.png",
    "videoUrl": "",
    "pptUrl": "assets/projects/elanom.pdf"
  },
  {
    "segment": "Transversal",
    "tipo": "Educación",
    "linea": "Educación & Formación",
    "tags": [
      "Educación Superior & Posgrados",
      "Investigación Tech & Sector Público",
      "Innovación & IA"
    ],
    "readyForSale": False,
    "name": "Doctorado en IA",
    "slogan": "Investiga el futuro, lidera el cambio",
    "description": "Programa doctoral de investigación de vanguardia en inteligencia artificial, enfocado en soluciones para el sector público y formulación de políticas basadas en evidencia.",
    "status": "En línea",
    "demoMode": "mostrar",
    "appUrl": "https://www.unisabana.edu.co/programas/posgrados/doctorado-en-inteligencia-artificial/",
    "githubUrl": "",
    "logo": "assets/projects/doctorado.png",
    "videoUrl": "",
    "pptUrl": ""
  },
  {
    "segment": "Transversal",
    "tipo": "Educación",
    "linea": "Educación & Formación",
    "tags": [
      "Educación Superior & Posgrados",
      "Formación Ejecutiva & Analítica",
      "Sector Público & Privado"
    ],
    "readyForSale": False,
    "name": "Maestría en IA",
    "slogan": "Domina la IA, transforma tu sector",
    "description": "Programa de posgrado en inteligencia artificial y analítica aplicada con énfasis en gobierno digital, política pública y gestión estratégica organizacional.",
    "status": "En línea",
    "demoMode": "mostrar",
    "appUrl": "https://www.unisabana.edu.co/programas/posgrados/maestria-en-inteligencia-artificial-aplicada/",
    "githubUrl": "",
    "logo": "assets/projects/maestria.png",
    "videoUrl": "",
    "pptUrl": ""
  },
  {
    "segment": "Transversal",
    "tipo": "Educación",
    "linea": "Educación & Formación",
    "tags": [
      "Educación Superior & Pregrados",
      "Ciencia de Datos & Modelado",
      "Talento Tech"
    ],
    "readyForSale": False,
    "name": "Pregrado en IA",
    "slogan": "Aprende IA desde la raíz",
    "description": "Programa de pregrado en Ciencia de Datos e Inteligencia Artificial de la Universidad de La Sabana. Formación integral en modelos, algoritmos y aplicaciones reales.",
    "status": "En línea",
    "demoMode": "mostrar",
    "appUrl": "https://www.unisabana.edu.co/programas/carreras/ingenieria-en-inteligencia-artificial/",
    "githubUrl": "",
    "logo": "assets/projects/pregrado.png",
    "videoUrl": "",
    "pptUrl": ""
  },
  {
    "segment": "Transversal",
    "tipo": "Educación",
    "linea": "Educación & Formación",
    "tags": [
      "Formación Ejecutiva & Capacitación",
      "Sector Corporativo & Público",
      "Educación Continua"
    ],
    "readyForSale": False,
    "name": "Bootcamps en IA",
    "slogan": "Habilidades reales, en tiempo récord",
    "description": "Programas técnicos intensivos de capacitación en IA para profesionales y directivos del sector público y privado, orientados a casos de uso inmediatos.",
    "status": "En línea",
    "demoMode": "mostrar",
    "appUrl": "https://www.unisabana.edu.co/programas/educacion-continua/bootcamps-ia/",
    "githubUrl": "",
    "logo": "assets/projects/bootcamps.png",
    "videoUrl": "",
    "pptUrl": ""
  }
]

with open("products_data.json", "w", encoding="utf-8") as f:
    json.dump(updated_products, f, ensure_ascii=False, indent=2)

print(f"Updated products_data.json successfully with {len(updated_products)} products.")
